- src/utils/getLegacySourceUrl.js
Fixes #67 
Adds a new source to meta search. This is a small source but contains very high-quality images for an important niche (education), so it's a nice addition to fast track.
> Add EDUimages to meta search

- src/components/ContentReport/ContentReportForm.vue
- src/components/ImageDetails/ReuseSurvey.vue
Fixes #66.
This PR updates the the URLs to the Google forms.
> Update to new Google Forms

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
Addresses WordPress/openverse#20.
This PR updates the existing configuration for release drafter.
Changes:
- Added humanized names for worflow job and step
- Updated labels used to categorize PRs into appropriate sections
> Update configuration and workflow for Release Drafter

- src/components/EmbeddedNavSection.vue
- src/components/NavSection.vue
- src/locales/en.json
- src/mixins/iframeHeight.js
- src/pages/feedback.vue
- src/pages/meta-search.vue
Fixes #72.
This PR restores the Feedback page that was removed in #58, with new feedback forms and de-duplicated code.
> Restore Feedback page

- .github/workflows/release-drafter.yml
We changed the default branch name from develop/master to main, this PR updates the action accordingly.
> Run release drafter CI action on push to main branch

- nuxt.config.js
- src/middleware/embed.js
- src/mixins/iframeHeight.js
- src/plugins/message.js
- src/utils/sendMessage.js
This PR improves the communication of the app with outer window in embedded mode.
When used in embedded mode inside an iframe, the app needs to set correct iframe height and display the correct URL in the address bar. This is achieved using messages sent from the app to the outer window. This PR specifically adds the message on every URL change.
Currently, there are two kinds of messages, which have unified format:
1. URL change, which sends the relative URL eg. `{type: 'urlChange', value: '/about' `}
2. Resize, which sends the height that iframe requires, in px, eg. `{type: 'resize', value: 1000 }`
> Add `urlChange` message and unify message format

- src/components/HeroSection.vue
- src/components/HomeLicenseFilter.vue
This PR contains two tiny style fixes: 
1. The home page filter legend wasn't centered:
2. The Search button was a tiny bit smaller than the Search input:
So excited to have the new styles 🎉
> License filter alignment and Search button height fixes

- src/components/Filters/FilterBlock.vue
- src/components/Filters/FilterDisplay.vue
- src/styles/components/button.sass
Currently, the search filter tags are aligned to top vertically.
However, in the design mockups they are center-aligned. This PR centers the filter tags vertically, and removes unnecessary spans from around the tag buttons:
> Make filter display vertically centered

- src/locales/en.json
- src/pages/about.vue
- src/pages/feedback.vue
- src/pages/sources.vue
- src/styles/base/generic.sass
- src/styles/utilities/derived-variables.scss
Fixes #34.
This PR remove the sources table in `/about` page and expand the one in the `/sources` page, as presented in @panchovm's [mockups][mockups] for transitional styles. Also updates the links to the Make WordPress team and to suggest new sources to the Catalog.
[mockups]: https://www.figma.com/file/BlUTIXRHLOq5mRITpDpi3E/Transitional-styles?node-id=0%3A1&viewport=74%2C344%2C0.09312169253826141
https://ov-fe-preview.herokuapp.com/sources
> Update about and sources pages

- src/components/SearchGridManualLoad.vue
Vue-masonry image grid was replaced by flex-based layout. This PR removes unused class and method that were left from `Vue-masonry`.
> Remove vue-masonry-related items

- src/components/Filters/FilterChecklist.vue
- src/components/Filters/FiltersList.vue
- src/locales/en.json
- src/store-modules/filter-store.js
Related to #105 
This PR refactors `FilterChecklist` to remove unnecessary repetition.
It also adds `filter-store` getters for applied filter tags so that the UI gets a list of unified objects for the filter (instead of some filter types that are arrays, some objects and some strings.
This will prepare the code base for adding the media type  specific filters.
> Filter refactor

- nuxt.config.js
- src/components/SearchGridManualLoad.vue
- src/locales/en.json
- src/plugins/vue-i18n.js
Some languages have a more complex set of pluralization rules than 'use a plural form when a number is greater than 1'. The current i18n setup does not take this into account, and the Image Search Result page would have incorrect translation because of that.
This PR adds the pluralization rules for Russian to fix this. Even as a native speaker, my mind is blown by the complexity of the rules :)
The pluralization function is called whenever we use `$tc` function of `vue-i18n` that chooses the correct plural noun in phrases with numbers.
Numbers ending with 2-4 require a different ending than the numbers ending with 5-9: 
<details> …
> Improve i18n pluralization for Russian

- src/components/Filters/FiltersList.vue
- src/constants/media.js
- src/pages/search/audio.vue
- src/pages/search/video.vue
- src/store-modules/filter-store.js
- src/utils/getLegacySourceUrl.js
- src/utils/searchQueryTransform.js
Related to #105, builds on work in #117
This PR adds the correctly-displayed filters for video, as a way of testing the new filter style PR. 
I also removed some unnecessary spreads, and fixed a bug in the approach for removing the 'mature' filter in the `getMediaTypeFilters` function, which was incorrectly removing an array item if the mature filter wasn't present.
> Add correct meta video filters to the new filter method

- src/components/AudioTrack/Waveform.vue
Related to #127 
Set the waveform progress on user click + hover of the waveform. so excited you started this work!
We probably want to lift up some of the state here and make waveform "dumb". It would accept the current progress, the 'preview' progress (the user hover %), and of course the waveform data, and emit events on user hover + click.
then the actual state would live in some sort of `AudioPlayer` parent component, I'd think.
or we could do it this way. either has its pros/cons
> User settable audio track progress

- src/utils/getLegacySourceUrl.js
Tiny change: an issue in the `creativecommons/cccatalog-frontend` was mistakenly changed to a non-existent issue in the `WordPress/openverse-frontend` repository. Changing it back. I scanned the repository, and it doesn't seem to have any other changes like this.
> Fix link to an old issue

- src/locales/en.json
- src/store-modules/filter-store.js
- src/utils/searchQueryTransform.js
- test/unit/specs/store/filter-store.spec.js
- test/unit/specs/utils/searchQueryTransform.spec.js
Continues work on #117
Some API parameters like 'categories', 'extensions' and 'source' have the same names for different media types. This PR renames local image parameters to match the audio filter names (i.e. `categories` becomes `imageCategories`, similar to `audioCategories`). 
Also, before sending a query to the API, this PR filters values for the mentioned parameters to make sure they are applicable for the media type. For example, if we search for images, we should only use `jpeg`, not `mp3`, value `extensions` parameter from the `search/images/categories=jpeg,mp3` queryString.
<details>
``` …
```
> Unify filter category names for different media types

- src/components/SearchGridManualLoad.vue
- src/locales/en.json
- src/store-modules/filter-store.js
Fixes #130 by @obulat
This PR improves wording for displaying the number of results on the search page, and the handling of i18n with it.
Previously, the result count was displayed as "1 image", "N images" or "Over N images" (for more than 10,000 results).
This PR uses the following wording, depending on the result count:
Fewer than 10,000 results: 1 result / N [ image | audio ] results 
More than 10,000 results: Over N [ image| audio] results
To ensure correct word pluralization and correct number formatting in other languages, we need to pass the count to the vue-i18n both as a Number, and a localized string representation (eg. 11,500 for English, 11 500 for Russian, and ١١٬٥٠٠ for Arabic). 
When translating, we will need to ensure that all different pluralization variants are added. …
> Improve result count strings for i18n

- .github/workflows/ci.yml
- package-lock.json
This PR fixes the [CI failure](https://github.com/WordPress/openverse-frontend/runs/3376968464) on the audio branch caused a missing dependency in the `package-lock.json` file.
It also enables tests to run on PRs to `audio` which is the working branch for audio integration.
<details>
```
Version 1.1
Suite D4700
By making a contribution …
```
> Fix CI failure and prevent future failures on audio PRs

- src/components/AudioTrack/AudioTrack.vue
- src/components/AudioTrack/PlayPause.vue
- src/components/AudioTrack/Waveform.vue
- src/components/AudioTrack/meta/AudioTrack.stories.mdx
- src/locales/en.json
- src/utils/searchQueryTransform.js
- Adds the proper ARIA roles to the waveform to make it function as a slider
- Improves play/pause button a11y with a text label and hiding the icon from screen readers
- Adds left + right arrow key seeking + shift key modification (1s seek w/o modifier, 15s seek w/ shift)
- Adds play/pause toggling to the waveform
- I logically wanted to apply this to the entire Audio Track, but doing so means double events on the play/pause button and makes pressing enter on the track title to navigate to the single view toggle the player state
https://user-images.githubusercontent.com/6351754/130304731-40d18745-7fa9-4a42-9242-450c06346820.mp4
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_slider_role
- …
> Audio track + waveform A11y

- package.json
- src/components/Dropdown.vue
- src/components/EmbeddedNavSection.vue
- src/components/NavSection.vue
- src/styles/components/navbar.sass
- test/unit/specs/components/dropdown.spec.js
Fixes #116  by @sarayourfriend 
Adds a Dropdown component based on [Vuetensils' Dropdown](https://raw.githubusercontent.com/AustinGil/Vuetensils/production/src/components/VDropdown/VDropdown.vue) to make the navbar keyboard accessible.
Heavily modifies the Vuetensils' Dropdown to accomodate a couple of things:
0. Make the keyboard navigation behave the same as WordPress.org's navbar (i.e., no arrow key navigation, just tabbing through each item in order)
1. Adds focus management to each child by making an `onFocus` prop available through the default slot. This `onFocus` prop should be used in the `@focus` for each dropdown item. This makes it possible to tab "backwards" from a subsequent navbar item. For example, in the real example of the Openverse dropdown if you <kbd>Shift + Tab</kbd> …
> Fix navbar keyboard accessibility

- src/components/MediaTag/MediaTag.vue
- src/components/MediaTag/meta/MediaTag.stories.mdx
- tailwind.config.js
- test/unit/specs/components/MediaTag/media-tag.spec.js
**Please merge #127 before this**
This PR adds the `MediaTag` component that represents one tag associated with a media item.
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the open source …
```
> Define and document the `MediaTag` component

- json-to-pot.js
Some strings in the translation file have double quotes in them. These are illegal in PO files without escaping. This PR escapes the double quotes in the 'pot' conversion script.
> Replace {} placeholders with ### and escape quotes in strings in POT file

- nuxt.config.js
- package-lock.json
- package.json
- src/components/AudioTrack/Waveform.vue
Fixes #142 by @sarayourfriend 
This PR
- implements drag-to-seek functionality
- switches to composition API to better organise the code
- some minor cleanups, renames and refactors
Vue i18n seems to not work very well with the composition API so usages of `t` in the `<script>` sections requires using the old options API syntax.
<details>
```
Version 1.1
Suite D4700 …
```
> Implement drag-to-seek

- json-to-pot.js
- parse-vue-files.js
- test.pot
This PR adds the reference links to where the strings are located in the code to the POT file. 
```
#: https://github.com/WordPress/openverse-frontend/blob/main/src/components/HeroSection.vue#L6
msgctxt "hero.title"
msgid "Search for content to reuse"
msgstr ""
```
<details>
```
Version 1.1
Suite D4700 …
```
> Add line reference comments to the POT file

- src/components/AudioTrack/PlayPause.vue
- tailwind.config.js
Fixes #148 by @sarayourfriend 
This PR adds a ring around the play/pause toggle button when focused. The Tailwind config added in the PR would also be useful in resolving #147.
The focus outline is only shown for the [`focus-visible` state](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible). Browser support is [good](https://caniuse.com/css-focus-visible) but Safari is the next IE.
The border fades in and out, similar to Gutenberg. Since the button has no rounded corners, neither does the outline.
<details>
```
Version 1.1 …
```
> Add focus style for play/pause button

- src/components/Filters/FiltersList.vue
- src/pages/search.vue
- src/styles/components/navbar.sass
- src/styles/global.scss
- test/iframe-test.html
Fixes https://github.com/WordPress/openverse/issues/56 by @zackkrida 
This PR fixes the iframe height infinite increase issue by removing `100vh` from the height of the sidebar, which was previously used to determine the height of the filter sidebar. This makes the filter sidebar content no longer sticky, but because these are interim styles _anyway_ I think it is okay. In the future we'll need to experiment with `100vh` within the iframe, perhaps replacing it with the browser window height in pixels passed down from the parent.
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation …
```
> Fix iframe infinite height increase issue

- README.md
- src/data/audio-service.js
- src/locales/po-files/openverse.pot
This PR
- fixes a file name that was broken during name refactoring #176
- adds a `README.md` step for fetching translations
- updates the `.pot` file to match the contents of the branch
Without these changes the dev server fails to load. This PR fixes that.
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, …
```
> Perform housekeeping on the `main` branch

- src/components/AudioTrack/Waveform.vue
Fixes #171 by @obulat
This PR defers the initialisation of the `observer` variable to the `onMounted` hook which runs on the client where the ResizeObserver API is available.
The ResizeObserver API is provided by `window`, and thus only exists on the client. Using it in the `setup()` function causes it to be run on the server side of SSR leading to an error. Marking the component as `<ClientOnly>` is not an elegant solution.
See reproduction steps on the issue.
<details>
```
Version 1.1
Suite D4700
San Francisco, …
```
> Attach `ResizeObserver` when component is mounted

- .prettierignore
Storybook files are ignored in the `.gitignore` file. But they still cause some Prettier violations when running Prettier directly. This PR ignores them from Prettier as well.
**Before:**
**After:**
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or …
```
> Ignore Storybook files in Prettier

- src/components/DropdownButton.vue
Hot fix for semantic merge conflict causing the frontend to not compile due to unavailable styles being used in the dropdown button.
Changes the dropdown button styles to stop-gap fix. cc @panchovm for us to fix these styles cause now they don't look so great:
`ring-2` no longer exists, the default width is the only one that exists so we replace it with just `ring`. `ring-offset-1` doesn't exist so we replace it with the only one that does `ring-offset-2`.
Ensure the frontend compiles.
<details>
```
Version 1.1 …
```
> Fix focus styles

- src/components/SearchGridManualLoad.vue
- src/styles/utilities/initial-variables.scss
We have set up self-hosting of fonts in #31. However, they are still also loaded from unpkg. This PR removes `unpkg` loading of the fonts.
Another piece of code removed by this PR is the left-over code from `vue-infinite-loading` plugin that was removed with infinite loading.
<details>
```
Version 1.1
Suite D4700
By making a contribution …
```
> Remove unused code

- src/components/EmbeddedNavSection.vue
- src/components/NavSection.vue
Fixes #218  by @zackkrida 
Initially the API on the Dropdown of Resources in the Navbar was being directed to  https://api.openverse.engineering, now I have redirected it to  https://api.openverse.engineering/v1/ as mention on #218 .
<details>
```
Version 1.1
Suite D4700
(a) The …
```
> Fix the API link in the "Resources" menu dropdown.

- nuxt.config.js
- src/components/HeroSection.vue
- src/components/SearchTypeTabs.vue
- src/pages/search/audio.vue
- src/store-modules/filter-store.js
This PR adds a `process.env.allMediaFeature` feature flag for the displaying of non-image media on Openverse. This will allow us to only enable audio and video support on wordpress.org/openverse when those sources are fully indexed, and prevents us from showing test data live. Currently the flag is used to:
- Hide the 'all' tab, and send users to the 'image' tab from the search bar
- Hide audio files on the audio tab, and mark audio meta search as _unsupported_
- This inadvertently fixes the audio bug in #239 
This `allMediaFeature` is _enabled_ by default, so work can resume as it nothing changed.
<details>
```
Developer …
```
> Add feature flag for non-image media types

- src/locales/en.json
- src/locales/po-files/openverse.pot
It is really minor fix. The commit title is self-explanatory.
I found this typo when translating Openverse to Indonesian during WordPress Translation Day 2021 mini-event.
> Fix typo on WordPress word

- jest.config.js
Fixes #250 by @obulat 
This PR fixes the paths in `jest.config.js` so that running tests also displays the coverage information.
Run `npm run test` and see that we need to write more tests :)
```
---------------------------------|---------|----------|---------|---------|-----------------------------------------------------
File                             | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                   
---------------------------------|---------|----------|---------|---------|-----------------------------------------------------
All files                        |   40.38 |    29.68 |   37.03 |   40.49 |                                                     
ab-tests                        |     100 |      100 |     100 |     100 | …
```
> Fix paths for jest coverage

- src/components/ImageDetails/PhotoDetails.vue
Replace ccsearch with openverse
issue track: https://github.com/WordPress/openverse-frontend/issues/181
Fixes #181 by @obulat
Replaces ref=ccsearch with ref=openverse
Updated URL ref parameter values for analytics.
<details>
```
Version 1.1
Suite D4700 …
```
> Updated URL ref parameter values for analytics for PhotoDetails.vue

- src/components/AudioTrack/layouts/Row.vue
- src/locales/en.json
- src/locales/po-files/openverse.pot
- src/styles/utilities/icon-font.scss
Fixes checks passing on the main branch. Not sure how this lint warning snuck through, but in any case it's a quick fix.
<details>
```
Version 1.1
Suite D4700 …
```
> Linting and formatting hotfixes for AudioTrack Row

- package-lock.json
- package.json
- src/components/DownloadButton.vue
- src/components/DropdownButton.vue
- src/components/meta/DownloadButton.stories.js
- src/locales/en.json
- src/locales/po-files/openverse.pot
- test/unit/specs/components/download-button.spec.js
- test/unit/test-utils/render.js
Related to #149 by @zackkrida 
Adds a new DownloadButton component based on the DropdownButton component.
Adds the `filesize` dependency which is a function for displaying filesizes with their units appropriatly. It's pretty small: https://bundlephobia.com/package/filesize
Most of the behavior of this component is already tested in the DropdownButton component's tests. The behavior around the localStorage would be worth testing though, so I'll add some unit tests for that (assuming JSDOM supports it)
To test this locally run `npm run storybook` and navigate to `/?path=/story/components-downloadbutton--default` to test the component manually. It should even let you download the files 🙂 
[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guideli …
> Add DownloadButton component

- .gitignore
- package.json
- src/components/AudioResultsList.vue
- src/components/AudioTrack/layouts/Full.vue
- src/components/AudioTrack/layouts/Row.vue
- src/locales/en.json
- src/locales/po-files/openverse.pot
- tailwind.config.js
- test/unit/specs/components/AudioTrack/audio-track.spec.js
Fixes #238 by @krysal
This PR updates the AudioTrack component to render even if the `audio` object doens't specify `duration` or `category`. Also, changes the variant according to if the filter sidebar is visible or not, as in mockups [[ref1][mockup1], [ref2][mockup2]]
[mockup1]: https://www.figma.com/file/vEoItpMQyFZb5AZV9aoP7I/Audio-integration?node-id=1070%3A10966
[mockup2]: https://www.figma.com/file/vEoItpMQyFZb5AZV9aoP7I/Audio-integration?node-id=1147%3A12234
Adds an 'Undefined category' to avoid showing the locale key and shows `--:--` in case the duration of the track is unknown. These fields should always be present once we add them to the API, but I believe they are not strictly required to show the component.
I added some minimal tests to verify the component is working, we …
> Change AudioTrack component according to filters sidebar

- src/components/MetaSearch/MetaSearchForm.vue
- src/components/SearchGridManualLoad.vue
- src/locales/en.json
- src/locales/po-files/openverse.pot
- src/pages/search/audio.vue
- src/pages/search/video.vue
Fixes #215  by @zackkrida 
- Added a noresult props to MetaSearchForm.vue, the parent component will pass a boolean(true/false if the query has 0 elements). 
- Remove the old no more image button.
If no more image:
If 0 image in query(no results):
1. Search something e.g.`spacexs`
2. Seach something to give no result e.g.`spacexxxxxxxxxx`
<details>
```
Version 1.1
Suite D4700 …
```
> Remove button styling from "no results" text

- src/locales/scripts/valid-locales.json
Related to i18n locales
However I'm unsure about the relevancy of this current PR, it updates locales in `valid-locales.json`.
Running the command below from the `main` branch adds changes to `valid-locales.json`: 
```bash
npm run i18n:get-translations
```
<details>
```
Version 1.1
Suite D4700 …
```
> Update i18n locales in `valid-locales.json`

- src/locales/scripts/parse-vue-files.js
Fixes #277 by @krysal
This PR fixes file path in `src/locales/po-files/openverse.pot` to be consistent between Windows and Linux.
Running the following command makes references using the relative path from project root directory `src/path/to/file.vue`:
```bash
npm run i18n:generate-pot
```
<details>
```
Version 1.1
Suite D4700
By making …
```
> Fix Windows full path in .pot file

- CONTRIBUTING.md
Fixes #292 by @zackkrida 
Adds a section in the CONTRIBUTION.md README file about types.
N/A
<details>
```
Version 1.1
Suite D4700 …
```
> Add contribution guideline about JSDoc types

- src/components/AppModal.vue
- src/components/AudioDetails/Tags.vue
- src/components/AudioTrack/layouts/Row.vue
- src/components/ContentReport/ContentReportForm.vue
- src/components/ContentReport/DmcaNotice.vue
- src/components/ContentReport/OtherIssueForm.vue
- src/components/ContentReport/ReportError.vue
- src/components/CopyButton.vue
- src/components/ExtensionBrowsers.vue
- src/components/Filters/FilterChecklist.vue
- src/components/Filters/FilterDisplay.vue
- src/components/Filters/FilterTag.vue
- src/components/Filters/FiltersList.vue
- src/components/FooterSection.vue
- src/components/ImageDetails/PhotoDetails.vue
- src/components/MetaSearch/MetaSourceList.vue
- src/components/NavSection.vue
- src/components/SaferBrowsing.vue
- src/components/SearchGridForm.vue
- src/components/SearchGridManualLoad.vue
- src/components/SearchTypeToggle.vue
- test/unit/specs/components/__snapshots__/filter-display.spec.js.snap
- test/unit/specs/components/__snapshots__/filter-tag.spec.js.snap
Updates all existing tailwind styles that used one of the direction specific styles to use the `start/end` styles introduced by the Tailwind CSS RTL plugin
Run the app and ensure that the styles still work in LTR mode. Go ahead and switch the `dir` on the root HTML element to be `rtl` but know that a vast majority of the site has not been converted to have proper RTL support so most of it will be broken. The Tailwind CSS RTL plugin definitely works fine based on the PR that introduced it and what you can see in Storybook so we don't have to test that those _styles_ work correctly, but do check that I've switched the `l` styles to `s` and the `r` styles to `e`. For good measure check that I didn't miss anything (I think my searches worked to catch all the instances of it but I might have …
> Use Tailwind RTL styles everywhere

- src/components/HeroSection.vue
- src/components/HomeLicenseFilter.vue
- src/components/SaferBrowsing.vue
- src/components/ScrollButton.vue
- src/components/SearchGridForm.vue
- src/styles/form/shared.sass
- src/styles/form/tools.sass
- test/unit/specs/components/search-grid-filter.spec.js
Related to #428 by @obulat
Fixes #424 by @dhruvkb 
This PR made the Homepage and Search page RTL-compatible:
The search bar both on the Homepage and on the Search page has corners of the input and button correctly rounded both in LTR and RTL modes. 
The "safer browsing" icon is removed, as in the transitional styles mockup, and its padding is adjusted. 
The scroll to top button is moved to the opposite corner.
You can set the language to Arabic using the `Locale chooser` in the footer of non-embedded page: `http://localhost:8443?embedded=false`, and then look at the RTL styles.
<details>
```
Version …
```
> Make Homepage and Searchbar RTL-compatible

- src/components/SearchGridForm.vue
- src/components/VCheckbox.vue
- src/pages/search.vue
Fixes #436 by @obulat
Related to #428 by @obulat
This PR adjusts the styles of the search grid form on screens smaller than `lg`.
This is the view for small/large screen with these changes:
Here is the current version:
It also fixes the Checkbox checkmark for RTL by changing the `left` positioning value to `start`.
Run the app and search for something, change the screen width, open and close filters and see that the search form height is consistent, and there is a space between the "Filters" button and the search form.
<details>
```
Version 1.1 …
```
> Fix Search form on smaller viewports

- src/pages/about.vue
- src/pages/extension.vue
- src/pages/feedback.vue
- src/pages/meta-search.vue
- src/pages/search-help.vue
- src/pages/sources.vue
Part of #421 by @sarayourfriend
Fixes #431 by @sarayourfriend
Based on a conversation with @dlind1 we'll temporarily force certain untranslated pages back to `ltr` direction for RTL languages. As long as these pages are still falling back to English for RTL languages then we'll keep this around. If we find that some RTL languages are getting translated (or even some pages for it) then we revisit this and do it conditionally based on the locale and page.
This also stops `toLocaleString` for provider resource count using Eastern Arabic numerals in a context when Western Arabic numerals would typically be used.
Checkout this branch and run `npm run dev`. Set your locale to an RTL locale and verify that the pages modified by this PR all have their direction set to LTR. …
> Set explicit ltr direction for pages untranslated in rtl languages

- nuxt.config.js
- package-lock.json
- package.json
Fixes #446 by @zackkrida
This PR updates the `@nuxtjs/sentry` package version to the most recent one, `5.1.5`, which uses Sentry SDK version `6.14.1`, not the most recent`6.15.0`. It also loads Sentry only on production builds to make the development environment faster.
I only ran:
1. `npm ci`
2. `npm run dev` 
3. `npm run build`, `npm run start`. Locally, this raises a CORS error.
After deploy, we can see if there are any problems (which there shouldn't be).
<details>
```
Version 1.1
Suite D4700
San Francisco, CA, …
```
> Update Sentry version and turn it on only for production

- nuxt.config.js
- src/mixins/i18n-sync.js
Fixes #308 by @zackkrida 
This PR adds a `wpLocale` property to the default English locale. This makes it possible to set the locale cookie when the message from wp theme is received.  It also adds the default locale as a fallback for 'en'. I am not sure if it's necessary because I can't test what locale is passed from wp theme in production, but the `lang` property on HTML on wp.org site is set to `en`, unlike the `lang` property on wp.org/openverse, which is set to `en-US` by default, so I added the fallback to be sure.
When you go to `wp.org/openverse`, the wp theme sets the wp `locale` property, and the `lang` and `dir` properties on the `html` element based on the subdomain. For Openverse currently only English subdomain is available, but other subdomains will be used soon.
_I found …
> Set default English locale correctly

- src/store/media.js
This PR fixes a bug in the media store module that prevents second and subsequent fetches to not be decoded as the decoded information is not used and overwritten.
<details>
```
Version 1.1
Suite D4700
have the right …
```
> Fix a typo that prevents subsequent fetches to not be decoded

- README.md
Fixes #494 by @zackkrida 
The text in the readme "You can learn more about the migration to Nuxt.js here." links to a broken page. That has been removed.
<details>
```
Version 1.1
Suite D4700
have the right to submit …
```
> Update README.md to remove broken link

- src/components/AudioResultsList.vue
- src/data/audio-service.js
- src/data/base-media-service.js
- src/data/image-service.js
- src/pages/search.vue
- src/store/media.js
- test/unit/specs/store/media-store.spec.js
This PR makes some improvements to the media stores and services to improve the general code quality.
- changes the results from an array to an object so that referencing results by ID becomes easier
- changes the decoding to be an additional transformation step in the media service
- cleans up the code for merging new results with the old ones
Searching and fetching more results should work as previously.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute …
```
> Add a transform step after receiving data from the API

- src/components/AudioDetails/Tags.vue
- src/components/AudioTrack/layouts/Row.vue
- src/components/MediaTag/MediaTag.vue
- test/unit/specs/components/MediaTag/media-tag.spec.js
Fixes #513 by @sarayourfriend
Fixes #512 by @sarayourfriend
Closes #421 as this will address the last two problems in that issue.
Fixes the RTL visual bugs outlined in the issues.
Checkout this branch and run it with `npm run dev`. Then go to http://localhost:8443/audio/8071128a-bebc-4c24-823d-6e26a2e6dfe2 and verify that the two elements outlined in the issue look good in both RTL and LTR mode. Follow the instructions in [this issue](https://github.com/WordPress/openverse-frontend/issues/421) under the Reproduction headline for how to quickly test RTL and LTR locally.
<details> …
> Fix audio RTL visual bugs

- src/utils/get-legacy-source-url.js
Fixes #299 by @hasanuzzamanbe
New Meta Search Provider "The Greats" added.
Search content in openverse shows some additional Meta Search Provider below the result. "The Greats" is now available on this list.
<details>
```
Version 1.1
Suite D4700 …
```
> Meta Search Provider: The Greats added (ticket #299)

- src/components/AppModal.vue
- src/locales/scripts/wp-locales.json
Fixes #536 by @sarayourfriend 
I ripped out some of the modal stuff like the title and close button. We only have one place the modal is used and it doesn't employ the title prop at all so instead of trying to fix something we don't use, I just took it out.
This is definitely a hacky solution but it does work as a holdover until we can figure out a better one.
Unforunately being inside an iframe makes having modals that make any sense and work as expected basically impossible, but we can put in some stop-gap solutions for now.
Checkout this branch then run `npm run dev`. Run the wporg-openverse theme following [these instructions](https://github.com/WordPress/wordpress.org/blob/0c2992b5dce25ea6c2c959cf6b41a6a2372a1845/wordpress.org/public_html/wp-content/themes/pub/wporg-openverse/README.m …
> Fix filters modal position in iframe

- nuxt.config.js
This PR fixes the auto-import functionality that was broken when adding Storybook smoke tests in #520. Using the `extensions` key to filter the components instead of `ignore` gets the components to work while preserving the passing nature of the smoke test.
As an added bonus, it removes the need to import subdirectories explicitly, using Nuxt's recursive lookup to import *all* Vue files from the `components/` directory!
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and …
```
> Use `extensions` rather than ignore to import components

- nuxt.config.js
- src/composables/use-i18n-sync.js
- src/data/audio-service.js
- src/middleware/middleware.js
- src/mixins/iframe-height.js
- src/plugins/url-change.js
- src/utils/dev.js
- src/utils/env.js
- src/utils/send-message.js
- test/unit/setup.js
Fixes #524 by @sarayourfriend 
Stops importing from `nuxt.config.js` during the runtime. See related issue for the rationale behind this.
Run `pnpm dev` and `pnpm storybook` and verify that they work as expected. There should be no changes to the behavior of the application.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute …
```
> Stop importing from nuxt.config.js

- .github/workflows/gh-pages.yaml
- README.md
Fixes #549 by @sarayourfriend 
Sets up the necessary stuff to deploy Storybook from the `gh-pages` branch by adding a new workflow for pushing to that branch on merge to main.
Let the CI run on this PR and then check the `gh-pages` branch and verify that it's been created and updated.\
You can also see the currently deployed version from https://github.com/WordPress/openverse-frontend/pull/550/commits/cb818064e383d8d429fcba644bd0645f89c5696a here: https://wordpress.github.io/openverse-frontend - after that commit I removed the testing code that was pushing to the `gh-pages` branch in this PR. From now on it will only run on merge to `main`.
- [N/A] I tried running the project locally and verified that there are no …
> Deploy Storybook to GitHub pages

- test/e2e/filters.spec.js
Fixes #572 by @zackkrida
This PR updates the API request urls used in the e2e tests, and un-comments mocking of the request.
Run `pnpm run e2e:ci`. All e2e tests should pass.
<details>
```
Version 1.1
Suite D4700 …
```
> Add API url changes to the e2e tests

- src/components/VInputField/VInputField.vue
- src/components/VInputField/meta/VInputField.stories.mdx
Fixes
- https://github.com/WordPress/openverse-frontend/pull/488#issuecomment-1007177415
- https://github.com/WordPress/openverse-frontend/pull/488#discussion_r780059390
The failing Storybook smoke-test should now pass.
<details>
```
Version 1.1
Suite D4700
(a) The contribution …
```
> Update references to `InputField` to point to `VInputField`

- src/components/AudioThumbnail/AudioThumbnail.vue
- src/components/VAudioThumbnail/VAudioThumbnail.vue
- src/components/VAudioThumbnail/meta/VAudioThumbnail.stories.mdx
- src/components/VAudioTrack/layouts/VGlobalLayout.vue
- src/components/VAudioTrack/layouts/VRowLayout.vue
Fixes #349 by @zackkrida 
This PR adds the code for generating the album art when the audio artwork does not exist or if the image raises an error. It also adds the 'V-' prefix to the component name.
0. Check out the PR and run Storybook.
1. Check out the `VAudioThumbnail` stories and docs.
<details>
```
Version 1.1
Suite D4700
By making …
```
> Show a generated artwork when the audio thumbnail is absent

- src/components/VAudioTrack/VWaveform.vue
When the waveform SVG is loading, the dimensions of the waveform are 0. Since the width of the focus rectangles are computed by subtracting from these dimensions, you get negative values and give errors in the console.
This PR prevents these errors by only rendering them after the dimensions of the SVG become non-zero.
0. Check out the PR and run the Storybook.
1. Render the Waveform stories over and over again.
2. Never see the errors in the console.
<details>
```
Version 1.1
Suite D4700 …
```
> Fix error when `<rect>` dimensions are negative

- src/components/VHeader/VHeader.vue
- src/components/VScrollButton.vue
- src/layouts/default.vue
- src/styles/base/layout.sass
Makes some small adjustments to css grid and the header, along with removing the hardcoded scrollbar styles. 
The main improvement here is that when the sidebar isn't visible, the first column (the main content) will span both grid cells.
The 'main' element is always full height, and it either has 1 full-width child that can scroll, or two (the sidebar added) that scroll independently.
> Remove hardcoded scrollbar styles, fixed header, and hide sidebar on non search views

- src/data/audio-service.js
Currently, there is a warning about missing trailing slash when searching for audio. This PR adds a slash. This way, audio query URL becomes the same as the image query url (`audio/`, `images/`)
Run `pnpm run dev`, and open audio search
<details>
```
Version 1.1
Suite D4700
(a) …
```
> Use correct URL for audio search

- src/locales/en.json
- src/locales/po-files/openverse.pot
This is a quick fix for i18n strings that are missing in audio page attribution components.
Run the app and open Audio search (localhost:8443/search/audio?q=cat) and audio single result page. You should not see any i18n warnings in the console, except for the license name warnings (`[vue-i18n] Cannot translate the value of keypath 'license-names.nc-sampling+'. Use the value of keypath as default.`), which should be fixed by #619.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to …
```
> Add missing strings

- src/components/License/VLicense.vue
- src/constants/license.js
- test/unit/specs/components/v-license.spec.js
There are several CC licenses that [have been retired](https://creativecommons.org/retiredlicenses/), and their use is no longer recommended. In the [discussion about them](https://github.com/WordPress/openverse/discussions/71), we have agreed to show the license names and their icons on search result page and the single result page, but not have specific filters for them.
This PR adds a list of deprecated licenses, and shows only their names "as is" on the frontend, to fix the errors with `VLicense` component on audio page.
Future PRs should add icons and more deprecated licenses to the array. 
Run `pnpm run dev` and search for some audios. 'Cat' search returns some audios from freesound.org that are under `Sampling+` deprecated license. These items should not cause errors with these …
> Show deprecated licenses 

- src/components/VButton.vue
- src/components/VContentSwitcher/VContentTypes.vue
- src/components/VContentSwitcher/VMobileMenuModal.vue
- src/components/VItemGroup/VItem.vue
- src/styles/accent.scss
N/A
This PR adds hover and focus styles to the content switcher items in the popover/modal.
To show a pink outline _inside_ the `VItem`, I had to change the `grouped` button to have an outline inside its `content` instead of the button itself. It might break some other buttons that used `grouped` variant, but I haven't found any.
Run the app and test the content switcher interactions.
<details>
```
Version 1.1
Suite D4700 …
```
> Add interaction styles to the content switcher

- src/components/VAudioTrack/VAudioTrack.vue
- src/components/VAudioTrack/VWaveform.vue
Fixes #628 by @sarayourfriend
Fixes #623 by @sarayourfriend
Replaces https://github.com/WordPress/openverse-frontend/pull/629 which had a coding error fixed in this PR anyway.
Fixes keyboard navigation and both keyboard and mouse based seeking on the waveform.
Checkout the branch and run `pnpm dev`. Visit an audio result like http://localhost:8443/audio/632d0076-fdbd-4919-8b8f-b498ef246ee8 and test the keyboard and mouse waveform seeking on the result waveform. Also test this on the related audio.
Verify that you can:
1. Seek using the mouse
2. Seek multiple tracks and have them start playing at the correct position
3. Seek using the keyboard
4. Tab out of the waveform when using keyboard navigation
- [N/A] I added …
> Fix audio waveform seeking behaviors

- .gitignore
- jest.config.js
This PR adds `.pnpm-debug.log` to the `.gitignore` to prevent tracking it and exclude Storybook stories from jest coverage reports.
Run `pnpm test` and see no more *.stories.js files mentioned, unlike in the main branch.
<details>
```
Version 1.1
Suite D4700
license document, but changing it is …
```
> Ignoring extra files

- package.json
- pnpm-lock.yaml
- src/locales/scripts/ngx-json-to-json.js
I'm not sure how we missed this but this node script depended on a lodash subpackage when lodash isn't explicitly declared as a dependency. I switched to the standalone `lodash.set` instead of `loadash/set` and installed it.
Perhaps another dependency has a peerdep of lodash that isn't installed in prod or something?
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created …
```
> Fix another missing dependency lodash.set

- src/components/VAudioTrack/VAudioTrack.vue
- src/components/VAudioTrack/VGlobalAudioTrack.vue
- src/components/VGlobalAudioSection/VGlobalAudioSection.vue
- src/composables/use-active-audio.js
- tsconfig.json
Fixes #653 by @sarayourfriend
Closes #632 by @sarayourfriend — All audio tracks on the page buffer immediately so there's no longer a delay between playing them... do we need to prevent audio from loading until the "play" button is hit on it or it is seeked? Probably so.
Switches to using a global ref for the currently active audio track and swapping between multiple audio elements (one per track on the page, aside from the global track).
Some notes/key concepts:
1. We derive all state from the state of the audio object, whether the global "active audio" or the local audio. This means our state is updated when the local audio object emits the corresponding events. The only exception to this is the current time. I originally implemented this to always update the `currentTime` ref (which is …
> Fix global audio syncing and seeking issues

- src/components/VAudioTrack/VAudioTrack.vue
- test/e2e/content-types.spec.js
- test/e2e/homepage.spec.js
- test/e2e/search-query-client.spec.js
- test/e2e/search-query-server.spec.js
This PR is a quick fix for e2e tests failures. It does not attempt to add good tests, only make the e2e tests that were written are usable for ci.
Run
1. `pnpm run dev` and `pnpm run test:e2e` - all the tests should pass.
2. Stop the `dev` script running on port 8443 and run `pnpm run e2e:ci` (or trust the GitHub actions to run this :) )
<details>
```
Version 1.1
Suite D4700 …
```
> Make e2e tests pass

- src/components/VAudioThumbnail/meta/VAudioThumbnail.stories.mdx
The PR removes the `toggle` arg-type and the `v-on` bindings from the `VAudioThumbnail` stories as it does not emit any events.
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the open source …
```
> Remove events from `VAudioThumbnail` stories

- src/components/VHeader/VSearchBar/VSearchBar.vue
- src/components/VInputField/VInputField.vue
- src/components/VInputField/meta/VInputField.stories.mdx
- src/locales/en.json
- src/locales/po-files/openverse.pot
- src/pages/index.vue
Fixes #652 by @dhruvkb 
Switches to a static version of the homepage that randomly selects a set of featured images to show. To avoid creating any accessibility problems with these images, they're wrapped in `aria-hidden`.
This removes the animated placeholder text. There is an `aria-label` on the search input that indicates it is for searching.
`VInputField`'s `sr-only` label element was causing a weird "Safari is busy" bug with VoiceOver. Replacing it with an `aria-label` has the same effect as the `sr-only` label element but fixes this bug (I don't know why this bug is happening but we can dig into that a later date).
Checkout this branch and run `pnpm dev`. Visit the site in Safari with VoiceOver and verify that you can successfully navigate the homepage and execute a search.
Note: …
> Fix homepage accessibility

- src/components/VContentSwitcher/meta/VContentSwitcherPopover.stories.mdx
This PR adds a story for the `VContentSwitcher` component. This should make it easier to develop #639 in isolation.
<details>
```
Version 1.1
Suite D4700 …
```
> Add stories for the content type switcher

- nuxt.config.js
- package.json
- pnpm-lock.yaml
- src/components/VAudioTrack/VWaveform.vue
- src/components/VAudioTrack/layouts/VRowLayout.vue
- src/composables/use-browser-detection.js
- src/locales/en.json
- src/locales/po-files/openverse.pot
- src/plugins/ua-parse.js
- test/unit/specs/components/AudioTrack/audio-track.spec.js
Fixes #680 by @zackkrida 
Adds a `featureNotices` feature to the audio track so custom messages can be displayed when any given feature isn't active. It's a bit of an extra abstraction but felt cleaner and simpler than writing some specific hack for this functionality.
When the waveform is disabled, it is no longer focusable, so when users tab from the play button they are sent straight to the next play button. This means they are not explicitly informed about the disabled seek bar, but they're also not incorrectly able to focus the waveform or anything worse like that. I'm not sure how to best approach the _ideal_ solution to this.
I couldn't get our UA detection to run server-only, which I would have liked. Perhaps this could be refactored in the future to add the parsed UA information …
> Notices for Jamendo tracks when seeking is impossible

- src/components/VAllResultsGrid/VAudioCell.vue
- src/components/VAudioTrack/VAudioTrack.vue
- src/components/VAudioTrack/VGlobalAudioTrack.vue
- src/components/VAudioTrack/VPlayPause.vue
- src/components/VAudioTrack/layouts/VBoxLayout.vue
- src/components/VIconButton/VIconButton.vue
Fixes #662 by @zackkrida 
- Spacebar or play button click to play/pause on boxed audio
- Click or enter to visit single result
We probably still need to announce to screen reader users that space will play/pause and click will visit the single result. There may be a way to do what I'm doing _and_ wrap in a NuxtLink for improved usability.
<details>
```
Version 1.1
Suite D4700 …
```
> All results audio tabbing, single result link, and play/pause fixes

- src/components/VItemGroup/VItem.vue
- src/components/VSearchGrid.vue
Fixes #670 by @zackkrida
This PR removes the check for `noresult` in the search results page to always show the search term as a page title. This prevents layout shifts.
It also removes unused functions, and uses constants to check for content type supported status, and removes a stray log.
Run the app and search for something that doesn't exist :) See that layout doesn't shift, although the skeletons and the meta search form appear and then disappear (this should be addressed in a separate PR).
<details>
```
Version 1.1
1 Letterman …
```
> Always show search title, even when search has no results

- src/components/VContentSwitcher/VContentTypes.vue
- src/components/VContentSwitcher/VMobileMenuModal.vue
- src/components/VModal/VMobileModalContent.vue
- src/components/VModal/VModal.vue
- src/components/VModal/VModalContent.vue
- src/components/VModal/meta/VModal.stories.js
- src/composables/use-dialog-content.js
- src/composables/use-focus-on-show.js
- test/unit/specs/components/v-modal.spec.js
Fixes #641 by @sarayourfriend
In order to fix the issue where opening the mobile content type switcher was focusing the wrong element, we needed to update the modal to allow for this behavior to specify the element we want to focus when the content is shown.
Even though we only needed this for the mobile menu content modal, I went ahead and implemented it in the default modal component and added a story control to demonstrate it working in the story.
Checkout the branch and run `pnpm dev`. Visit the search page with a narrow width viewport and open the content type switcher using the keyboard. It should focus the active content type button. Be sure to try different content types being selected. It should always focus the active one.
For good measure, run `pnpm storybook` and visit the …
> Allow focusing specific element when opening modal

- src/components/VAllResultsGrid/VAllResultsGrid.vue
- src/components/VAudioTrack/layouts/VFullLayout.vue
- src/components/VContentLink/VContentLink.vue
- src/styles/tailwind.css
This small change will save us from copying the styles for links several times in every place where one appears (I was doing this in the single result page for images). The default color is pink and they should have an underline on hover state.
Run the project, everything should look the same. Writing a new link should have the default styles without requiring to do anything else.
<details>
```
Version 1.1
Suite D4700 …
```
> Style links globally

- src/components/ImageDetails/VPhotoDetails.vue
- src/components/VHeader/VPageMenu/VDesktopPageMenu.vue
- src/components/VPopover/VPopover.vue
- src/components/VPopover/meta/VPopover.stories.js
Fixes #725 by @sarayourfriend 
This PR exposes `close` as a slot prop to VPopover content. The default slot can access the `close` function by tapping into the `controls` slot prop.
0. Check out the branch and run the Storybook.
1. Play with the "Control" story under "Components/VPopover".
<details>
```
Version 1.1
Suite D4700
By making …
```
> Expose `close` to popover content via slot props

- src/components/VFilters/VSearchGridFilter.vue
Fixes #729 by @panchovm 
This PR adds a border to the left (in LTR, and right in RTL) side of the filter sidebar on desktop screen. To be honest,  with my settings for scrollbar visibility, it is not easy to see:
Run the app, and open the filters sidebar. You should see a border between the sidebar and the main content. 
<details>
```
Version 1.1
Suite D4700
Developer's …
```
> Add inline-start border to filters on desktop

- src/components/VContentSwitcher/VContentTypeButton.vue
- src/pages/index.vue
Fixes #709 by @obulat
This PR adds the content type switcher buttons to the homepage that are used on mobile screen. They are hidden on larger screen using tailwind utilities.
@panchovm , I don't know what the `hover` styles should be for the buttons.
Run the app, open the homepage on a narrow screen, and try changing the content types, and searching for different content types.
<details>
```
Version 1.1
Suite D4700
license …
```
> Add homepage content switcher for mobile screens

- src/locales/en.json
- src/locales/po-files/openverse.pot
- src/locales/scripts/get-translations.js
- src/locales/scripts/jed1x-json-to-json.js
- src/locales/scripts/json-pot-helpers.js
Fixes #702 by @obulat
This PR uses  a more modern JSON format for downloading the translations from `translate.wordpress.org`, `jed1x`. This enables pluralization (the NGX format did not have any information about pluralization).
Run `pnpm run i18n:get-translations` to update the translations for all locales. You should see that the keys that need to be pluralized (eg. `waveform.current-time`, `browse-page.all-result-count-more`), have several values joined with a pipe if translations for that locale has been done.
<details>
```
Version 1.1 …
```
> Use jed1x json format to correctly handle pluralization

- nuxt.config.js
Fixes #754 by @sarayourfriend 
Enables source maps in production so that Sentry can use them for better stack traces in issues.
Does not effect the dev experience at all as they were already enabled in development, this PR just removes the "isDev" check that was guarding source map generation.
This will slightly slow down the production build but IMO that's the least concern (I'm more concerned that we're using production quality source maps in development and we could get a dev performance win if we switched to a different source map generation technique in dev, but that's another story altogether and our dev build is still pretty fast anyway).
Run `pnpm build && pnpm start` and verify that you can access the source maps in your browser.
- [N/A] I added or updated tests for the changes I …
> Enable source maps in production

- src/components/VAudioTrack/layouts/VRowLayout.vue
- src/components/VGlobalAudioSection/VGlobalAudioSection.vue
Fixes #779 by @sarayourfriend 
Switches from using `end-0`, which doesn't seem to work correctly, to explicitly using `rtl:left-0 ltr:right-0`. 
I think the `end-0` css logic looks for _any_ parent element that doesn't have a `dir` applied, so both of these styles are applied at once and specificity wins:
```css
:not([dir="rtl"]) .end-0 {
right: 0;
}
[dir="rtl"] .end-0 {
left: 0;
}
```
<details>
```
Version 1.1
Suite D4700 …
```
> Fix global audio rtl close placement

- src/components/VFourOhFour.vue
- src/layouts/error.vue
- src/pages/audio/index.vue
- src/pages/image/index.vue
Fixes #496 by @obulat 
Adds an `index.vue` to the `image` and `audio` page directories so that we can render a 404 page when a single result route without an id is hit.
I'm not sure if this is really the _right_ way to do this... I couldn't find any solid evidence about this and redirecting to `/404` seems incorrect for some reason. If we prefer that though, we can do that instead of this. I do like that this is a little more on the "declarative" side of things rather than programatically testing the route.
Checkout the branch and run `pnpm dev`. Visit `/image/` without an id and `/audio/` without an id and verify that they show the 404 page.
<details> …
> Make audio/image pages without ids show a 404

- src/components/VFourOhFour.vue
- src/components/VHeader/VLogoButton.vue
Fixes #786 by @zackkrida 
Fixes #815 by @krysal 
This PR:
- sets a default value for `is-search-route` property in the `VLogoButton` instead of requiring it every time and 
- sets the `size` of the `VSearchBar` in the error layout (404 page), fixing its style.
Follow steps in the linked issue, the warning errors should be gone.
- [-] I added or updated tests for the changes I made (if applicable).
<details>
```
Version 1.1
Suite D4700 …
```
> Complete missing props

- src/composables/use-get-locale-formatted-number.js
- src/composables/use-i18n-utilities.js
- src/pages/sources.vue
- test/unit/specs/composables/use-get-locale-formatted-number.spec.js
- test/unit/specs/composables/use-i18n-utilities.spec.js
- tsconfig.json
- typings/nuxt__types/index.d.ts
Fixes #535 by @sarayourfriend
The issue actually was out-dated, but the solution being used on the search result page differed from the solution used on other parts of the app (namely the sources page).
This PR unifies both approaches and fixes some minor bugs in how the locale was being used for the search results page, and also uses the `en-gb` locale for locales that would have used Eastern arabic numerals.
This also matches the approach taken in Gutenberg for formatting input numbers.
I also managed to get VueI18n into the Nuxt context type so that `useContext`'s return actually includes it, meaning we can add more composables to type checking.
Visit the search page using a locale that uses eastern arabic numerals by default, like `ar` and verify that it is using western arabic …
> Unify number localization strategy across the app.

- src/components/VAllResultsGrid/VAudioCell.vue
- src/components/VAudioTrack/VAudioTrack.vue
- src/components/VAudioTrack/layouts/VBoxLayout.vue
Fixes #721 by @obulat 
This PR makes the default size for the boxed layout `null` instead of `'m'` (preserved for all other layouts if not explicitly specified) with a computed property, this way we avoid the warning for an invalid prop and it still looks good in the All search results grid, as no fixed `width` is applied.
Follow instructions on the related issue and observe no more warnings are shown, maintaining the normal aspect of the all search results grid.
- [-] I added or updated tests for the changes I made (if applicable).
<details>
``` …
```
> Set default size of VAudioTrack with a computed property

- src/components/VCheckbox/VCheckbox.vue
- src/components/VRadio/VRadio.vue
- tailwind.config.js
This PR updates the usages of the color primary to reference pink as it was planned to be done after the redesign launch.
0. Check out the PR and run the Storybook & dev server.
1. Search for the usages of color 'primary'.
2. The usages should all be pink.
<details>
```
Version 1.1
Suite D4700 …
```
> Update color 'primary' to 'pink' after redesign

- src/components/FooterSection.vue
- src/components/VContentSwitcher/meta/VContentSwitcherPopover.stories.mdx
- src/pages/search/audio.vue
In the interest of consistency this PR replaces the few instances of `@` imports with `~`. Vue CLI apps generally tend to use `@` as the alias for the `src` dir, but Nuxt seems to [support both equally](https://nuxtjs.org/docs/configuration-glossary/configuration-alias/) so there's really no reason to favour one over the other. Since `~` is more commonly used in the code, using that as the standard causes minimum disruption.
0. Check out the PR and run the dev server.
1. It should start.
<details>
```
Version 1.1 …
```
> Replace `@` imports with `~` imports

- src/components/VHeader/VHeader.vue
Fixes #726  by @sarayourfriend 
Changing `searchStatus` to a computed property seems to solve the stuck text of the search bar.
Try searching different terms, change between media types (image, audio, all content) and observe if the search bar status changes correctly.
<details>
```
Version 1.1
Suite D4700 …
```
> Unstuck `searchStatus` of search bar

- src/store/search.js
- src/utils/search-query-transform.js
This PR fixes the mixup between the `mediaFilterKeys` and `mediaSpecificFilters` objects in the `search` store.
The first is used to keep all the filter types that are used for the content type, and the second has a list of filters that are only used for the specific content type, and not used in other content types (such as `duration` for audio).
One of the places where the `mediaSpecificFilters` was used was the `search/CLEAR_OTHER_MEDIA_TYPE_FILTERS`. This action is dispatched when changing a content type to clear filters that do not apply to current content type. So, when changing from "All Content" to "Images", it would set all the filters that are specific for "All Content" and "Audio" to not checked. With the bug that is fixed here, it would also uncheck the following filters: …
> Use the correct list of filters for All content

- src/components/VContentSwitcher/VContentSwitcherButton.vue
- src/components/VHeader/VHeader.vue
- src/components/VHeader/VLogoButton.vue
- src/constants/screens.js
- src/layouts/default.vue
- src/styles/base/generic.sass
Fixes #825 
This PR makes some cleanup to the main layout logic of every page:
- Ensures the header and main content area are the first two child elements of our primary grid container, by grouping the locale banner, cc banner, and header into a div. 
- Only applies our grid layout above the medium breakpoint
- Removes a hardcoded `min-width: 300px` from the `html` element
- Uses viewport width units to fix some flexbox behavior in the header, where using `100%` width allowed the header to grow beyond the device width.
- Hides header logo text and content switcher label on _extremely_ small screens via a new `xs` breakpoint. Time to make Openverse work on smart watches 😄 
- **Unrelated bugfix**: Localizes the header logo link properly 
In addition to fixing the layout bugs, this should …
> Fix global layout issues

- src/components/VPopover/VPopoverContent.vue
Fixes popover wonkiness on iOS outlined here: https://github.com/WordPress/openverse-frontend/pull/850#pullrequestreview-879636906
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the open …
```
> Fix inline popover content taking up space

- src/components/VAudioTrack/VAudioTrack.vue
- src/components/VAudioTrack/VGlobalAudioTrack.vue
When an audio file is played and the duration from the passed properties
does not match the duration of the actual audio file, e.g. the duration
was rounded, the progress bar drifts outside of the total width of the
VWaveform dimensions.
On smaller width screens or larger tracks it is less noticeable but when
the audio track is small and the screen width is large that percentage
adds up to 10s or more of pixels which is where the bug crops up.
This commit fixes this issue by by using the audio context's duration
parameter and falling back to less specific sources for duration.
Fixes #692 by @sarayourfriend 
<details>
```
Developer …
```
> (#692) Fix duration mismatch between audio and metadata

- .eslintrc.js
Related to #871 
This PR adds a custom vue eslint rule disallowing usage of raw `<a>` tags and encouraging the use of `<VLink>` instead.
Try adding this code `<a href="cool">cool</a>` to any Vue component in a text editor where you receive eslint messages and observe the correct eslint error:
Suggestions are welcome regarding the error message or lint rule implementation. I didn't dive into the vue-eslint AST[^1] too deeply so there may be a more specific rule we'd like to use.
<details>
```
Version 1.1
Suite D4700 …
```
> Disallow all link components except `<VLink>` with eslint rule

- src/components/VMigrationNotice.vue
- src/layouts/default.vue
- src/middleware/middleware.js
- test/e2e/migration-banner.spec.js
Fixes #515 by @sarayourfriend
This PR enables the migration banner to render via SSR.
Nuxt middleware runs once on the server during the first render and subsequent times on the client during routing. On the server, the plugin `migration-notice.js` sets the Vuex state `isReferredByCc` to true, and the middleware immediately sets it to false. So the banner isn't part of the SSR page.
On the client the plugin again sets the Vuex state `isReferredByCc` to true. The middleware already having executed on the server is not run on the client for the first page, so the banner pops in. Further navigation causes the middleware to run and remove the banner (as expected).
By changing the middleware to not run the unset mutation on the server, we are able to ensure that it only has the intended banner …
> Enable SSR for migration banner

- .babelrc
- .eslintrc.js
- .pnpmfile.cjs
- jest.config.js
- nuxt.config.js
- package.json
- pnpm-lock.yaml
- src/components/VAudioTrack/VWaveform.vue
- src/components/VLogoLoader/meta/VLogoLoader.stories.js
- src/constants/media.js
- src/store/types.ts
- src/utils/deep-freeze.ts
- src/utils/warn.js
- test/unit/specs/components/search-grid-filter.spec.js
- test/unit/specs/components/v-popover.spec.js
- test/unit/test-utils/svg-transform.js
- tsconfig.json
- typings/openverse/index.d.ts
- typings/vue/index.d.ts
Fixes #921 by @sarayourfriend
Adds support for native TypeScript by adding the following dependencies:
* `@nuxt/typescript-build` -> This adds TypeScript to our build pipeline
* `@typescript-eslint/*` -> These packages enable TypeScript parsing and recommended rules for ESLint
* `@babel/preset-typescript` -> This adds TypeScript to the babel configuration we use for running `jest`
Additionally, I've had to add a `.pnpmfile.cjs` ([documentation for that here](https://pnpm.io/pnpmfile)) in order to force resolve `typescript` to a modern version. We need this because `@nuxt/typescript-build` uses an older version of TypeScript that doesn't support some of the TS features we were already using (like casting to `const` with JSDoc and type parameter defaults in JSDoc).
Finally, I've converted …
> Add support for native TypeScript

- src/store/types.ts
Fixes #996 by @obulat
Adds optional peaks key to AudioDetail interface which will be soon used for the waveform. Type set to 'any'.
No testing written.
<details>
```
Version 1.1
Suite D4700
have the right to submit …
```
> Add optional peaks key to AudioDetail interface

- .eslintrc.js
- package.json
This PR
- fixes a typo in `.eslintrc.js`
- deduplicates the `lintfix` script to use the `lint` script
<details>
```
Version 1.1
Suite D4700
indicated in the …
```
> Minor improvements to `.eslintrc.js` and `package.json`

- src/components/VScrollButton.vue
Fixes #1032 by @zackkrida
Changed the scroll to the top button component color from blue to pink 
<details>
```
Version 1.1
Suite D4700
indicated in the file; …
```
> changed the scroll to top button color B->P 

- src/components/VAudioTrack/VAudioTrack.vue
Fixes #1048 by @zackkrida 
Adds the `group` class to the AudioTrack, so when it is focused it shows the cc license icons in the same way the VImageCellSquare does.
- Navigate by keyboard to an audio result in the all results view, observe the visible CC license icons
- Test other audio tracks in the UI and make sure this hasn't introduced any odd behavior 
<details>
```
Version 1.1
Suite D4700
license document, but changing …
```
> Add group class to audio track

- src/components/VAllResultsGrid/VImageCellSquare.vue
- src/components/VImageGrid/VImageCell.vue
Related to #1034 by @zackkrida 
Adds width and height properties to images, as well as setting the background to grey while they are loading. We _could_ and maybe _should_ wait to display images until they are loaded, and show the skeleton components while they are loading, but this still makes an improvement to the current loading appearance via the grey backgrounds. 
Observe the appearance of the all results grid and image results views while loading.
> before
> after (loading appearance while on a throttled 4g connection)
<details>
```
Version 1.1 …
```
> Add width and height properties to images

- src/components/VSearchGrid.vue
Fixes console warnings :)
`VMetaSearchForm` expects a prop called `has-no-results`, but parent passes a prop without the `s`: `has-no-result`. This causes error and warning in the console. 
`VSearchResultsTitle` component import is also added.
Run the app and see that there are no more warnings in the console when you open a search page.
<details>
```
Version 1.1
Suite D4700 …
```
> Fix prop name mismatch

- src/components/VMediaInfo/VMediaReuse.vue
Fixes #1091 by @zackkrida 
Switches the media reuse columns to use flexbox for layout. Observe an image and/or audio single result on desktop and mobile; confirm the correct appearance.
<details>
```
Version 1.1
Suite D4700 …
```
> Switch to css grid instead of legacy column classes in media reuse

- src/components/VAudioTrack/VWaveform.vue
- src/locales/po-files/openverse.pot
- test/unit/specs/components/AudioTrack/waveform.spec.js
Fixes #1074 by @sarayourfriend 
This PR updates the `peaks` prop to use the default value even when given a truthy value of `[]`. This prevents the peaks from showing up as blank.
0. Check out the PR and run the Storybook.
1. Visit a Waveform story and change the control for peaks to a blank array.
2. See the waveform become random.
<details>
```
Version 1.1
Suite D4700 …
```
> Handle waveform with `peaks` prop as a blank array

- package.json
- pnpm-lock.yaml
- src/components/VContentReport/VContentReportForm.vue
- src/data/report-service.js
- src/pages/image/_id.vue
- test/unit/specs/components/v-content-report-form.spec.js
Fixes #1079 by @zackkrida 
Related to #1086 by @krysal 
This PR:
- fixes the mature content report submission by passing the id correctly and removing the extra `/` when building URL in the data service
- update Axios to the last version
- (no related to mentioned issues) adds a catch method to silence an annoying console error in Firefox when navigating by related images (in development mode). If you know a better way to handle this, please share it.
Try to report any image, you should see the success message and the request must have been sent.
<details>
```
Developer …
```
> Fix mature content report submission

- src/components/VContentReport/VContentReportForm.vue
- src/components/VLicenseElements.vue
- src/components/VMediaInfo/VCopyLicense.vue
- src/components/VMediaInfo/VMediaLicense.vue
- src/locales/en.json
- src/locales/po-files/openverse.pot
Fixes #1111 by @krysal
This PR fixes the font size of the license description and breaks words in the attribution HTML tab to avoid causing horizontal scrolling when the page is on small screens.
Follow steps on issues and compare with Figma mockups.
- [-] I added or updated tests for the changes I made (if applicable).
<details>
```
Version 1.1
Suite D4700
license …
```
> Tweaks to the Image Details page

- .eslintrc.js
- src/components/VAudioTrack/VAudioTrack.vue
- src/components/VAudioTrack/VGlobalAudioTrack.vue
- src/composables/default-ref.ts
- test/unit/specs/composables/default-ref.spec.ts
Fixes #1076 by @sarayourfriend 
`defaultRef` is just a computed that uses some default computed value until another value is explicitly set.
This allows us to get rid of the confusing `duration` and `audioDuration` ref duplication that was happening in the audio track components by hiding what was the effective "default" in the original computed.
It also fixes the `null / 0` error.
Check the unit tests to make sure I didn't miss any edge case.
Test the audio track, global, search results, related audio, and single result tracks, specifically from Jamendo to make sure there isn't a regression on #692.
<details>
```
Developer …
```
> Fix audio track null duration and add defaultRef

- src/components/VAudioTrack/VWaveform.vue
- src/locales/po-files/openverse.pot
Related to [`openverse-api` issue#575](https://github.com/WordPress/openverse-api/issues/575).
The front end expects all audio peaks values to be non-negative integers in the range of [0..1]. However, [some of the peaks values](https://api.openverse.engineering/v1/audio/727b9979-98f1-4604-9097-0a8b6fa68f2e/) that API sends are negative.
This PR adjust the validator for peak values, and makes all the values at least zero.
To minimize the effect of this fix on performance, I added the `Math.max(0, value)` to the already existing `map` function that handles the peaks object.
On the main branch, go to `http://localhost:8443/audio/727b9979-98f1-4604-9097-0a8b6fa68f2e/`. You should see a warning in the console saying "Invalid prop: custom validator check failed for prop "peaks".
When opening …
> Hotfix for negative values in peaks

- .eslintrc.js
- src/components/VCopyButton.vue
- src/components/VMediaInfo/VCopyLicense.vue
- src/locales/en.json
- src/locales/po-files/openverse.pot
- test/unit/specs/components/v-copy-button.spec.js
Related to #1087 by @zackkrida
This PR moves the CopyButton styles from `<style>` block to tailwind (class definitions), and renames the component to add `V` prefix.
> CopyButton style and name change; remove unused locale strings 

- package.json
- pnpm-lock.yaml
Fixes #1086 by @krysal 
updates dev dependencies 
```
"@intlify/eslint-plugin-vue-i18n": "^1.4.0",
"lint-staged": "^12.3.7",
"vue-tsc": "^0.33.9"
```
<details>
```
Version 1.1
Suite D4700 …
```
> Update @intlify/eslint-plugin-vue-i18n, vue-tsc & lint-staged

- src/components/VItemGroup/VItem.vue
Following up #1191 that left out the items in the pages menu, as @obulat noticed.
This PR makes the `VItem` component use always the variant `plain` of the `VButton` to keep focus-visible styles. I don't know in which cases the "plain-dangerous" version would be used, please point it out or describe it if you find it. 
Navigate the pages menu in a version of Safari < `15.4` with the keyboard, you should see the focus ring in each page entry.
<details>
```
Version 1.1
Suite D4700
Everyone is …
```
> Fix focus style of buttons in page menu

- src/components/VAllResultsGrid/VAudioCell.vue
- src/components/VAudioTrack/VAudioTrack.vue
- src/components/VAudioTrack/VPlayPause.vue
- src/components/VAudioTrack/layouts/VBoxLayout.vue
- src/components/VWarningSuppressor.vue
- src/constants/key-codes.ts
- src/locales/en.json
- src/locales/po-files/openverse.pot
- test/playwright/e2e/all-results-keyboard.spec.ts
- tsconfig.json
Fixes #1242   by @sarayourfriend 
Makes the boxed audio result a VLink wrapped element so that when focused, it is keyboard accessibly openable and also reports the actual URL of the page that will be opened, unlike the existing solution which mimicked link behavior using JavaScript.
We will later continue to work on the audio result link by transforming it into a composite element (probably `role="grid"`) that has custom keyboard navigation to enter the link to be able to play and pause the audio.
Check the new e2e tests pass. Also test it in your own browser and in particular check the focus styles.
I could add visual regression tests for the focus styles actually, I will do that tomorrow! …
> Fix audio results not being keyboard accessible in all results view

- src/components/VMetaSearch/VMetaSearchForm.vue
Related to the legacy styles milestone, this PR removes some small instances (the only ones I'm aware of) of classes used from the global sass stylesheets.
> Remove usage of legacy classes

- src/stores/search.ts
- src/utils/search-query-transform.ts
- test/playwright/e2e/search-query-client.spec.ts
- test/tapes/search_images_q=cat&categories=photograph_close.json5
- test/unit/specs/utils/search-query-transform.spec.js
Fixes #1169 by @krysal
This PR replaces plural API parameter `categories` with singular `category`, and updates some documentation.
This probably shouldn't be merged until the API fix is deployed because it will break the image category filtering.
If you run this as is, filtering by category will return un-filtered result because the production API discards filters that don't exist. If you run it with API from https://github.com/WordPress/openverse-api/pull/583 running locally, you should get filtered results for audio and images.
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux …
```
> Use singular `category` API param

- Dockerfile
Fixes staging not deploying due to a Node 18 issue (and also just generally puts us in line with the `engines` and builder image versions.
Run the docker-compose stack locally and verify it works. Alternatively deploy this and confirm that staging deploys successfully.
<details>
```
Version 1.1
Suite D4700 …
```
> Pin node version for final production image

- src/components/VFilters/VSearchGridFilter.vue
- src/components/VHeader/VFilterButton.vue
- src/locales/po-files/openverse.pot
- test/playwright/e2e/filters.spec.ts
- test/playwright/utils/navigation.ts
Addresses the point in a [comment](https://github.com/WordPress/openverse-frontend/pull/1275#pullrequestreview-951750164) to #1275
This PR sets updates `VSearchGridFilter` to add the id of `filters`, and adds `aria-controls = "filters"` attribute to `VFilterButton`.
Unfortunately, `aria-controls` isn't implemented by most of the screen-readers, so we will **have** to add our own solution to shift focus to the sidebar after `VFilterButton` is clicked. This PR also implements one piece of advice from an article about `aria-controls`: https://heydonworks.com/article/aria-controls-is-poop/: it makes `VSearchGridFilter` a `section`, so adds a landmark role to it. These other two pieces will have to be implemented separately
-  Same-page links to move users from one part of the interface to …
> Add some a11y properties to VSearchGridFilter

- package.json
- pnpm-lock.yaml
- src/locales/scripts/jed1x-json-to-json.js
- src/locales/scripts/ngx-json-to-json.js
- src/locales/scripts/utils.js
Fixes #1107 by @sarayourfriend 
Replaces `lodash.set` with a smaller implementation from SO. This should prevent accidentally using it in the actual app.
Checkout this branch and delete your local translation .json files other than `en.json`. Copy one of them first to compare to the output. Then run `pnpm i18n`. The output of the file you copied should match the newly generated one.
<details>
```
Version 1.1
Suite D4700 …
```
> Remove lodash.set

- test/playwright/e2e/search-navigation.spec.ts
- test/playwright/e2e/search.spec.ts
Related to #1350
Added tests in the `search-navigation.spec.ts` file. I also moved some test from the `search.spec.ts.` file to grouped them under the "back to search results link" description, and removed a skiped test.
Try these changes in **main** and observe tests fail, then here with @obulat fixes, they should pass.
<details>
```
Version 1.1
Suite D4700 …
```
> Add e2e test for localized back to search link

- src/components/VHeader/VSearchBar/VSearchBar.vue
- src/components/VInputField/VInputField.vue
- src/components/VNotificationBanner.vue
- src/types/emits.ts
The idea struck me earlier to go digging around the `defineComponent` types around the `emits` option and I remembered that there was a way to define emit payload types, just that it was cumbersome to do so because it required writing a validator function.
I wrote about this in the [WordPress Make slack](https://wordpress.slack.com/archives/C02012JB00N/p1650955199262509) (requires [a free account](https://make.wordpress.org/chat/) to view).
Hopefully the documentation on the `defineEvent` function is clear enough to explain the rationale and theory behind the function.
The code changes outside of that function are basically noops, `null` emit values are the same as just using the string array approach, so this shouldn't change the runtime behavior of the components, just the types. …
> Add defineEvent emit type helper

- src/components/VContentSwitcher/VMobileMenuModal.vue
- src/components/VHeader/VHeaderFilter.vue
- src/components/VModal/VModalContent.vue
- src/composables/use-dialog-content.js
- test/playwright/e2e/mobile-menu.spec.ts
- test/playwright/utils/navigation.ts
Fixes #1308 by @stacimc
This PR sets the `useHideOutside` to false for mobile modals. This fixes the bug, but it doesn't fix the underlying problem. That, hopefully, will be fixed in PR that Typescriptifies the dialog composables: https://github.com/WordPress/openverse-frontend/pull/1279
Open the app on mobile width, and try clicking Filter/ Page menu buttons in the header several times. The menus should open and close successfully. On main [search-staging.openverse.engineering/search](https://search-staging.openverse.engineering/search/?q=cat), you can only open them once.
<details>
```
Version 1.1 …
```
> Fix mobile menu modals not opening for the second time

- src/locales/en.json
- src/locales/po-files/openverse.pot
- src/utils/attribution-html.ts
- test/unit/specs/utils/attribution-html.spec.ts
This PR handles cases where a media item either has no name or a blank one. It uses "This work" (or it's equivalent translation) if the media name is not known.
See added test case.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part by me …
```
> Handle attribution when title is blank

- .github/workflows/push_production.yaml
Adds the ability to rollback the `stable` image tag to a specific commit.
Note: the action should always be run from the `main` branch, this just changes the ref that is used to checkout the code that the docker build is run on.
Not sure how to test this without merging it and then seeing how it goes.
<details>
```
Version 1.1
Suite D4700
San Francisco, …
```
> Allow running prod ECS deployment action from ref

- .github/actions/build/action.yml
This PR fixes staging deploys by removing a duplicated `shell` property on the pnpm version step.
> Fix duplicated shell property in the staging build config; fix staging deploys

- src/components/VFilters/VFilterChecklist.vue
- src/components/VPopover/VPopover.vue
- src/components/VPopover/VPopoverContent.types.js
- src/composables/use-popper.js
- src/locales/po-files/openverse.pot
Fixes #1413 by @zackkrida 
Makes the popper.js property 'positioning strategy' configurable; sets this property to 'fixed' for the elements in the filter sidebar.
- Inspect the styles for the license explanation popover and look for `position: fixed` in the inline CSS. 
- Inspect the styles for the single result reporting form popover and look for `position: absolute` in the inline CSS. 
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim copies of …
```
> Make the popover positioning strategy configurable

- src/components/VAllResultsGrid/VAllResultsGrid.vue
- src/components/VAudioThumbnail/VAudioThumbnail.vue
- src/components/VAudioTrack/layouts/VBoxLayout.vue
- src/components/VAudioTrack/layouts/VRowLayout.vue
- src/components/VContentSwitcher/VSearchTypeButton.vue
- src/components/VErrorSection/VErrorImage.vue
- src/components/VHeader/VFilterButton.vue
- src/components/VHeader/VHeader.vue
- src/components/VImageDetails/VImageDetails.vue
- src/components/VLicense/VLicense.vue
- src/components/VLoadMore.vue
- src/components/VMediaInfo/VCopyLicense.vue
- src/components/VMediaInfo/VMediaReuse.vue
- src/components/VSketchFabViewer.vue
- src/composables/use-get-locale-formatted-number.ts
- src/composables/use-i18n-utilities.js
- src/locales/po-files/openverse.pot
- src/pages/search/audio.vue
Fixes #645 by @dhruvkb
This PR uses the `useI18n` composable to get the app i18n in the components setup functions instead of getting it from `useContext`. This will simplify conversion to Nuxt 3.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or …
```
> Use i18n from useI18n composable instead of Nuxt context

- .github/workflows/ci.yml
- src/pages/index.vue
- src/pages/search.vue
- src/stores/search.ts
Fixes #1225 by @obulat
The actual fix is in the `src/pages/index.vue` file but I also refactored the search page to use the correct Nuxt hook for async data (SSR), and remove a duplicated computed property with the Vue Options API.
Follow the steps in the issue and observe no more double fetching for audio and images in the browser console.
<details>
```
Version 1.1
Suite D4700 …
```
> Stop fetching the media twice in the search page

- .github/workflows/ci.yml
This PR should fix the pipeline in `main` by doing the following:
- Skip jobs trying to comment instructions on the `main` branch
- Removes checking steps from the `playwright-test-failure-comment` job as they were interfering when we really want it to run
- Add dependency on `build` in the `nuxt-playwright` job, tests would fail if nuxt can't be built anyway
<details>
```
Version 1.1
Suite D4700 …
```
> Workflow improvements to fix CI pipline

- .github/workflows/ci.yml
Skip the preview step on main as the final Storybook and Tailwind pages are generated by [**GitHub Pages** workflow](https://github.com/WordPress/openverse-frontend/blob/main/.github/workflows/gh-pages.yaml) and it's causing the CI pipeline to fail on main.
<details>
```
Version 1.1
Suite D4700 …
```
> Skip previews of Storybook and Tailwind in `main` branch

- src/composables/use-match-routes.ts
- src/locales/po-files/openverse.pot
- src/pages/audio/_id.vue
- src/pages/image/_id.vue
- typings/vue-router/index.d.ts
Simplify setting `backToSearchPath` in `beforeRouteEnter` in single media page and improve typing
Related to Typescriptification milestone
This PR uses `vue-router` `meta` parameter to pass the _Back to search path_ to the media detail page instead of adding it to the `next` component's `vm`. This makes typing the parameter easier, and the code cleaner. Now we don't need to use `this` parameter and can remove `data` from media detail page.
Search for something and open single result pages from the "All content", "Images" and "Audio" views. The "Back to search" path at the top should correctly return the user to the previous page.
<details> …
> Use the `route.meta` parameter to pass the path to search page

- .github/workflows/ghcr.yml
In #1449 I added a ternary, but GH Workflow syntax doesn't support them :facepalm: This replaces the ternary with the equivalent `&&` `||` construct.
<details>
```
Version 1.1
Suite D4700
license document, …
```
> Remove ternary from ghcr.yml

- src/components/VContentSwitcher/VSearchTypeButton.vue
- src/components/VContentSwitcher/VSearchTypePopover.vue
- src/components/VContentSwitcher/VSearchTypes.vue
- src/components/VErrorSection/VNoResults.vue
- src/components/VSearchGrid.vue
- src/composables/use-search-type.js
- src/stores/media/index.ts
- src/stores/search.ts
- src/utils/search-query-transform.ts
Fixes #1428 by @AetherUnbound
This PR makes it possible to open a `/search/video` page without crashing the app (mostly for users that get redirected from CC Search). It doesn't add `Video` to the Content Switcher.
To make sure everything works, I had to make the types more flexible, and make some methods accept `SearchType` (i.e., All Content and all media types including `video` and `media_3d`) instead of `SupportedSearchType`.
This PR is probably a good precursor for #1410, which will add the ability to add more types to the Content Switcher, making it possible to open the `model-3d` and `video` pages through the UI and not only by using the URL with the type in path.
With this PR, you will not be able to open `model-3d` page because we still haven't added a page component …
> Stop opening `/search/video` from crashing the app

- src/components/VMediaInfo/VLicenseTabPanel.vue
On copy now copy just the text on the slot
Targeting a container will copy all the text inside, including the text for the button, to prevent this we should target just the text container.
search for an image, click the selected image and go to credit the creator, select the type of credit and click "copy text" button.
paste the text on any text editor.
Expected: 
the text is pasted without any extra line and without the button text.
<details>
```
Version 1.1
Suite D4700
Everyone is …
```
> Target slot container to copy just the text.

- src/components/VAudioTrack/VGlobalAudioTrack.vue
- src/components/VAudioTrack/VPlayPause.vue
- src/components/VAudioTrack/layouts/VGlobalLayout.vue
- src/components/VAudioTrack/layouts/VRowLayout.vue
- src/components/VButton.vue
- src/components/VGlobalAudioSection/VGlobalAudioSection.vue
- src/locales/po-files/openverse.pot
Fixes #1427 by @panchovm
Fixes #1373 by @obulat
This PR adds `connections` prop to `VButton` to enable setting non-rounded corners if the button is a part of a compound control and only needs rounded corners at start/end. So, for a row audio track, we can set `connections=end` and make the button non-rounded where it is connected to the waveform.
Other changes in this PR:
- Clean up some `GlobalAudioTrack` props/attrs that were not used before, or fell out of sync with the base `AudioTrack` component (e.g. `ariaLabel` wasn't computed).
- Set the `GlobalAudioTrack` `Close` button `z-index` to 20 to prevent the waveform from overlapping. This fixes #1373. It's a one-character change, so I added it in here instead of opening a separate PR. …
> Fix audio button rounding and global audio not closing

- .github/renovate.json
Renovate is creating a new dependency dashboard every time it runs. I'm not sure why because the code to find the dependency dashboard issue just compares against the title. I'm taking a shot in the dark to see whether maybe fixing the bot username and the casing of the WordPress organization fixes it (maybe it's also secretly checking these somehow and I'm not seeing it in the code?).
Merge and :crossed_fingers: 
<details> …
> Try fixing things that might confuse deps dashboard finding

- src/components/VAudioTrack/VAudioTrack.vue
- src/components/VAudioTrack/VGlobalAudioTrack.vue
- src/components/VAudioTrack/VWaveform.vue
- src/locales/po-files/openverse.pot
- test/unit/specs/components/AudioTrack/waveform.spec.js
Fixes #1494 by @obulat
This PR uses `prng` to _seed_ the random number generator that generates the peaks for the audio waveform. It uses the audio id hash as the prng seed.
The audio waveforms should work fine. It's a base PR that is necessary for adding visual regression testing PRs for audio.
<details>
```
Version 1.1
Suite D4700
By …
```
> Make random waveform peaks deterministic

- .github/renovate.json
https://docs.renovatebot.com/self-hosted-configuration/#prcommitsperrunlimit
Renovate opened tens of PRs all at once. We can prevent this so that it only opens 3 every run (15 minutes).
Merge and :joy: 
<details>
```
Version 1.1
Suite D4700 …
```
> Limit renovate to prevent eating up our GH actions

- src/components/VImageDetails/VRelatedImages.vue
- src/stores/media/related-media.ts
- src/stores/media/single-result.ts
Related to #1516 by @obulat
The [comment from @sarayourfriend](https://github.com/WordPress/openverse-frontend/issues/1516#issuecomment-1152141457) in #1516 made me realize how to improve the loading of the single result pages so that they fully loa on SSR, but also do not block on the related media fetch call when being rendered client-side:
Awaiting the related media request on the server makes sure that the server-rendered page has the related media.
**Not** awaiting the related media request on the client makes the other parts of the page load quickly, and we can render a loading icon while fetching the related media.
Try opening the single detail page for images directly, and from the search page. It should load the related items when opened directly, but on client-side, it should …
> Make fetching related images on the client non-blocking

- src/components/VAudioTrack/VAudioTrack.vue
- src/components/VAudioTrack/VGlobalAudioTrack.vue
- src/components/VAudioTrack/VPlayPause.vue
- src/components/VAudioTrack/layouts/VGlobalLayout.vue
- src/components/VIconButton/VIconButton.vue
- src/constants/audio.ts
- src/locales/en.json
- src/locales/po-files/openverse.pot
- tsconfig.json
Fixes #1001 by @sarayourfriend 
Adds a loading indication to the button when audio is being loaded.
https://user-images.githubusercontent.com/24264157/172460095-b69a35eb-18f6-4784-869e-64c45b65ed0b.mp4
Do what I do in the video above, click around the audio results page, single results, mobile results, etc and make sure that the loading indicator appears and disappears when it's meant to. Be sure to test edge cases like multiple audios loading at once. Only the "about to be played" audio should ever indicate loading status.
<details>
```
Version 1.1 …
```
> Add loading indication for audio

- .github/workflows/generate_pot.yml
Follow up to #1535 @sarayourfriend 
As @zackkrida pointed out in the original #1051 issue, the workflow is not working due to not being able to checkout the translations branch. I'm trying to fix that here.
Checkout the workflow runs and confirm that it works in this PR.
<details>
```
Version 1.1
Suite D4700 …
```
> Fix PO generation workflow

- .github/workflows/ci.yml
- bin/playwright.sh
- docker-compose.playwright.yml
- package.json
- src/utils/env.ts
- src/utils/sentry-config.ts
- test/playwright/e2e/filters.spec.ts
- test/playwright/e2e/report-media.spec.ts
- test/playwright/playwright.config.ts
- test/playwright/visual-regression/components/audio-results.spec.ts
- test/playwright/visual-regression/components/header.spec.ts
- test/playwright/visual-regression/components/media-reuse.spec.ts
- test/playwright/visual-regression/pages/homepage.spec.ts
- test/playwright/visual-regression/pages/pages.spec.ts
- test/playwright/visual-regression/pages/sources.spec.ts
- test/unit/specs/stores/provider.spec.js
Fixes #1491 by @sarayourfriend 
This PR:
- instruct playwright to run said tests in parallel workers
- fixes the condition for when updating tapes
- **sets the playwright service container to use the maximum number of CPUs available**[^1]. GitHub action runners only have 2-cores[^2], as Sara commented below, that is why it
- **sets the tests in CI to run with 2 workers** instead of one as it has been running so far
- turn down the docker container for testing after tests are finished, currently it keeps running 
- silence warnings in the `provider.spec.js` unit test
Run the following command for more workers (to me it defaults to only 2):
```sh
pnpm test:playwright visual-regression --workers=4
```
In the main branch you'd see these lines when it finishes:
```
playwright_1  |   Slow test …
```
> Parallelize snapshot tests

- .husky/pre-commit
Fixes #1598 by @obulat 
This PR adds a check for `src/locales/ar.json` existence. If it doesn't exist, pre-commit runs `pnpm i18n` to load translations.
Remove `src/locales/ar.json` if you have it. Create a new branch based on this PR's branch, add any change and run `git commit -m "Test commit"`. You should see a message that i18n scripts load locale files, and the commit should be successful.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim copies …
```
> Load locales in pre-commit if necessary

- src/composables/use-window-scroll.ts
- test/unit/.eslintrc.js
- test/unit/specs/composables/use-window-scroll.spec.ts
Part of a broader TS-ification project and necessary for TS-ifying the last blocking component: VPopover.
Updates `useWindowScroll` to use TypeScript and adds unit tests. Also removes the usage of deprecated window properties.
Ensure CI and e2e tests work as expected.
<details>
```
Version 1.1
Suite D4700
Developer's …
```
> Add TS to useWindowScroll

- src/components/VErrorSection/VNoResults.vue
Fixes #1588 by @panchovm
On component VNoResults.vue
- changed h5 to h4 below <div class="no-results text-center md:text-left">
- deleted text-3xL -  on <h6 class="mt-10 text-3xl font-normal md:mt-16 md:font-bold">
In live build
- search "fjkdls;a;"
- when you arrive at 'no results' page
- inspect page, view on 'mobile view' to see text size changes
<details>
```
Version 1.1
Suite D4700
license document, but changing it is …
```
>  Text styles in no results page are incorrect #1588 

- .github/renovate.json
- src/utils/sentry-config.ts
Fixes #1625 by @sarayourfriend 
Fixes #1650 by @krysal 
This PR:
- makes Renovate bot ignore forks
- removes Openverse' Sentry DNS and disable it if it is not set
For Sentry, try running the project with different environment variables configurations.
1. Simulating production and without setting the SENTRY_DSN, confirm it's disabled
```sh
NODE_ENV=production pnpm dev:only
```
In your terminal you should see an output like this:
```sh
✔ Sentry reporting is disabled ("disabled" option has been set)                                                       nuxt:sentry 16:13:45
╭─────────────────────────────────────────────╮
│                                             │
│   Nuxt @ v2.15.8                            │
│                                             │
│   ▸ Environment: development …
```
> Make Renovate bot ignore forks and remove the SENTR_DSN

- src/components/VAudioTrack/VPlayPause.vue
Reverts WordPress/openverse-frontend#1643
Reverting due to the introduction of an uncaught Playwright failure: https://github.com/WordPress/openverse-frontend/actions/runs/2869167598
Playwright failures were not being surfaced in PRs due to #1637
> Revert "Avoid pausing audio when is loading"

- src/components/VAudioTrack/VWaveform.vue
Fixes #1436 by @zackkrida
Changes text size based on screen size + Adds a padding to smaller displays to stop text from connecting to black play button.
Go to any audio search result list in Chrome and hover a Jamendo or Freesound result, on a small-ish > 1000px browser width
<details>
```
Version 1.1
Suite D4700
By making a contribution …
```
> Audio label fixed

- src/components/VAudioDetails/VAudioDetails.vue
- src/components/VAudioDetails/VRelatedAudio.vue
- src/components/VMediaInfo/VCopyLicense.vue
- src/components/VMediaInfo/VMediaLicense.vue
- src/components/VMediaInfo/VMediaReuse.vue
- test/playwright/visual-regression/components/media-reuse.spec.ts
- test/unit/specs/components/related-audios.spec.js
Fixes #1616 by @obulat 
- Pull Request changes the headers of the following components to be a in sequential order ( h1 - h3)
(h1) * src/components/VMediaInfo/VMediaReuse.vue
(h2) * src/components/VAudioDetails/VAudioDetails.vue
(h3)  * src/components/VAudioDetails/VRelatedAudio.vue
- Pull Request changes testing file 'related-audios.spec.js' to pass 'RelatedAudios' test. 'h4' has been changed to 'h3'. Test now passes. 
##Add screenshot
<details>
```
Version 1.1
Suite D4700
Everyone is …
```
>  Correct heading order for single audio result pages

- src/components/VImageDetails/VImageDetails.vue
- src/components/VImageDetails/VRelatedImages.vue
Fixes #1698 by @obulat
Pull Request changes the headers of the following components to be a in sequential order 
(h2) *VImageDetails.vue
(h2) * VRelatdImages.vue
<details>
```
Version 1.1
Suite D4700
have the right …
```
> Correct heading order for single IMAGE result page

- src/components/VMetaSearch/VMetaSearchForm.vue
Changed from h tag to p tag, and also changed the text styling.
Fixes #1615 by @obulat 
The search results message did not match the figma at all. Addresses issue with ticket #1615, where the search results message is styled as a header and not as a paragraph. Changed from h tag to p tag, and also changed the text styling.
<details>
```
Version 1.1
Suite D4700
Developer's …
```
> Replace Search result page `h` element with a `p` element

- .github/workflows/actionlint.yml
- .github/workflows/bundle_size.yml
- .github/workflows/generate_pot.yml
- .github/workflows/gh-pages.yaml
- .github/workflows/ghcr.yml
- .github/workflows/label_new_pr.yml
- .github/workflows/rollback.yml
Related to https://github.com/WordPress/openverse/issues/290 by @sarayourfriend 
Workflows by default run in parallel and will finish running even if the
results of them don't matter by the time they're done. CI for example,
does not matter on a PR if the PR is updated. That's why we already had
concurrency on the ci.yml workflow that cancels in progress workflow
runs. This helps prevent our worker allowance from being eaten up by
long CI runs.
We can also use this to prevent certain workflows from running in
parallel and instead waiting for the previous run to finish. For
example, deployments. Auto-deployments should never happen in parallel
and should wait for any currently active deployments to the same
environment, whether to staging or production, to finish before starting. …
> Add better concurrency settings for workflows

- src/stores/active-media.ts
- test/unit/specs/stores/active-media-store.spec.js
Fixes #1627 by @obulat
This PR converts the `active-media` store from a setup store to an options store. This makes all stores consistent and prevents `cannot assign to a readonly value` errors in updated versions of Pinia/Nuxt/Vue. You can see the warnings in the CI logs of #1635:
```
console.error
[Vue warn]: Set operation on key "id" failed: target is readonly.
33 |   const pinia = createPinia()
34 |   const activeMediaStore = useActiveMediaStore(pinia)
> 35 |   activeMediaStore.$patch({
|                    ^
36 |     state: {
37 |       type: 'audio',
38 |       id: 'e19345b8-6937-49f7-a0fd-03bf057efc28',
at warn$2 (node_modules/.pnpm/vue@2.7.10/node_modules/vue/dist/vue.common.dev.js:5005:21)
at Object.set (node_modules/.pnpm/vue@2.7.10/node_modules/vue/dist/vue.common.dev.js:1335:13 …
```
> Convert active media to options store

- .github/workflows/ghcr.yml
Small improvement.
This should make the slack messages a little more meaningful. Right now they say they're deploying `main`, which is true, but that makes it less transparent for tracking _which_ deployment it is. Granted you can click on the workflow link in the slack message, but it doesn't hurt to be more specific here, I don't think.
Ensure `actionlint` passes and hope it works :crossed_fingers: 
<details>
```
Version 1.1
Suite D4700 …
```
> Use the specific tag for staging deployments

- .github/workflows/ghcr.yml
Reading the documentation comment on this block, it is clear that this was a typo. We do want to cancel builds on Pull Requests but not when the `push` event happens. Otherwise this will cause staging deployments to cancel halfway through :scream:
If you look at the staging deployment log you can see that some are getting cancelled when other PRs get merged after them: https://github.com/WordPress/openverse-frontend/actions/workflows/ghcr.yml?query=branch%3Amain+event%3Apush
Check my reasoning and make sure it's consistent with the intention stated in the documentation. …
> Fix typo in concurrency cancellation check

- src/components/VModal/VModalContent.vue
- test/unit/specs/components/v-modal.spec.js
Fixes #1280 by @sarayourfriend
This PR adds ` :escape-deactivates="!hideOnEsc"` to `FocusTrap` so that the `Escape` key is handled by the `use-dialog-content` composable instead of the `focus-trap`.
The PR also updates the testing libraries. 
On mobile screen, open a menu modal or a filters modal, and press <kbd>Escape</kbd>. The modal should close. Try the same on the production site - Escape does not close the modal.
You can also check out Modal in the storybook.
<details>
```
Version 1.1
Suite D4700
San …
```
> Fix modal not hiding on escape

- DEPLOYMENT.md
Noticed this information was missing from here so adding it before I forget again :slightly_smiling_face: 
Read the new docs and let me know if it needs any clarification or other improvements.
<details>
```
Version 1.1
Suite D4700
license document, but changing …
```
> Add info about env variables to deployment doc

- .eslintrc.js
- .lintstagedrc
- README.md
Fixes #1658 by @dhruvkb 
Fixes a discrepancy between `pnpm lint:fix` and our precommit linting script. Now they run eslint and prettier formatting in the same order with the same settings.
> Fix lint staged to match pnpm:fix order and settings

- tailwind.config.js
Hotfix to make the snackbar not invisible. There's a likely tailwind bug with using color keywords or something happening. Switching from 'black' to the actual _hex color_ for black, `#000000` in the tailwind config seems to fix it.
`pnpm build && pnpm start` and observe that the snackbar is visible when tabbing over audio tracks.
also observe that the snackbar is transparent when you follow the same practice on `main`.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and …
```
> Switch from "black" css color keyword to "#000000" hex value

- src/components/VContentLink/VContentLink.vue
- test/unit/specs/components/v-content-link.spec.js
Fixes #1699 by @panchovm 
This PR disables the vcontent links when the result count is zero by:
- Removing their href
- Setting aria-disabled to true
This PR adds basic unit tests for this functionality and removes tests that no longer match the structure of the component. A previous version used radio buttons which was reflected in those tests.
The styling is a placeholder, waiting for design work from @panchovm. It currently sets the entire button's opacity to `.5`.
<details>
```
Version 1.1
Suite D4700
San …
```
> Disable content link when result count is zero

- src/pages/search/audio.vue
Fixes #1799 by @zackkrida 
When the audio result in the search results view is clicked to navigate to the single result view, it fires the `mousedown` event, followed by a `focus` event, which activates the snackbar. This PR handles these scenarios by ignoring `focus` events immediately preceded by a `mousedown`.
I'm not sure if this is the most elegant solution, but it handles the case descried in the linked issue and needs to be fixed quickly as it's already been deployed to prod.
0. Follow the steps to reproduce from #1799.
1. Fail to reproduce it on this branch.
<details>
```
Version 1.1 …
```
> Handle focus events that are fired  when the audio player is clicked

- src/components/VHeaderOld/VHeaderOld.vue
- src/composables/use-media-query.ts
- src/layouts/default.vue
- src/types/provides.ts
Fixes #1819 by @obulat
This PR re-adds the `addEventListener` to `use-media-query` composable.
It also adds the typed `provide` keys for `isMinScreenMd` and `isMinScreenLg` that will be used in the new header, and updates the `default` layout classes to use `lg` breakpoint when the `new_header` flag is On.
There are several components that depend on `isMinScreenMd` value being updated. You can check that it is actually updated, for example, using the `RelatedAudios`:
If you go to https://search-staging.openverse.engineering/audio/2ecd5631-c48c-4a5f-89c4-83c44dbbd365 and narrow the screen, you will see that the related audios are not updated to use the `VAudioTrack` components used in smaller screens.
On this branch, the `VAudioTrack` should change (because the value of `isMinScreenMd` …
> Fix `use-media-query` composable

- src/components/VLink.vue
- test/unit/setup.js
- test/unit/specs/components/AudioTrack/v-audio-track.spec.js
- test/unit/specs/components/image-grid.spec.js
- test/unit/specs/components/related-images.spec.js
- test/unit/specs/components/v-content-link.spec.js
- test/unit/specs/components/v-link.spec.js
- test/unit/specs/components/v-modal.spec.js
Fixes #1828 by @obulat
This PR replaces the conditional component (`component :is="<>"`) in `VLink` with one of three components with `v-if`/`v-else-if`/`v-else` to make it possible to use `@click.native` with `NuxtLink`. The component looks much more verbose now, but the functionality is improved. 
This PR also adds a common mocking for `NuxtLink` in unit tests.
All the links in the app should work as normal. You can also see these changes in #1825: the click handler for an internal link in the mobile modal closes the modal using a `click` handler. It wouldn't work without these changes: the click event is not passed to the parent component from a `VLink` that is a `NuxtLink` (internal link).
[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit …
> Add a click handler to VLink if it uses NuxtLink

- src/middleware/middleware.ts
- src/stores/feature-flag.ts
- test/unit/specs/stores/feature-flag-store.spec.js
Fixes #1837 by @obulat 
This PR allows feature flags to be toggled (when set to switchable) using 'ff_' prefixed query params.
The intended behaviour of the query param is to be be a one-time override to the value set in the cookie. After the query param is dropped and the page is refreshed, the flag will be reset to the value stored in the cookie.
0. Check out the PR and run the dev server.
1. Visit the preferences page and set the 'new_header' flag to off.
2. Navigate around the site and see that the new header and footer are not shown.
3. Add the query param `?ff_new_header=on` to the URL. This time the footer will appear as will remain visible as long as you navigate the site.
4. On the next reload (<kbd>Ctrl</kbd>/<kbd>Cmd</kbd> + <kbd>R</kbd>) without the param, the header and …
> Allow setting feature flags using query params

- src/plugins/api-token.server.ts
We've had a pretty large increase to our log storage costs in production. This PR tries to remove some of the logs from the API token process. I'm opening to keeping a subset of these or whatever the minimum amount of information we need to debug problems with this is.
<details>
```
Version 1.1
Suite D4700 …
```
> Reduce api token logging

- src/components/VHeader/VHeaderMobile/VShowResultsButton.vue
- src/components/VHeader/meta/VShowResultsButton.stories.mdx
Fixes #1808 by @obulat, building on top of past work by @obulat
This PR adds animation to the 'See Results' button. There are two kinds of animations, based on the reduced animation preference.
0. Check out the PR and run the Storybook.
1. Check the 'Components/VHeader/VHeaderMobile/VShowResultsButton' story.
2. In Chrome dev tools, you can emulate the 'prefers-reduced-motion' preference to see the other animation.
https://user-images.githubusercontent.com/16580576/194356548-47513998-c603-4340-a52d-069a32243821.mov
https://user-images.githubusercontent.com/16580576/194356562-6659b678-ea78-41ab-b553-d82a903056da.mov
<details>
``` …
```
> Add loading animations to the 'See Results' button

- .github/workflows/generate_pot.yml
This PR fixes the deploy failures. 
The deploy workflow is failing with the following error:
```
No .pre-commit-config.yaml file was found
- To temporarily silence this, run `PRE_COMMIT_ALLOW_NO_CONFIG=1 git ...`
- To permanently silence this, install pre-commit with the --allow-missing-config option
- To uninstall pre-commit run `pre-commit uninstall`
```
To bypass Git hooks, which are unnecessary in the automated step, we set the `--no-verify` flag when committing or pushing. Also, the `translations` branch didn't have any Husky-based hooks so there is not safety lost.
<details>
```
Version 1.1 …
```
> Skip Git hooks when updating PO file

- Dockerfile
- bin/install-pre-commit.sh
- package.json
Add another facility to skip the pre-commit installation in environments that do not need it
Fixes the staging builds failing
We added `--ignore-scripts` so that `prepare` would be skipped inside Docker. Nuxt and some other dependencies need those scary post-installation, apparently, to make things work so we can't skip `prepare` in that way. I've added a different facility for skipping the pre-commit installation in Docker.
```
docker build . --build-arg API_URL=https://api.openverse.engineering/ --build-arg RELEASE=v0-test -t openverse-frontend:latest
docker run -p 8443:8443/tcp  openverse-frontend:latest
```
And then make a request to the local server. Before this PR it will fail on an error about reading `use` of undefined. After this PR it will work.
- [N/A] I added or updated tests …
> Remove ignore scripts (nuxt requires it)

- src/layouts/default.vue
Fixes #1891 by @obulat
This PR makes  `isNewHeaderEnabled` a computed so that it's updated when you check the `new_header` checkbox on the Preferences page.
Go to the Preferences page (http://localhost:8443/preferences) and check the `new_header` flag. You should see the header updated immediately (it should now have internal links).
You can also try the [staging](https://search-staging.openverse.engineering/preferences) to see that the header there is not updated until you reload the page.
<details>
```
Version 1.1 …
```
> Make `isNewHeaderEnabled` a computed so that it's updated

- src/components/VButton.vue
Fixes #1909 by @Jorgewlf88
'Get this media' button scales to match title height
[Screenshot](https://ibb.co/w4MjMJz)
<details>
```
Version 1.1
Suite D4700 …
```
> Fix the height of the button adding a new class

- src/components/VHeader/VSearchBar/VSearchBar.vue
Fixes #1886 by @zackkrida
This is a follow up for [1889](https://github.com/WordPress/openverse-frontend/pull/1889) to close the Recent searches popover when pressing <kbd>Shift</kbd>+<kbd>Tab</kbd> while inside the input (when you get to the Openverse logo).
On main, when you press <kbd>Shift</kbd>+<kbd>Tab</kbd> while inside the search input, you focus the Openverse logo, but the Recent searches popover stays open. Here, it should close.
<details>
```
Version 1.1
Suite D4700
Everyone is …
```
> Close the recent searches on Shift+Tab

- src/components/VHeader/VHeaderMobile/VContentSettingsModal.vue
- src/components/VHeader/VSearchBar/VSearchBar.vue
- src/components/VTabs/VTab.vue
Fixes #1897 by @obulat
This PR adds hover styles to the mobile Content switcher tabs and to the close button.
Check that the components match the mockups, and the old components (Tabs on the `/feedback` page and the Copy license component) are not changed.
<details>
```
Version 1.1
Suite D4700 …
```
> Add hover styles to the tabs and close button

- src/components/VAudioTrack/layouts/VFullLayout.vue
- src/components/VButton.vue
- src/pages/image/_id.vue
Fixes #1929 by @obulat
This PR moves `self-center` class for fixing the CTA button from `VButton` component to the parent components of the CTA button.
<details>
```
Version 1.1
Suite D4700
have the right to submit …
```
> Fix VButton centering

- src/components/VFourOhFour.vue
- src/components/VSelectField/VSelectField.vue
Fixes #1935 by @obulat
This PR updates the language chooser to match the Figma mockups.
Since the dark charcoal 20% border involves some transparency the border color was not `border-dark-charcoal-20` but rather `#d6bb32`. On macOS, you can use the Digital Color Meter app to verify this by zooming in Figma and hovering over the border.
- Visit http://localhost:8443/search/?q=cat&ff_new_header=on and see the language chooser in the footer.
- Visit http://localhost:8443/404/?ff_new_header=on and see the language chooser in the footer.
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux …
```
> Update the language selector to work with the yellow pages

- src/components/VInputFieldOld/VInputFieldOld.vue
Fixes #1948 by @0kyn 
This PR fixes the name defined in the `VInputFieldOld` component.
<details>
```
Version 1.1
Suite D4700
(b) …
```
> Fix `VInputFieldOld` component name

- nuxt.config.ts
- src/plugins/sentry.ts
Fixes #1620  by @sarayourfriend 
added render context property to the sentry event that is sent when there is an error
[screenshot](https://ibb.co/gvNrfC2)
i`ve tested it on my own sentry account and it seems to work...
someone with access to sentry needs to test this.
1. go to util/sentry-config.ts
2. paste the project dsn in the dsn property.
3. comment out the disabled and clientConfig property.
4. go to pages/index.vue
5. insdie setup(), throw an error
6. open the project in the browser.
7. go to sentry, look for that error and check if there is render context -> platform: server, in the report.
8. got to pages/index.vue again. now, encapsulate your error with an if statment that checks if the proccess is client
` if (process.client) {
throw new Error('test index page')
}`
9. repeat …
> add render context prop to sentry error event

- README.md
- justfile
- package.json
This PR adds two docker scripts, `docker:build` and `docker:run`, to the pnpm `package.json` config. I've also replaced the uses of those docker commands in the README with the associated `pnpm` command.
I've also added a `justfile` to this repo so `just` can be used in lieu of `pnpm`. Since we use `just` for our other projects, this can help make the workflow similar to our other projects!
Run the following:
1. `just`
1. `just run docker:build`
1. `just run docker:run`
<details>
```
Version 1.1
Suite D4700
San …
```
> Add docker scripts and just shim

- src/components/VFourOhFour.vue
- src/components/VHeader/VSearchBar/VSearchBar.vue
- src/components/VHeader/VSearchBar/VSearchButton.vue
- src/components/VHeader/VSearchBar/VStandaloneSearchBar.vue
- src/components/VHeaderOld/VSearchBar/VSearchBarOld.vue
- src/components/VHeaderOld/VSearchBar/VSearchButtonOld.vue
- src/pages/index.vue
Fixes #1947 by @obulat
There are two components for the Search button: old and new. Currently, `VSearchButton` is used only on the search page with the `new_header`. The `VSearchButtonOld` is used everywhere else (in the search pages with the `old_header` and the standalone search bar on the 404 and home pages)
This means that we cannot simply remove the component when we switch to the `new_header` as the standalone search bar would be using it.
To solve it, this PR refactors the components. Now, the `VSearchButtonOld` is only used on the search pages with `old_header` layout, and can be safely deleted when we switch on the `new_header` flag in production.
There are no additional tests, but there are VR tests for the search button on all pages that still pass in this PR, so it means there …
> Refactor VSearchButton

- src/components/VSelectField/VSelectField.vue
Fixes #1970 #1972 by @obulat 
1. As the classes ```border border-dark-charcoal``` and ```border-opacity-20``` were no longer dynamic so they were moved to static class.
1. The variant prop was not being used so it was removed. 
<details>
```
Version 1.1
Suite D4700
(a) The …
```
> Classes moved to static class and redundant variant prop removed #1970 #1972

- src/components/VHeader/VHeaderDesktop.vue
- src/components/VHeaderOld/VHeaderFilter.vue
- src/layouts/default.vue
Fixes #1958 by @obulat
This PR removes the sidebar `Teleport` to improve the rendering of the desktop filters. Instead, the `VSearchGridFilter` used for the desktop filters sidebar is rendered in `default.vue` layout.
<details>
```
Version 1.1
Suite D4700 …
```
> Improve filter sidebar rendering performance

- src/components/VGlobalAudioSection/VGlobalAudioSection.vue
- src/components/VSnackbar.vue
- src/constants/z-indices.js
Fixes #2018 by @sarayourfriend 
This PR
- puts the z-index of the global audio player at 20 (starting a new stacking context, so we can reduce the z-index of the &times; to 10)
- reduces the z-index of the snackbar to 10
This prevents the visible/invisible snackbar from overlapping with player controls. The use of clearer z-index names should prevent such issues in the future.
In the long term, adoption of an official system for z-indices (such as Material design's) could be immensely useful.
^ https://m2.material.io/design/environment/elevation.html#default-elevations
^ https://m1.material.io/material-design/elevation-shadows.html#elevation-shadows-elevation-android
Try reproducing the linked bug with the PR checked out. You should fail. …
> Prevent obstruction of audio player controls

- src/components/VContentSwitcherOld/VMobileMenuModal.vue
- src/components/VContentSwitcherOld/VSearchTypePopoverOld.vue
- src/components/VHeaderOld/VHeaderMenu.vue
- test/playwright/e2e/mobile-menu-old.spec.ts
Fixes #2004 by @obulat
When you select a search type in the mobile modal (with the old header), the modal should close. This wasn't happening because `closeMenu` method was not available in `VMobileMenuModal.vue`. This PR adds the method, and fixes some template ref types.
<details>
```
Version 1.1
Suite D4700 …
```
> Fix mobile menu not closing

- src/components/VModal/VInputModal.vue
- src/components/VModal/VModalContent.vue
- src/composables/use-dialog-content.ts
- src/composables/use-focus-on-show.ts
- src/composables/use-popover-content.ts
- test/playwright/e2e/homepage.spec.ts
Fixes #2033 by @zackkrida
The change that moved the focus trap from the VModal component into the useDialog composable failed to account for the fact that Popovers also use it, and don't need a focus trap.
This PR only activates/deactivates the focus trap if the `trapFocus` prop is set to `true`, and sets `trapFocus` to `false` for VPopover component. 
It also adds an e2e test for closing the popover on click outside and pressing Escape to the `homepage` e2e test (that's the simplest place where we can open a popover).
Try running the app on desktop. Open the popovers (content switcher on the homepage, pages menu or content switcher in the header) and check that pressing Escape or clicking outside closes them.
[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to- …
> Fix popover not closing on Escape or click outside

- src/middleware/middleware.ts
- src/stores/ui.ts
- test/unit/specs/stores/ui-store.spec.js
Fixes #2029 by @obulat 
This PR sets the UI cookies' `sameSite` to `None` if the new_header is Off to stop them from being rejected when Openverse is inside the iframe.
<details>
```
Version 1.1
Suite D4700
have the …
```
> Set same site to None when `new_header` is off

- src/components/VHeaderOld/VPageMenu/VPageList.vue
Fixes #2008 by @sarayourfriend 
This PR fixes the absence of bottom margin in pages menu.
search for something. then, in the results page at the top of the page click on the 3 vertical dots button.
hover over the last element in the menu
<details>
```
Version 1.1
Suite D4700
(a) …
```
> fix margin bottom of pages menu

- .github/workflows/ghcr.yml
Fixes #1937 by @obulat
This PR replaces the outdated `set-output` command with the recommended value: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands
The CI should work
<details>
```
Version 1.1
Suite D4700
(a) The …
```
> Replace deprecated `set-output` command

- .github/actions/staging-frontend-deploy/action.yml
Related to #2052 by @krysal
This PRs updates `.github/actions/staging-frontend-deploy/action.yml` with the output from terraform.
Let's test on staging first to see if it works correctly, then once confirmed the same changes will be applied to the `.github/actions/production-frontend-deploy/action.yml` file.
Merge and trigger a staging deployment to confirm.
<details>
```
Version 1.1
Suite D4700 …
```
> Ping staging deployer in Slack notification

- src/components/VAllResultsGrid/VAllResultsGrid.vue
- src/components/VContentSwitcher/VSearchTypeItem.vue
- src/components/VContentSwitcherOld/VSearchTypeItemOld.vue
- src/components/VFilters/VSearchGridFilter.vue
- src/components/VFourOhFour.vue
- src/components/VHeader/VHeaderDesktop.vue
- src/components/VHeader/VHeaderMobile/VHeaderMobile.vue
- src/components/VHeaderOld/VHeaderMenu.vue
- src/components/VHeaderOld/VHeaderOld.vue
- src/pages/index.vue
- src/pages/search-help.vue
- src/stores/search.ts
- test/unit/test-utils/pinia.js
Fixes #2044 by @obulat
This PR adds two methods that return a localized search path to the search store: 
- `updateSearchPath` - can update the search state (search term and search type) and return the updated path.
- `getSearchPath` - can return a path for a search type that's different from the current search type to use, for example, in the content links.
Try searching for something, updating the search type, changing the search term: the search path should always be updated correctly. Also, if you select some filters on the "All media" search view and click on the Content links (See all images/audio), the new page should have correct URL. 
It should work both with the old header and the new one, and for all languages.
[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Cont …
> Move getting localized search path to the search store

- .github/actions/staging-frontend-deploy/action.yml
Follow up of #2053.
Previous changes to the **staging-frontend-nuxt-deploy** action [are not working](https://github.com/WordPress/openverse-frontend/actions/runs/3734996887/jobs/6337773734) because the encrypted secrets cannot be used directly, they need to be provided to actions as an input or environment variable, according to [GitHub docs](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow). I use an envvar here so trying again to see if it works.
<details>
```
Version 1.1 …
```
> Set and use `GH_SLACK_USERNAME_MAP` as an environment variable

- .github/actions/staging-frontend-deploy/action.yml
Follow up of #2056, #2055 and therefore #2053.
Fix for the staging deployment. Here I omit the use of the `toJSON` function of GitHub actions, which might not be necessary if we follow how the input is set in other lines:
https://github.com/WordPress/openverse-frontend/blob/8881cd57f0a2963406e49c48de1bb6a62dff4015/.github/workflows/ghcr.yml#L62-L66
Also, use single quotes instead of double quotes and make the following steps continue even if the slack user and the notifications steps fail.
<details>
```
Version 1.1
Suite D4700 …
```
> Try without `toJSON` function and continue in any case

- .github/actions/staging-frontend-deploy/action.yml
- .github/workflows/gh-pages.yaml
Now that we know the python code works[^1], I want to try the bash version that @sarayourfriend suggested. It's much more straightforward.
[^1]: Successful run: https://github.com/WordPress/openverse-frontend/actions/runs/3743973967/jobs/6356853268
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the …
```
> Simplify step for setting the Slack user in GH action

- .github/actions/production-frontend-deploy/action.yml
- .github/actions/staging-frontend-deploy/action.yml
- .github/workflows/ghcr.yml
- .github/workflows/rollback.yml
Fixes #2052 by @krysal 
This completes the changes for the production environment, while going back to Python for setting the Slack user as the bash code tried in #2058 didn't work. You can see that the user is not shown correctly:
[`ef8794f`](https://github.com/WordPress/openverse-frontend/commit/ef8794f4c601c859fabcd915b85e447c086f4472) is the commit with the bash changes. Might only need to use `toJSON`/`fromJSON` functions for the `gh-slack-username-map` secret, but I'll let that minor improvement for later. The action worked with the python code:
Just trying an actual deployment.
<details> …
> Ping deployer on production Slack notification 

- src/components/VAudioTrack/layouts/VBoxLayout.vue
- test/playwright/e2e/homepage.spec.ts
- test/playwright/e2e/translation-banner.spec.ts
- test/playwright/utils/navigation.ts
Fixes #730  by @panchovm 
added hover state to the play pause button on the result page
https://user-images.githubusercontent.com/29175506/212543143-099de987-2805-4f4e-aec1-eb413903e03c.mp4
* search for something while content type is set to all content
* hover over an audio`s result play-pause button
errors.
<details>
```
Version 1.1
Suite D4700
license document, but changing …
```
> add hover state for play-pause button

- .github/actions/production-deploy/action.yml
- .github/actions/staging-deploy/action.yml
Follow up to https://github.com/WordPress/openverse-infrastructure/pull/353 and similar to https://github.com/WordPress/openverse-api/pull/1114
This PR updates the deployment actions to use the new definitions.
Merge and find out I suppose! Hard to test GitHub actions on their own.
errors.
<details>
```
Version 1.1
Suite D4700 …
```
> Update deployment actions using new definitions

- src/components/VFourOhFour.vue
- src/components/VModal/VInputModal.vue
- src/components/VModal/VModalContent.vue
- src/layouts/default.vue
- src/pages/index.vue
- test/playwright/utils/navigation.ts
- test/playwright/visual-regression/pages/no-results.spec.ts
Fixes #2110 by @obulat
This PR fixes the bug where the bottom of the screen is cut-off and hidden behind the address bar on mobiles by using `dvh` units for screen height.
Currently, the support for them is below 80%, so as a fallback, we set the height to 100 vh but also add a bottom padding to the modals to make sure that clickable elements are not hidden.
Run the app and test it on a mobile. You should see the WordPress logo in the footer. When you input something in the hompage searchbar, even the bottom part of the screen should remain yellow. When you open modal (content switcher on homepage), none of it should be hidden.
I don't have a phone to test the fallback, it would be nice if someone could test it on a real device.
errors. …
> Set layout height to 100dvh with fallback to 100vh

- nuxt.config.ts
Prometheus metrics generally should not be served on a public endpoint. The easiest way to make the metrics publicly inaccessible is to serve them on an entirely separate port. This allows us to easily make security group changes that only allow services internal to our VPC (specifically, Grafana Agent) to access the metrics endpoints.
In the process, I also went ahead and fixed some issues with the Prometheus development workflow, namely that its metrics were disabled by default in development due to a persistent crash when the server automatically restarts after changes. To fix this, we just need to de-register all the existing metrics when the server closes. This allows the `express-prom-bundle` middleware to re-register the same metrics without causing name clashes with the metrics …
> Serve Prometheus metrics on a separate port; fix metrics development workflow

- src/components/VFilters/VSearchGridFilter.vue
- test/playwright/e2e/search-navigation-old.spec.ts
- test/playwright/e2e/search-navigation.spec.ts
Fixes #505 by @sarayourfriend 
as described in the issue by @sarayourfriend, currently when selecting several filters one after the other
a query will be excuted for each filter selection.
so, as suggested in the issue i added a debounce of 500ms to filter selection (basically switched the watch function to watchDebounced )
<b>Staging</b>
https://user-images.githubusercontent.com/29175506/213170688-53d17a10-0bb6-4039-88e6-88bd50cfa0bf.mp4
<b>This PR</b>
https://user-images.githubusercontent.com/29175506/213171268-41363f93-a314-4d4f-8644-e3d18fb12bb7.mp4
follow the steps in the video :)
errors.
<details> …
> Add Debounce to filter selection

- nuxt.config.ts
- src/layouts/content-layout.vue
- src/layouts/default.vue
- src/pages/search/audio.vue
- src/pages/search/image.vue
- src/pages/search/index.vue
- src/server-middleware/robots.js
- Add robots.txt file, which deindexes the staging site
- Make `canonical` and `hreflang` links absolute
- Deindex search routes, for now
- Run the app locally
- Go to the robots.txt route and observe the correct contents for staging
- Inspect any page, find the 'canonical' tag and observe that it starts with "https://openverse.org"
- Observe search routes are no longer indexed
> Baseline SEO improvements

- src/components/VAudioTrack/VAudioTrack.vue
- test/unit/specs/components/AudioTrack/v-audio-track.spec.js
Fixes #2118 by @obulat
This PR tightens the condition that allows playback to continue by using the router matching composable. This fixes the condition where audio playback would continue on any page.
0. Check out the PR and run the dev server.
1. Search for a term.
2. Play an audio track.
3. Click on any other result (be it image or audio) to open the single result page. Audio playback should be stopped. (Technically you could navigate to any other page, even the home or content pages and the playback should stop).
4. Go back and resume the audio track again.
6. Click on the same result to open the single result page. Audio playback should continue from the same spot.
errors. …
> Tighten the condition for audio playback to continue across pages

- nuxt.config.ts
- src/modules/prometheus.ts
This PR is a suggested implementation of extracting the Prometheus setup from `nuxt.config` into a separate Nuxt module. I think it will be easier to have Prometheus set up as a separate module when moving from Nuxt 2 to Nuxt 3 because it will not affect the `nuxt.config` changes anymore, and typing the modules should become easier with Nuxt3.
> Extract Prometheus module

- package.json
- pnpm-lock.yaml
- src/locales/scripts/axios.js
- src/locales/scripts/get-translations.js
Fixes #2170 by @AetherUnbound 
This PR installs the `axios-rate-limit` module and sets up rate limiting for requests to GlotPress. This ensures that 429 errors are not raised and all translations are reliably downloaded.
This also adds logging in the `get-translations.js` script which prints the names of locales that fail to download. 
0. Check out the PR.
1. Run `pnpm i18n:get-translations` with various rate limits in `src/locales/scripts/axios.js`. Very low limits like 10 or 20 will slow down the download considerably, whereas very high limits like 200 or 1000 will report large number of failures due to 429 errors. With the rate-limiting enabled and set to 99 (lower than 100 req/sec), no failures are recorded.
Example output when rate limit is set to 1000.
```
Successfully saved English …
```
> Make translations more reliably present in all environments

- src/locales/scripts/axios.js
Fixes #2170 by @AetherUnbound by improving #2172 by @dhruvkb
Even with the limit of 99 requests per second, the GlotPress download reports several 429 errors. This was not happening when the PR #2172 was made but it's happening now, because of which staging.openverse.org again lacks some languages. The situation is better, we have ~150 languages now but still not all of them (~200).
This PR reduces the rate limit even further. It would be better if GlotPress had some official documentation around rate limits. Alternatively we could fail the deploy if the download step is incomplete?
errors.
<details> …
> Reduce GlotPress limit further to ensure all languages

- src/components/VHeader/VWordPressLink.vue
Fixes #2183 by @obulat
This PR adds an `aria-label` to the WordPress link in the footer to make sure that the screen readers read it correctly, with the necessary pauses between the words.
Turn on a screenreader and listen to what it says for the link in the footer.
errors.
<details>
```
Version 1.1
Suite D4700
Developer's …
```
> Use aria-label for WordPress affiliation link

- src/components/VSkipToContentContainer.vue
- src/layouts/default.vue
- src/pages/audio/_id/index.vue
- src/pages/image/_id/index.vue
- src/pages/image/_id/report.vue
- src/pages/index.vue
Related to #2174 by @obulat
#2175 grew to be too big, so I extracted a part of it into this PR. This PR only deals with the single result pages (image, image/report, audio). It also refactors the `VSkipToContentContainer` to allow setting its tag to `main`.
The single result pages should have a "Skip to content" link that is the first element on the page that gets focus.
errors.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy …
```
> Add "skip to content link" to the Single result pages

- src/locales/scripts/bulk-download.js
- src/locales/scripts/get-translations.js
- src/locales/scripts/separate-download.js
- src/locales/scripts/utils.js
This PR improves upon #2188 in the following ways
- breaks the code down into async functions, reducing the use of promises
- breaks the large `get-translations.js` file into smaller files that work independently
- adds error handling at critical points
- adds fallback to separate parallel downloads when bulk download fails
- adds a flag `--require-complete` that can be passed to halt builds when the translations are incompletely downloaded.
All in all, this PR adds significant resilience to the multi-pronged approach developed in #2188.
0. Check out the PR.
1. Try different combinations of the following:
- Make credentials
- valid
- invalid
- rate limits in `src/locales/scripts/axios.js`
- reasonable (~50)
- unreasonable (~1000)
- `--require-complete` flag
- set 
- unset
`Update …
> Simplify `get-translations.js` and add error handling and fallbacks

- src/locales/scripts/en.json5
Fixes #2189 by @zackkrida
Add a note for translators to not translate 'network', 'Netflix' and 'Netherlands', which are used as examples of words starting with 'net'. If translated to these would no longer be valid examples.
An alternative approach would be to pick a different triplet of words in each language but that would be too cumbersome and wouldn't accurately reflect the English-centric nature of the Openverse search engine.
Test that the POT contains the comment.
errors.
<details>
```
Version 1.1 …
```
> Add a directive for translators to not translate Netherlands
