WordPress/openverse-frontend

README.md, package-lock.json, package.json
Switch version numbers back to semver from calver
=> Release version 2.0.0 and switch back to semver

src/components/Filters/FilterBlock.vue, src/components/Filters/FilterDisplay.vue, src/locales/en.json, src/pages/search.vue, src/store-modules/filter-store.js, src/store/index.js, src/utils/searchQueryTransform.js, test/unit/specs/components/filter-display.spec.js, test/unit/specs/utils/searchQueryTransform.spec.js
Fixes #93 
Ensure that the filter data from URL query is saved in the store.
Simplify filter display.
=> Make store the only source of truth for filter data

nuxt.config.js, package-lock.json, package.json
A new major release of the nuxt-18n plugin which includes a rename of the package and some deprecations that fortunately didn't effect us.
Simply swaps the old library for the new one and removes the deprecated `seo` option.
Look at the app without embedded mode to ensure translations are working.
<details>
```
Version 1.1
Suite D4700
By …
```
=> Update nuxt-i18n to @nuxtjs/i18n

nuxt.config.js, src/layouts/embedded-with-nav-search.vue, src/layouts/embedded.vue, src/locales/en.json
Builds on work in #121.
Includes the default `description` meta tag in translation files.
Are there any other tags that require translation?
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the …
```
=> Translate default `description` meta tag

src/utils/getLegacySourceUrl.js
Related to https://github.com/WordPress/openverse-catalog/issues/39
Adds the "Images of Empowerment" collection to image meta search. A good first step for integrating them into the catalog.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part …
```
=> Add images of empowerment to meta search

.lintstagedrc
Since the repository also contains MDX files now, which Prettier supports, they should automatically be formatted with Prettier when staged.
ESLint does not work with MDX files, so the entry for Prettier cannot be merged with the existing `*.{js,vue}` entry.
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, …
```
=> Automatically format MDX files with Prettier

src/components/AudioTrack/AudioTrack.vue, src/components/AudioTrack/meta/AudioTrack.stories.mdx
**Please merge #127 before this**
This PR creates a compact version of the track introduced in #127. This compact version is used in places such as the search results and related audio.
Since there are slight differences in the two versions that cannot be dynamically handled, the component has a bit of code duplication in the `template` section.
<details>
```
Version 1.1
Suite D4700 …
```
=> Create a compact version of the track

src/components/ContentReport/ReportError.vue, src/components/EmbeddedNavSection.vue, src/components/NavSection.vue, src/components/SearchGridManualLoad.vue, src/components/SearchRating.vue, src/locales/en.json, src/pages/meta-search.vue, src/pages/sources.vue
This PR changes some i18n string key names so that there are no repeated keys.
When using json files for i18n, it is OK to have some parts of a long key, eg. `feedback` in `about-page.feedback` and `search-result.feedback` be the same, because the full key is different. However, because we are converting the json files to PO files for translation, and then PO files to json files to display them in the app, this becomes problematic. Therefore, it is easier to make all the i18n keys unique.
<details>
```
Version 1.1 …
```
=> Ensure i18n keys are unique

src/components/AudioTrack/PlayPause.vue, src/components/AudioTrack/Waveform.vue, tailwind.config.js
Fixes #147 by @sarayourfriend
Fixes #190 by @sarayourfriend
Fixes #191 by @sarayourfriend
This PR adds the focus indicator to the waveform.
The focus outline of the play/pause button interferences with the waveform seekbar, likely due to complex `z-index` layers inside the `Waveform` component. This might be tricky to solve.
https://user-images.githubusercontent.com/16580576/132212606-9dd3d87a-1cd3-475e-93e7-da66b9af6a85.mov
Uses <kbd>Tab</kbd> and <kbd>Shift</kbd>+<kbd>Tab</kbd> to focus forward and backward respectively.
<details>
```
Version 1.1 …
```
=> UI improvements for audio track

tailwind.config.js
This PR configures Tailwind to provide the typographical utilities as defined in [Figma](https://www.figma.com/file/vEoItpMQyFZb5AZV9aoP7I/Audio-integration?node-id=1147%3A11088). These utilities will be useful in all UI building PRs, hence this is a bit urgent.
The line-heights are now included in the font-sizes based on the defaults. They can be configured on a per-usage basis using the `leading-*` utilities, also configured in the PR itself.
<details>
```
Version 1.1
Suite D4700
Everyone …
```
=> Update Tailwind config to match typography from Figma

nuxt.config.js, src/locales/scripts/get-validated-locales.js, src/locales/scripts/locales-list.json, src/locales/scripts/update-locale-list.js, src/locales/scripts/valid-locales.json, src/mixins/i18n-sync.js, src/pages/about.vue, src/pages/extension.vue, src/pages/feedback.vue, src/pages/index.vue, src/pages/meta-search.vue, src/pages/photos/_id.vue, src/pages/search-help.vue, src/pages/search.vue, src/pages/sources.vue
Fixes #199 by @zackkrida 
The WordPress theme emits `localeSet` events in response to `localeGet` events (WordPress/wordpress.org#39). This PR sends `localeGet` events and updates the Nuxt i18n locale based on the data of the returned `localeSet` event.
This PR turns off the URL prefix because that leads to the URL containing a language in the subdomain as well as subpath, which might be different leading to inconsistent and bad UX.
1. Set up the `wp-openverse` theme locally with `wp-env`.
2. Launch the Nuxt server with `npm run dev`.
3. Set the Nuxt server URL (`http://localhost:8443`) as the `iframe` URL in the theme customizer.
https://user-images.githubusercontent.com/16580576/132738567-88b387e6-b6c9-4253-ae73-9699b0b3b4d3.mov …
=> Sync locale and lang from WordPress theme

src/assets/fonts.css, src/components/Dropdown.vue, src/styles/components/navbar.sass, src/styles/utilities/icon-font.scss, src/styles/utilities/initial-variables.scss, src/styles/vocabulary.scss
Fixes #220 by @zackkrida
Fixes #221 by @zackkrida
This PR increases the z-index value for dropdowns in order to show them over the search form input, and includes again the Vocabulary font to recover icons.
Adds the same font version that we were using before #208.
<details>
```
Version 1.1
Suite D4700 …
```
=> Fix dropdowns and icons

README.md
This PR makes fixes the link to the handbook in the README by making it absolute, instead of relative.
<details>
```
Version 1.1
Suite D4700
indicated in the …
```
=> Make the link to the handbook absolute

src/pages/search-help.vue
This PR fixes spacing missing between the title and body content.
Add title spacing on `search-help` view
Title spacing seems to be already present on `feedback` view
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon …
```
=> Add title bottom spacing

src/components/Filters/LicenseExplanationTooltip.vue
Replace ccsearch with openverse
issue track: https://github.com/WordPress/openverse-frontend/issues/181
Fixes #181 by @obulat
Replaces ref=ccsearch with ref=openverse
Updated URL ref parameter values for analytics.
<details>
```
Version 1.1
Suite D4700 …
```
=> Update URL ref parameter values for analytics

src/components/License/License.vue
Fixes #258 by @zackkrida 
Improves the spacing of icons in the Audio track row.
<details>
```
Version 1.1
Suite D4700
(b) The …
```
=> Fix license icon spacing

src/locales/po-files/openverse.pot, src/locales/scripts/get-translations.js, src/locales/scripts/json-to-pot.js
Fixes #260 by @zackkrida
~Also capitalizes the contents of `###STRING###` strings to better match the spec/convention.~ Could do that, but I think the comments are helpful enough and I don't want to make even more work for translators.
<details>
```
Version 1.1
Suite D4700
(a) The …
```
=> Switch to extracted comments in `openverse.pot`, remove duplicated context

src/components/AudioTrack/layouts/Full.vue, src/locales/en.json, src/locales/po-files/openverse.pot
Fixes #263 by @panchovm 
This PR puts the creator of the audio track ('full' layout) on the second line. This gives more room for the title.
It also removes the now-unused i18n key.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part by me …
```
=> Put the creator of the track on a new line

nuxt.config.js, src/utils/session-id.js
Fixes #266 by @zackkrida
Fixes #265 by @zackkrida
This PR implements the cookie policies necessary for usage with an iFrame. This should fix the production translation issue as well.
1. This requires testing localhost securely, so try the following steps:
2. Build Openverse locally with `npm run build`
3. Run `brew install mkcert nss` to easily manage local certificates
4. Run `mkcert -install` so your machine automatically trusts created certificates
4. Run `mkcert localhost` in the root of the project
5. Add the following to `nuxt.config.js`:
```js
// at the top
import fs from 'fs'
import path from 'path'
// in the "server" block:
https: {
key: fs.readFileSync(path.resolve(__dirname, 'localhost-key.pem')),
cert: fs.readFileSync(path.resolve(__dirname, 'localhost.pem'))
}
```
6. Run `npm …
=> Cookie policies for iframe usage

src/assets/fonts/VocabularyIcons.json, src/components/ImageDetails/ImageAttribution.vue, src/components/ImageDetails/ImageInfo.vue, src/components/ImageDetails/PhotoDetails.vue, src/components/MediaInfo/CopyLicense.vue, src/components/MediaInfo/MediaLicense.vue, src/components/MediaInfo/MediaReuse.vue, src/pages/audio/_id.vue, src/utils/attribution-html.js, test/unit/specs/components/ImageDetails/copy-license.spec.js, test/unit/specs/components/ImageDetails/image-attribution.spec.js, test/unit/specs/components/ImageDetails/image-info.spec.js
Fixes #254   by @dhruvkb 
This PR would make the prop name uniform across the code base by changing the non-camelcase to camel case.
For now these changes has been made across the code base:
`ccLicenseURL to ccLicenseUrl`
`licenseURL to licenseUrl`
`openverseLicenseURL to openverseLicenseUrl`
<details>
```
Version 1.1
Suite D4700
By …
```
=> Url camelcase fix

README.md, src/data/usage-data-service.js
Removes old, out of date references to api.creativecommons.engineering and replaces them with openverse.
<details>
```
Version 1.1
Suite D4700
indicated in …
```
=> Remove references to api.creativecommons.engineering

src/components/ScrollButton.vue, tailwind.config.js
Fixes #247 by @sarayourfriend
This PR gives the 'ScrollButton.vue' back to top component a refresh:
- Transitional blue background cover and hover bg color
- New WordPress 'chevron up' SVG 
- Uses constants for spacing instead of arbitrary numbers
- Scroll down the page and view it!
<details>
```
Version 1.1
Suite D4700
By making a …
```
=> Fix 'scroll to top' button

package-lock.json, package.json
Fixes #291 by @0kyn 
This PR adds `cross-env` dependency to support Windows OS
`npm install`
<details>
```
Version 1.1
Suite D4700 …
```
=> Add `cross-env` dependency

Dockerfile
Fixes #225 by @zackkrida 
1. Updates the node and npm versions used by the Dockerfile to match the Volta specification we have in `package.json`
2. Adds a run of `i18n:get-translations` after installing. I guess these could be split into separate RUN layers but I'm not sure whether that's necessary or better? cc @AetherUnbound 
Checkout the branch and run `docker-compose build` then `docker-compose up` and ensure the frontend starts.
<details>
```
Version 1.1
Suite D4700
Everyone is …
```
=> Update Dockerfile node/npm version and add translations

.github/ISSUE_TEMPLATE/component_spec.md
This PR improves the component specification by
- removing the redundant heading at the top as it's the same as the issue title
- adding a dependencies section to list blockers or components that must be developed first
<details>
```
Version 1.1
Suite D4700
(a) The contribution …
```
=> Add a dependencies section and remove the redundant title

jest.config.js, package-lock.json, package.json, src/components/VButton.vue, src/components/meta/VButton.stories.js, src/utils/a11y/get-tab-index.js, src/utils/a11y/is-native-tabbale.js, src/utils/a11y/supports-disabled-attribute.js, tailwind.config.js, test/unit/specs/components/v-button.spec.js
Fixes #365 by @sarayourfriend
Adds a base `VButton` component that basically just wraps the default `button` element with styles as well as some sensible defaults like `type = 'button'`. There is also explicit `active` state handling to allow for situations where a button might need the "active" appearance without being actually `:active` (which only applies to anchor elements anyway).
Checkout this branch and run `npm install` then `npm run storybook` and verify that the `VButton` component in Storybook looks the same as the figma designs linked in the issue attached to this PR.
<details>
``` …
```
=> Add base Button component

src/components/AppModal.vue, src/components/AudioResultsList.vue, src/components/Filters/FiltersList.vue, src/components/Filters/LicenseExplanationTooltip.vue, src/components/Filters/SearchGridFilter.vue, src/components/HeroSection.vue, src/components/SearchGridForm.vue, src/components/SearchGridManualLoad.vue, src/pages/audio/_id.vue, src/pages/search.vue, tailwind.config.js, test/unit/specs/components/search-grid-filter.spec.js
Fixes #391 by @krysal 
This PR removes the custom screen breakpoints in favor of Tailwind defaults. It updates classes prefixed with old names, for example `desk:hidden` to `lg:hidden` (min-width: 1024px) and `tab:px-0` to `md:px-0` (min-width: 768px).
Also replaces the Bulma's named mixin `@include desktop` with the Tailwind equivalent `@screen lg`. This is not possible to do with mixins `@include tablet` and `@include mobile` as they use `max-width` instead of `min-width`, so no equivalent exists yet.
Run the project and see everything remains with the same styles, also all unit tests pass.
<details>
``` …
```
=> Tailwind breakpoints

src/components/Skeleton/GridSkeleton.vue
Fixes an issue caused by `GridSkeleton` using breakpoint names from before #403. This PR updates the `@screen` directives to the new names.
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the …
```
=> Update breakpoints to the new Tailwind config

src/components/HeroSection.vue, src/components/HomeLicenseFilter.vue, src/styles/form/shared.sass
Fixes #424 by @dhruvkb
The PR updates the styling for the components
- `HeroSection`
- `HomeLicenseFilter`
to correct problems that plague their RTL-version. Some redundant styling has been removed and some migration to Tailwind has also been performed.
See tracking issue #421 for instructions to reproduce. These instructions should no longer be able to reproduce the issue.
<details>
```
Version 1.1
Suite D4700
license …
```
=> Make Homepage RTL-compatible

package-lock.json
Just a quick PR to fix this. Noticed it while reinstalling dependencies on `main`.
N/A
- [N/A] My code follows the established code style of the repository.
<details>
```
Version 1.1
Suite D4700
By making a …
```
=> Fix package-lock.json engines

src/styles/base/layout.sass, src/styles/components/navbar.sass, src/styles/utilities/initial-variables.scss
Fixes #440 by @dhruvkb
This PR updates the breakpoints used in Sass files (based on previously used Bulma CSS library) to match Tailwind values.
I also reviewed the `navbar.sass` file to make sure that the breakpoints are used correctly, and found and fixed a couple of small left-over issues with RTL-compatibility.
<details>
```
Version 1.1
Suite D4700
Developer's …
```
=> Update Sass breakpoints to match tailwind

nuxt.config.js, src/server-middleware/healthcheck.js
Fixes #466 by @rbadillap
This PR adds a `/healthcheck` endpoint that returns 'OK' with the following headers:
```
HTTP/1.1 200 OK
Date: Wed, 01 Dec 2021 06:15:17 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Content-Length: 2
```
Run `npm run dev`, and go to `http://localhost:8443/healthcheck`. You should get a text "OK" response.
<details>
```
Version 1.1
Suite D4700 …
```
=> Add /healthcheck endpoint

src/components/VIcon/VIcon.vue, tailwind.config.js
Fixes #451 by @obulat
This PR adds a `safelist` array to the tailwind config to ensure that the common icon size class names are not purged in production. 
<details>
```
Version 1.1
Suite D4700
have the right to …
```
=> Safelist the classes for common icon sizes

src/components/VButton.vue, tailwind.config.js
Fixes #470 by @sarayourfriend 
Fixes button focus ring offsets. Adds a 0 and 1 value for the ring offsets to accomodate the button without interrupting existing usages of the 2px offset.
Run `npm run storybook` then visit `http://localhost:6006/?path=/story/components-vbutton--default` and focus the button with your keyboard and verify that the focus ring matches the designs linked in the attached issue.
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux …
```
=> Fix button ring offset

README.md, nuxt.config.js, package-lock.json, package.json, test/e2e/image-detail.spec.js, test/e2e/search.spec.js
Related to #472 by @krysal 
As the previous PR changes the image detail page route, here I add a redirect to avoid breaking the old links. It uses the `@nuxtjs/redirect-module` which internally uses a server middleware, so it should work as long as we don't switch from using SSR.
1. Manually go to any image page and try replacing `image` by `photos` in the URL, e.g.:
```
http://localhost:8443/photos/66003607-a201-40bd-8db6-601319de92ae
```
2. It should go to `http://localhost:8443/image/66003607-a201-40bd-8db6-601319de92ae` with a `301 Moved Permanently` status code and render the page normally.
<details>
```
Developer Certificate …
```
=> Redirect on image detail page

package-lock.json, package.json
Fixes #516 by @sarayourfriend 
Adds `ts-node` dependency that Storybook wants. That's it, there's nothing else necessary to fix the issue.
Checkout the branch and run `npm run storybook`. Verify that it starts like normal. Keep in mind there is another issue with Storybook preventing `mdx` stories from loading.
<details>
```
Version 1.1
Suite D4700
Everyone is …
```
=> Add ts-node to stop Storybook complaining about tsconfig.json

src/components/VMetaSearch/VMetaSearchForm.vue
Fixes #538 by @AetherUnbound 
This PR removes stray spaces introduced in the text due to the presence of newlines in the markup.
Search for a keyword that is unlikely to have any results.
<details>
```
Version 1.1
Suite D4700 …
```
=> Remove stray whitespace

.github/workflows/ci.yml, src/components/VMetaSearch/VMetaSearchForm.vue, test/e2e/content-types.spec.js
Part of #554 by @sarayourfriend 
Adds a step to run the e2e suite in the CI workflow. This isn't the ideal situation as it doesn't actually replicate the production environment because it doesn't have the wp.org wrapper. We can continue to explore a solution that accomodates that but for now this is better than nothing.
Let the CI run and verify that it works.
<details>
```
Version …
```
=> Add stop-gap solution for e2es

src/data/api-service.js, src/data/audio-service.js, src/data/image-service.js, src/data/report-service.js, src/locales/scripts/wp-locales.json, src/pages/audio/_id.vue, src/pages/image/_id.vue, test/e2e/content-types.spec.js, test/e2e/filters.spec.js, test/e2e/search.spec.js
Fixes #556 by @obulat
This PR adds trailing slashes to the old request URLs to avoid 301 redirects.
```
https://api.openverse.engineering/v1/images?q=cat[HTTP/2 301 Moved Permanently 579ms]
https://api.openverse.engineering/v1/images/?q=cat [HTTP/2 200 OK 288ms]
```
These changes are added to the `search`, 'single result pages' for image and audio, and the `thumbs` endpoints.
Run the app using `pnpm run dev`, and try searching or looking at the single result pages. You should not see any 301 redirects in the console.
<details>
```
Version 1.1 …
```
=> Update API urls to avoid redirects

src/components/VSearchGrid.vue, src/components/VSearchResultsTitle.vue, src/locales/scripts/wp-locales.json, test/unit/specs/components/v-search-results-title.spec.js
Fixes #576 by @zackkrida
Adds a super simple component to display the search term as an `<h1>` title on search result pages. Accepts a size prop to support the larger size used on the 'all' results page. Hidden on mobile but still accessible by screen readers.
Spacing for this component will be handled by it's parent; currently in the 'transitional' view the horizontal and vertical padding are incorrect. The line height however, is intentionally correct per the mockup.
View the 'all' and 'images' tabs, observe the visible title and size difference. Note that this component doesn't display on unsupported media types like video. 
<details> …
=> Search results title

src/components/AudioDetails/VAudioDetails.vue, src/components/AudioDetails/VAudioTags.vue, src/components/AudioDetails/VRelatedAudio.vue, src/pages/audio/_id.vue, test/unit/specs/components/related-audios.spec.js
Fixes #581 by @obulat
This PR
- renames the `.vue` files of `AudioDetails/` components to add the `VAudioDetails-` prefix
- matches the component names in the `name` field to the file name
- updates the usages of the components to the updated names to avoid the need of explicit imports
- 0. Checkout the branch and run the dev server.
- 0. Go to the audio detail page.
- 0. Verify that all components (`VAudioDetailsTable`, `VAudioDetailsTags`, `VAudioDetailsRelated`) are rendered as expected.
<details>
```
Version 1.1 …
```
=> Update names and references of `AudioDetails-` components

src/pages/search/audio.vue
According to the Figma mockups, the AudioTrack must be in the
- Row M layout when the [filters sidebar is closed](https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Openverse-Releases?node-id=133%3A43735)
- Row L layout when the [filters sidebar is open](https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Openverse-Releases?node-id=133%3A17711)
This PR fixes the layout sizes to match the mockups.
0. Checkout the PR and run the dev server.
1. Search for a term.
2. Switch over to the 'Audio' tab.
3. Toggle the filters sidebar.
- When the filter sidebar is closed, the layout should be Row M
- When the filter sidebar is open, the layout should be Row L
<details> …
=> Update the layout sizes to match Figma mockups

src/components/AudioDetails/VAudioDetails.vue
Fixes a small issue on the audio single result page where the display of the audio category was wrapped in a link to the audio set, which caused any track _without_ an audio set to fail.
- Visit an audio url like http://localhost:8443/audio/12d54947-85c3-4928-a7e1-0f4fb9594d0e and observe that the page fails to load without this change.
<details>
```
Version 1.1
Suite D4700 …
```
=> Audio fixes

src/components/ImageGrid/ImageGrid.vue, src/components/VAllResultsGrid/VAllResultsGrid.vue, src/components/VHeader/VHeader.vue, src/composables/use-load-more.js, src/pages/search.vue, src/pages/search/audio.vue, src/pages/search/image.vue, src/store/media.js, src/store/types.d.ts, src/utils/prepare-search-query-params.js, test/unit/specs/components/search-grid.spec.js, test/unit/specs/components/v-content-link.spec.js, test/unit/specs/store/media-store.spec.js, test/unit/specs/store/search-store.spec.js
Fixes #[issue number] by @[issue author]
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work …
```
=> Refactor fetching for all media

src/store/index.js
Just a quick devex fix.
Stops Vuex logging everything that happens making it difficult to view other more important logs.
If we want this in the future we should open an issue and figure out a way to make it easy to enable/disable (disabled by default) via a `.env` variable.
Checkout the branch and run `pnpm dev` and visit the site locally. Verify that vuex does not log everything that happens 🙂 
<details>
```
Version 1.1 …
```
=> Stop logging vuex stuff

src/components/VAudioTrack/layouts/VFullLayout.vue
Fixes #626  by @sarayourfriend 
Only use the `alt_files` array when it is present and do not automatically include the preview URL into the list of download formats.
This behavior could use some unit tests but I'm just fixing this in passing as I try to fix the audio keyboard stuff. If someone else wants to add unit tests for this behavior before merging then they are welcome, otherwise I think we can add them later on once we have multiple audio providers actually injested and are able to better hammer out the expected behavior (in case this for some reason doesn't work for other providers... in which case we're setting outselves up for a really complicated solution).
Checkout this branch and run `pnpm dev` and visit http://localhost:8443/audio/632d0076-fdbd-4919-8b8f-b498ef246ee8. …
=> Do not automatically include the preview URL into the list of download formats

src/components/VPill.vue, src/components/meta/VPill.stories.js
Fixes #630 by @panchovm
Adds a simple `VPill` component that creates the yellow pill for the BETA feature label. Currently has no props or anything but could easily be expanded in the future to include other background colors for different applications. Right now it can stay this simple though.
Necessary for further content switcher additions.
Checkout this branch and run `pnpm storybook` and visit http://localhost:6006/?path=/story/components-vpill--default.
<details>
``` …
```
=> Add VPill component

src/utils/env.js
Fixes #[issue number] by @[issue author]
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work …
```
=> Enable audio universally

src/components/AudioDetails/VAudioDetails.vue, src/components/VAudioThumbnail/VAudioThumbnail.vue, src/utils/math.js, src/utils/prng.js
Fixes #636 by @obulat 
This PR
- replaces the plain `<img>` with the `VAudioThumbnail` component capable of automatically falling back to generated artwork
- makes the artwork generation deterministic so that it remains the same in different appearances of the file
- removes the extra space above the media tags when audio does not have any associated description
0. Check out the branch and run the dev server.
1. Visit the page for an audio track without artwork.
2. See the generated art in the information section.
<details>
```
Version 1.1 …
```
=> Replace plain `<img>` tag with `VAudioThumbnail` component

src/composables/use-pages.js, src/locales/en.json, src/locales/po-files/openverse.pot
Fixes #650 by @zackkrida 
Adds a link to WP.org's privacy policy to the menu.
<details>
```
Version 1.1
Suite D4700
(b) The …
```
=> Add the privacy policy to the menu

src/components/VHeader/VPageMenu/VPageList.vue
Fixes #657 by @panchovm 
Adds a min-width of 200px to the pages menu dropdown.
<details>
```
Version 1.1
Suite D4700
(b) The …
```
=> Fix pages menu min width

src/components/VAudioTrack/VAudioTrack.vue
This PR uses prop-types as props
- to remove duplicated definitions
- prevent lint errors
- allow branches to pull `main` without having to commit these changes everytime
<details>
```
Version 1.1
Suite D4700
have …
```
=> Use `propTypes` as `props`

src/pages/search/audio.vue, test/e2e/content-types.spec.js
Fixes #668 by @obulat
This PR uses 's' layout for screens smaller than `md`. This layout doesn't show the audio track, which is shown at the bottom of the screen instead.
Run the app and search for audio on a narrow screen. You should not see a large play button.
<details>
```
Version 1.1
Suite D4700 …
```
=> Use 's' audio track layout for mobile

src/components/VButton.vue, src/components/VHeader/VFilterButton.vue
Fixes #675 by @panchovm
This PR adds a transparent border to the `pressed` variant of the button so that the width doesn't change.
Another small change added is default values for injected properties in Buttons. This enables us to use them even without provided values in Storybook.
Run the app and try clicking the Filter button in the header. There should be no jumping described in the linked issue.
<details>
```
Version 1.1
Suite D4700 …
```
=> Add a transparent border to filter button

src/pages/search/audio.vue
Fixes #674 by @panchovm 
This PR increases the separation between audio tracks to 40px on `md` and above, while using 32px on smaller devices.
0. Check out the branch and run the dev server.
1. Search for audio.
2. Observe the space between tracks to be 40px on `md` and above and 32px on `sm` and below.
<details>
```
Version 1.1
Suite D4700
Developer's Certificate of Origin …
```
=> Increase space between audio results

src/components/VAudioTrack/layouts/VRowLayout.vue
Fixes #672 by @zackkrida 
This PR
- reduces the space between different lines of the title
- increases the space below the artist name, accounting for the box around the timestamp
0. Check out the branch and run the Storybook.
1. In the story for the Row (small) layout, inspect the spaces using the Dev Tools.
<details>
```
Version 1.1
Suite D4700
Developer's Certificate of …
```
=> Fix spacing issues in the Row S layout

src/components/VFilters/VSearchGridFilter.vue
Fixes #676 by @panchovm 
This PR adds a padding to the text and reduces the margin. Combined, this does not affect the spacing but prevents the text from moving up and down when the 'Clear filters' button changes visibility.
https://user-images.githubusercontent.com/16580576/150627784-d78f860e-b504-4c91-8217-959a96529b0b.mov
<details>
```
Version 1.1
Suite D4700
Developer's …
```
=> Prevent vertical movement in filters

package.json
Installs are so fast in pnpm that adding an install step to our general development script will make it easier for developers to test PRs that introduce new dependencies without needing to explicitly install them manually. 
<details>
```
Version 1.1
Suite D4700
(a) The …
```
=> Add `pnpm install` to dev script

src/pages/about.vue, src/pages/audio/_id.vue, src/pages/extension.vue, src/pages/feedback.vue, src/pages/image/_id.vue, src/pages/meta-search.vue, src/pages/search-help.vue, src/pages/search/audio.vue, src/pages/search/image.vue, src/pages/search/index.vue, src/pages/sources.vue
This PR adds titles to all the Openverse pages, which will be passed up to the WordPress site using the message functionality.
0. Check out the branch and run the dev server.
1. Surf around Openverse (try to hit every different type of page) and observe the tab titles.
<details>
```
Version 1.1
Suite D4700 …
```
=> Add titles to pages

src/components/VContentSwitcher/VContentSwitcherPopover.vue
Fixes #686 by @dhruvkb
This PR sets a specific placement on the `VPopover` component to prevent it from switching between 'bottom-start' and 'bottom-end' out of its own volition.
0. Check out the PR and run the Storybook.
1. Visit the story for the VContentSwitcher.
2. Open the popover by clicking the button.
3. Reduce the height of the story slowly till zero by pulling up the drawer.
4. Observe no horizontal movement in the open popover.
<details>
```
Version 1.1
Suite D4700
Everyone is …
```
=> Prevent content switcher dropdown from shifting horizontally

src/components/ImageDetails/VPhotoDetails.vue, src/components/VPopover/VPopover.vue, src/components/VPopover/VPopoverContent.types.js, src/components/VPopover/VPopoverContent.vue
This PR uses the tailwind `z-` class to set z-index, makes the content report close button work, and adds `aria-label` to the report form popover.
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, …
```
=> Fix z-index close button

src/components/DropdownButton.vue, src/components/VAudioTrack/VAudioTrack.vue, src/components/VAudioTrack/VGlobalAudioTrack.vue, src/components/VAudioTrack/VWaveform.vue, src/components/VItemGroup/VItemGroup.vue, src/utils/key-codes.js
Fixes #402 by @sarayourfriend 
Allows toggling the audio playback using the spacebar when focused on the waveform.
Also fixes a minor visual bug where the vertical progress bar that shows when focused didn't keep up with the edge of background progress bar.
Could do some clean up and share the `handleToggle` function, but I'd rather put that off until these components settle and we know there aren't going to be minor differences between how global and local audio tracks need to handle this sort of thing.
Checkout the branch and visit audio search or audio result. Toggle playback on an audio track using the play/pause button and also by using the spacebar when focused on the waveform. Both should work as expected.
[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing- …
=> Allow toggling playback using spacebar from the waveform

src/components/VAudioTrack/layouts/VRowLayout.vue
Fixes #673 by @zackkrida 
This is a small PR to limit the audio track title to a single line on desktop and two lines on mobile, per the designs.
<details>
```
Version 1.1
Suite D4700 …
```
=> Truncate row layout audio titles

src/components/VMetaSearch/VMetaSearchForm.vue, src/utils/get-legacy-source-url.js, test/e2e/content-types.spec.js
Fixes #743 by @zackkrida
This PR removes Jamendo and Wikimedia Commons from Audio Meta search, because they are already in the main search.
Run the app, and search for audio. On the bottom of the page, you should not see Jamendo and Wikimedia Commons buttons for additional sources.
<details>
```
Version 1.1
Suite D4700
By making a …
```
=> Remove Jamendo and Wikimedia Commons from audio meta sources

src/utils/local.js
Fixes #762 by @sarayourfriend 
Changes `~/utils/local.js` to check `localStorage` isn't explicitly `null` to handle browser privacy settings.
Follow repro steps in the issue and verify that they're fixed.
<details>
```
Version 1.1
Suite D4700 …
```
=> Check for `null` localStorage explicitly

src/components/VHeader/VLogoButton.vue, src/components/VLogoLoader/VLogoLoader.types.js, src/components/VLogoLoader/VLogoLoader.vue, src/pages/index.vue
Fixes #687  by @dhruvkb 
Simplifies the VLogoButton implementation by using VButton for focus styles and also fixes the internal padding issues the VLogoButton was having.
Because this component is used across all pages, be sure to test it in all the following scenarios.
Checkout the branch and run `pnpm dev`. The visit and test the following pages, focusing on the logo button behavior and focus styles.
1. Homepage, large and small width viewports
2. Search page, large and small width viewports, scrolled and unscrolled
3. Single results page, large and small width viewports, scrolled and unscrolled
4. Information pages, large and small width viewports …
=> Fix logo button paddings and simplify implementation

src/components/VButton.vue
Fixes #766 by @sarayourfriend
The issue had the wrong diagnosis. It was just a styling error.
Open the content type switcher in the modal and verify that using keyboard to focus does not produce the double focus rings in the issue.
<details>
```
Version 1.1
Suite D4700
(a) The …
```
=> Fix double focus ring in item groups

src/components/VAllResultsGrid/VAllResultsGrid.vue, src/components/VContentLink/VContentLink.vue
Fixes #732  by @panchovm 
Fixes #778 by @zackkrida 
This PR:
- Centers vertically the "See all <media>" label 
- Uses the correct font size for the results text
- Removes the underline and pink color on hover
- Changes breakpoint to when it change from mobile to desktop layout as we're mainly using `md` and around the 1000px of width it was still showing the mobile version
- [-] I added or updated tests for the changes I made (if applicable).
<details>
```
Version 1.1
1 …
```
=> Adjust styles of `VContentLink`

nuxt.config.js, package.json
Fixes #820 by @sarayourfriend
Nuxt documentation about this change here: https://nuxtjs.org/docs/features/configuration#edit-host-and-port
Checkout the branch and run `pnpm dev` then visit the locally running site from another device like a mobile phone or another computer. It should work now. Also visit it at `localhost:8443` like we used to. That should also work.
<details>
```
Version 1.1
Suite D4700
license document, …
```
=> Allow local network access from other devices when in development

src/components/VAudioTrack/VWaveform.vue, src/mixins/iframe-height.js, src/pages/index.vue
Fixes #794 by @sarayourfriend 
Prevents ResizeObserver from being accessed if it does not exist. I don't think we need to polyfill it or anything in these cases and we can pretty gracefully degrade the experience when it's not around without hurting anything.
Do not try to test this on Firefox by disabling resize observer. It will completely destroy your Firefox personalized settings.
<details>
```
Version 1.1
Suite D4700 …
```
=> Fix unguarded `ResizeObserver` access

src/pages/index.vue
Fixes #769 by @zackkrida
This PR adds a check for search term before submitting a query from the search page. This prevents the user from getting to the blank `/search/` url.
Go to the homepage and click the search button. You should not be redirected, or see any changes.
<details>
```
Version 1.1
Suite D4700 …
```
=> Add a check for blank search term before searching

src/utils/local.js, tsconfig.json
Fixes #792  by @sarayourfriend 
Adds a `try/catch` in the `local` utility to guard against thrown errors when accessing `localStorage`.
Also adds `local.js` to type checking and updates the functions' APIs to match `localStorage` functions exactly.
I'm not sure how to cause the `SecurityError` from the sentry error.
I tried writing unit tests for this module but forcing `localStorage` functions to do anything is nearly impossible with how JSDom implements it.
<details>
```
Version 1.1
Suite D4700
San Francisco, CA, …
```
=> Guard `local` util against thrown errors

src/composables/use-active-audio.js, src/composables/use-filter-sidebar-visibility.js, src/composables/use-window-scroll.js
Just adding a little documentation around the existing global refs.
N/A, just adding comments
<details>
```
Version 1.1
Suite D4700 …
```
=> Document global ref SSR safety

src/components/VHeader/VSearchBar/VSearchBar.vue, src/pages/index.vue, test/unit/specs/components/VHeader/SearchBar/search-bar.spec.js
Fixes #644 by @zackkrida 
Adds a default placeholder text for the search bar.
Unit tests should pass. You can also check the search routes for good measure and they should have the placeholder text now. The `/404` page should still have it's own custom placeholder text.
<details>
```
Version 1.1
Suite D4700 …
```
=> Add default placeholder for VSearchBar

src/components/VButton.vue
This is a workaround for a development-only bug wherein CSS file order is incorrect.
Fixes #[issue number] by @[issue author]
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the open source …
```
=> Duplicate button classnames for increased specificity

src/styles/utilities/derived-variables.scss, src/styles/utilities/initial-variables.scss
Fixes #708 by @panchovm 
This PR makes a simple replacement of the incorrect gray `#333`/`rgb(51,51,51)` with the correct color `#30272e`. This small PR is meant to be a temporary solution until #823 lands.
<details>
```
Version 1.1
Suite D4700 …
```
=> Fix text colors

src/components/AudioDetails/VAudioDetails.vue, src/components/VImageDetails/VImageDetails.vue, src/components/VMediaTag/VMediaTag.vue, src/components/VMediaTag/meta/VMediaTag.stories.mdx, test/unit/specs/components/VMediaTag/v-media-tag.spec.js
Fixes #742 by @panchovm
- Updates the component name with the `V` prefix and its references and changes the default HTML tag to `span`as indicated in the code comment
- Applies text styles of `caption bold` to tags
- Adjust horizontal padding on desktop
Run the project and see the details page of any image with tags, observe if styles matches Figma mockups [[mobile](https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Openverse-Releases?node-id=958%3A19663), [desktop](https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Openverse-Releases?node-id=1228%3A21557)]
<details>
```
Version 1.1
Copyright (C) 2004, …
```
=> Add tags in image single result page

nuxt.config.js
If you're in development and just want to _try_ something that ESLint doesn't like, it adds an overlay that prevents you from using the app.
ESLint is useful from preventing production bugs, but it's absolutely awful to fight it just to debug something (like adding an early return and causing "unreachable code" temporarily, or commenting out a function call that results in an unused variable, etc).
We have two (probably three for most people) places where linting is already running:
1. pre-commit hook
2. In CI
3. Probably your editor
Making it fail development builds is not necessary with these other checks in place and only hinders local development/makes it frustrating.
Checkout this branch and run `pnpm dev`. Add something that ESLint will not like, like an unused variable in a .vue …
=> Disable friendly errors overlay

src/components/VContentSwitcher/VContentItem.vue, src/components/VContentSwitcher/VContentTypes.vue, src/components/VItemGroup/VItem.vue
Related to #639 by @panchovm
This PR improves the paddings for the Content Switcher component to match the Figma mockups that were broken by some unrelated changes.
The focus ring for the medium size of the switcher component is still different from the mockups: inside the gray area instead of around it.
<details>
```
Version 1.1
Suite D4700
Developer's Certificate of Origin …
```
=> Remove excessive padding from VContentItem

CONTRIBUTING.md
We just use `goal: fix` now. Ideally the `bug` label wouldn't even exist.
N/A, just updating markdown
<details>
```
Version 1.1
Suite D4700 …
```
=> Remove outdated labelling instructions

.lintstagedrc
This is a quick PR that adds TS files to the scope of the lint hooks. Without it, type definitions files are not linted locally and thus break CI after the push eg. [61945b9](https://github.com/WordPress/openverse-frontend/pull/906/commits/61945b9e87f929823cb72b5e39eeb1ef51f86fd3)
0. Check out the PR.
1. Make some anti-lint changes to a TS file.
2. Try to commit. The hook should prevent the commit.
<details>
```
Version 1.1
Suite D4700 …
```
=> Lint TS files in Git hooks

src/pages/index.vue
Fixes #801 by @ad-mk
Remove the z-index. It's not necessary. Not sure why it was added in the first place, potentially just a copy/paste issue or a programming error.
Note: it'd be nice to dissuade people from adding z-indexes to things OR switch to a z-index token system like Gutenberg uses instead of generic number based indexes. That way you can organize the proper ordering of elements that actually should have z-indexes in one place instead of trying to coordinate all the usages of the generic z-[n] utility all across the app.
Follow the reproduction steps in the issue and verify that they are no longer able to be reproduced. …
=> Remove z-index from brand blocking search type switcher

src/composables/use-storage.js
Fixes #994 by @sarayourfriend 
Creates a new private function, `useSafeDefaultOptions` that catches errors safely.
Follow the reproduction instructions in the issue and verify you can reproduce the issue in staging. Then checkout and run this branch with `pnpm dev` and verify that the app no longer crashes.
<details>
```
Version 1.1
Suite D4700
Developer's Certificate of …
```
=> Remove unguarded localStorage access

test/tapes/response-49.json5
This PR adds a missing tape to fix e2e errors in CI.
The problem seems to be that the test is looking for creativecommons as the referrer (migration banner), but the response we get (from the `talkback` proxy that is set to `recordMode.DISABLED`) sets the referrer to localhost.
Run e2e tests on the main branch, using `pnpm run ci:e2e-test`, and see that it fails. Then checkout this branch and run the same command. It should pass.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to …
```
=> Add the missing tape that causes e2e errors

src/composables/use-browser-detection.js, src/plugins/ua-parse.js, typings/nuxt__types/index.d.ts
Fixes #903  by @obulat 
explicitly declared the userAgent type as string 
Converted the `context.req.headers['user-agent']` and `navigator.userAgent` to string type. 
This will make sure the `user.parse(userAgent)`  always gets a string value as an argument.
`
<details>
```
Version 1.1
Suite D4700 …
```
=> handling null and undefined value for userAgent

src/components/VAudioTrack/layouts/VBoxLayout.vue, src/components/VContentSwitcher/VSearchTypeItem.vue, src/components/VHeader/VPageMenu/VPageList.vue, src/styles/base/generic.sass, src/styles/tailwind.css
Fixes #1094 by @zackkrida
Moves the default values for typography into the main tailwind.css file and deletes the corresponding sass. If this is working correctly, the site should look identical everywhere.
<details>
```
Version 1.1
Suite D4700 …
```
=> Move typography defaults into `tailwind.css` file

src/components/CopyButton.vue, src/components/ExtensionBrowsers.vue, src/components/VAllResultsGrid/VImageCellSquare.vue, src/components/VAudioDetails/VRelatedAudio.vue, src/components/VAudioTrack/VAudioTrack.vue, src/components/VAudioTrack/VGlobalAudioTrack.vue, src/components/VBackToSearchResultsLink.vue, src/components/VContentLink/VContentLink.vue, src/components/VContentReport/VContentReportPopover.vue, src/components/VContentSwitcher/VSearchTypeButton.vue, src/components/VContentSwitcher/VSearchTypeItem.vue, src/components/VContentSwitcher/VSearchTypes.vue, src/components/VErrorSection/VErrorSection.vue, src/components/VFourOhFour.vue, src/components/VHeader/VHeaderFilter.vue, src/components/VImageGrid/VImageGrid.vue, src/components/VMediaInfo/VCopyLicense.vue, src/layouts/blank.vue, src/layouts/default.vue, src/pages/search/audio.vue, src/pages/search/image.vue
Fixes more warnings :)
And hopefully, makes other PR reviews easier.
This PR adds the missing component imports, and removes some extra lines between the imports in the same group (e.g., between two component imports).
This doesn't affect the running of the code because the components are auto-imported if no import statement is there. However, the tests usually display a warning without it.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim copies of …
```
=> Add component imports, remove extra blank lines between imports

src/utils/get-legacy-source-url.js, test/e2e/search-types.spec.js
Fixes #1067 by @zackkrida 
Adds Centre for Ageing to meta search for images.
<details>
```
Version 1.1
Suite D4700
(b) The …
```
=> Add Centre for Ageing to image meta search

src/components/VIconButton/VIconButton.vue
Fixes #1005  by @zackkrida 
Removed the unnecessary `focus : `classes in VIconButton.vue which was implemented on top of the `focus-visible : ` class in VButton.vue. Which might have been causing the issue.
<details>
```
Version 1.1
Suite D4700 …
```
=> removing all the ' focus: ' classes from VIconButton.vue

package.json, pnpm-lock.yaml
Fixes #1105 by @sarayourfriend 
This PR removes the `findindex` package from `package-json` and the lock file. All the usages of `lodash.findindex` have already been replaced in the code.
Passing CI should be enough.
<details>
```
Version 1.1
Suite D4700 …
```
=> Remove lodash.findindex from dependencies

src/utils/sentry-config.ts
Fixes #1145  by @sarayourfriend 
Adds filters client side for Sentry so we stop getting some of the nonsense errors that still get through.
We can continue to expand this list.
There's no way to test this locally really.
<details>
```
Version 1.1
Suite D4700 …
```
=> Strictly filter sentry errors

CONTRIBUTING.md, package.json, pnpm-lock.yaml, src/components/VLink.vue, tsconfig.json
Adds support for TypeScript in Vue SFCs.
Notable changes:
* Usage of `vue-tsc` and addition of some modules that Vue 2 doesn't automatically pull in necessary for template types
* Applied fixes from https://github.com/johnsoncodehk/volar/discussions/592 due to Storybook pulling `@types/react` into the chain causing templates to have the incorrect types applied to them by TypeScript compiler
I chose a simple `VLink` component to be the test candidate.
Checkout this branch and make changes in VLink and run `pnpm types` test compilation.
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux …
```
=> Add support for TypeScript in Vue SFCs.

src/pages/sources.vue
Fixes #1008 by @krysal 
Removes the links on the sources name in the source table on the `/sources/` route.
Visit `/sources/` and observe there are no permalinks on the source names.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part by me …
```
=> Remove source links from sources page

.gitignore, README.md, TESTING_GUIDELINES.md, nuxt.config.ts, package.json
Fixes #1143 by @zackkrida 
Adds instructions for generating an SSL certificate locally and setting up a local certificate authority. Also adds a new local development command to use the certificates, and adds generated certificates to the `.gitignore` file.
Follow the README instructions to generate a certificate and run `pnpm dev:secure`.
<details>
```
Version 1.1
Suite D4700 …
```
=> Enable HTTPS in local development

src/components/VAudioTrack/VPlayPause.vue, src/components/VIconButton/VIconButton.vue
Fixes #1110 by @sarayourfriend 
FIxes the play pause button outline placement as suggested by @sarayourfriend 
SIDE NOTE -> I had already submitted this PR but I had to delete my forked repo because I had by mistake messed up the main branch in that repo, sorry, won't happen again. This caused my previous PR to auto-close.
<details>
```
Version 1.1
Suite D4700
Developer's …
```
=> fix focus outline placement button

src/components/VContentSwitcher/VSearchTypes.vue, src/constants/media.ts, src/locales/po-files/openverse.pot
This PR
- reduces code duplication using groups
- resolves conflicts between #1190 and #1203
<details>
```
Version 1.1
Suite D4700 …
```
=> Resolve conflicts between 3D models PRs

src/components/VErrorSection/meta/VErrorSection.stories.mdx
Related to #1135 by @dhruvkb 
Small fix for the VErrorSection stories that converts them to the Composition API format. This PR is based on @dhruvkb 's `fix_stories` branch. Feel free to change/merge it as you see fit, @dhruvkb .
<details>
```
Version 1.1
Suite D4700
(a) The …
```
=> Fix VErrorSection stories

tsconfig.json, typings/nuxt__types/index.d.ts
Add's missing pinia types to the tsconfig global `types` list.
cc @obulat 
<details>
```
Version 1.1
Suite D4700 …
```
=> Fix missing pinia types

package.json
In #1207, the command for building Storybook was mistyped with `--`. This PR removes the hyphens to allow Storybook to be built again.
0. Check out this PR.
1. Run `pnpm storybook:build`.
<details>
```
Version 1.1
Suite D4700 …
```
=> Fix command for building Storybook

src/layouts/blank.vue, src/layouts/default.vue, src/middleware/middleware.ts, src/plugins/migration-notice.ts, src/plugins/url-change.ts, src/stores/nav.ts, src/stores/navigation.ts, test/unit/specs/stores/nav-store.spec.js
Fixes #1254 by @obulat
This is the last store that needed to be converted from a Pinia setup store to an options store. 
`active-media` store can also be converted, but because it's not used in server-rendered pages, it's not necessary.
<details>
```
Version 1.1
Suite D4700
(a) …
```
=> Convert nav store to an options store

.eslintrc.js, .lintstagedrc, .storybook/.eslintrc.js
Fixes #1160 by @sarayourfriend 
(But also mostly @krysal change to add --max-warnings=0 ultimately addresses the main issue).
Upgrades all the things set to warning in our eslint to error. We control these, so they might as well give actual errors.
Also fixes the storybook directory's eslintrc extension that wasn't actually extending the config (doh!)
CI passes.
<details>
```
Version 1.1 …
```
=> Upgrade all warnings to errors that we control

src/components/VScrollButton.vue, src/layouts/default.vue, src/pages/search.vue
Related to #1257 by @zackkrida 
Here I add a few changes to complete Zack's PR. On mobile, the size of the page was bigger than the viewport in the search page of images or audio, so we have to change the between `w-screen` and `w-full` to prevent a horizontal scroll.
This PR:
- applies required changes by @obulat to the `VScrollButton`
- removes the horizontal scroll that appeared when changing the content type to images or audio on the search page.
Run the project locally, do a search that returns results for both images and audio, like `coffee`, and change between types, open/close the filter sidebar. Compare this branch with `layout-fixes`.
<details> …
=> Complement to app layout issues

src/composables/use-body-scroll-lock.ts, src/composables/use-event-listener-outside.js, src/composables/use-focus-on-blur.js, src/composables/use-hide-on-click-outside.js, src/utils/dom/get-document.ts
Fixes #945 by @sarayourfriend 
This PR converts the `use-body-scroll-lock` composable to TS. It also copies the code from the `reakit-utils` into `/utils` directory to avoid contaminating our types with React types in the future.
CI should be green, and there should be no problems with locking scroll in the app.
<details>
```
Version 1.1
Suite D4700
Developer's Certificate …
```
=> TS-ify use-body-scroll-lock composable

src/components/VAudioTrack/VGlobalAudioTrack.vue, src/components/VGlobalAudioSection/VGlobalAudioSection.vue, tsconfig.json
Fixes #1157 by @sarayourfriend
Fixes #775 by @sarayourfriend 
This PR branch is based on the `ts_vwaveform` branch (#1311), so should be merged after that PR.
The main fix of this PR is to set `activeAudio` obj value to undefined when the `Close` button is clicked on the Global Audio Player, in addition to ejecting active media item in the active media store. This ensures that the audio playback is stopped when the player is closed.
Other changes include converting the `VGlobalAudioSection` to TS, and simplifying `VGlobalAudioTrack` by removing the unnecessary layout computations and size prop (this can be re-added should we decide to use the global audio player on layouts other than mobile.
Search for audio in the Audio view on mobile screen (http://localhost:8443/search/audio?q=cat), …
=> Stop playing audio when global player is closed

.github/workflows/bundle_size.yml, nuxt.config.ts
Fixes #567 by @sarayourfriend 
Uses the example from Gutenberg and uses the preact action used there as well. Hopefully it works :grin: 
Update: it works!
Note that the list of files in this PR is going to be super long because I've also changed how the bundle names are generated.
Maybe we could actually only change the way the bundle names are generated during this specific build by passing an environment variable or something. What do y'all think about that? Then we wouldn't have to worry about hashes changing at all, we'd just see names 1:1? I'll try it out and see if it works.
Check out the new workflow and confirm that it is working :tada: 
<details> …
=> Add bundle size reporting to PRs

src/models/media.ts, src/utils/attribution-html.ts, test/unit/specs/utils/attribution-html.spec.ts
Fixes #1353 by @krysal 
This PR addresses the stray "by" that appears when the creator of a media is not known. It adds the corresponding test case and updates the type `Media` to account for such a case.
You will no longer be able to reproduce #1353 on this branch.
<details>
```
Version 1.1
Suite D4700 …
```
=> Handle unknown creator in attribution

.github/workflows/ci.yml, .github/workflows/gh-pages.yaml, .github/workflows/pr_closed.yml
Fixes #1326 by @sarayourfriend 
Deploys Storybook and Tailwind previews to GitHub pages for each PR in a subdirectory on GitHub pages.
Not sure really how to test it, but you can see it worked on this PR :slightly_smiling_face: 
We will need to verify that the clean up step actually works after this is merged. The goal there is to prevent our `gh-pages` branch from becoming stuffed with tons of old no-longer-relevant JavaScript.
<details>
``` …
```
=> Try publishing Storybook/Tailwind config previews per PR

.github/renovate.json
Related to #1357 by @renovate-bot 
As agreed in the linked PR, we don't want to pin deps in the `package.json` so here disables it by instructions mentioned there.
<details>
```
Version 1.1
Suite D4700
have the right …
```
=> Prevent renovatebot from pinning dependencies

.github/workflows/ghcr.yml
Currently our images are only pushed to ECR, which isn't public. This PR builds and pushes images for all PRs and for the main branch to GHCR which is public.
Check that the CI works. Confirm on this page: https://github.com/WordPress/openverse-frontend/pkgs/container/openverse-frontend
Pushing to `main` should add the `latest` tag automatically through the metadata action.
<details>
``` …
```
=> Publish branch and main images to ghcr

package.json, pnpm-lock.yaml, src/components/VSourcesTable.vue, test/unit/specs/components/v-modal.spec.js, test/unit/specs/components/v-sources-table.spec.js
Fixes #1108 by @sarayourfriend 
Fixes #1388 by @krysal
This PR completes the **Remove lodash** milestone by replacing `lodash.sortby` with `Array.prototype.sort` as Sara suggested. There is still a `lodash.isempty` dependency that I'm not sure if it can be safely removed, doesn't seem to be used anywhere.
Also fixes the sorting of the Sources table, something I noticed while working in the first issue :)
Reproduce steps in #1388 and see URLs correctly sorted.
<details>
```
Version 1.1 …
```
=> Replace `lodash.sortby` and fix sources table ordering by url

src/components/VHeader/VHeader.vue
Fixes #1367 by @obulat 
Removes the focus on the search bar after submitting a search.
This is done by adding a simple `document.activeElement?.blur()` after the search is done.
Navigate to a search result page, and try searching for something else through the header. After submitting with the `Enter` key or the search button on keyboard (if mobile), the search field should no longer be focused.
<details>
```
Version 1.1
Suite D4700 …
```
=> Remove focus on SearchBar after submit

.github/actions/build/action.yml
Fixes #[issue number] by @[issue author]
Add `shell` to build action
<details>
```
Version 1.1
Suite D4700
(b) The contribution is …
```
=> Try fixing build action

.github/workflows/bundle_size.yml, .github/workflows/ci.yml, .github/workflows/gh-pages.yaml, .github/workflows/ghcr.yml
This PR updates the following actions to not run on forks:
- GHCR deploys
- bundle size reporting
- Preview builds deployed to GH pages
It also updates the following action to run on forks:
- Build deployed to GH pages
Cannot tests actions without merging PR and waiting for situation to emerge.
<details>
```
Version 1.1
Suite D4700
By …
```
=> Update actions for forks vs main repo

.github/renovate.json
Files included in this change are synced from [WordPress](https://github.com/WordPress/openverse/tree/main/.github/workflows)/[openverse](https://github.com/WordPress/openverse/tree/main/.github/workflows_downstream), so we don't Renovate to update them here but in the parent repo.
Reference: [Configuration Options Docs](https://docs.renovatebot.com/configuration-options/#ignorepaths).
Just see once it's merged no more renovate PRs will be triggered for these files (?)
<details>
```
Version 1.1
Suite D4700
San …
```
=> Ignore workflow files in Renovate

.github/workflows/ghcr.yml
Currently we're only pushing SHA tags to the openverse-frontend image repository. This should add at least the `main` branch `main` tag when we push to main.
Merge it and see if it works :confused: 
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and …
```
=> Tag images built for main with main

src/locales/po-files/openverse.pot, src/pages/audio/_id.vue, src/pages/image/_id.vue, src/utils/og.ts
Fixes #1441 by @zackkrida
This PR extracts the creation of the head meta object for the media details page and adds a thumbnail to audio `og:image` if available.
Open an audio details page (http://localhost:8443/audio/2ecd5631-c48c-4a5f-89c4-83c44dbbd365) and look at the HTML <head> element. You should see the following element (in the end of many lines of `meta`s):
`<meta data-n-head="ssr" data-hid="og:image" name="og:image" content="https://api.openverse.engineering/v1/audio/2ecd5631-c48c-4a5f-89c4-83c44dbbd365/thumb/">`
<details>
```
Version 1.1 …
```
=> Add OG image for audio detail page

src/components/VMediaInfo/VCopyLicense.vue, src/components/VMediaInfo/VLicenseTabPanel.vue, src/components/VTabs/VTab.vue, src/components/VTabs/VTabPanel.vue, src/components/VTabs/VTabs.vue, src/models/tabs.ts, test/unit/specs/components/v-tabs.spec.js
Fixes #1425 by @panchovm
This PR uses the required `tab` prop to link VTab to VPanel and to make sure that the selected tabpanel is set correctly. Now, it is required to use the same `id` for the VTab and VPanel that are linked.
Merge and see...
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, I certify …
```
=> Try fixing the tabs by using the id prop

.github/workflows/renovate.yml
We depend on a `.pnpmfile.cjs` to modify TypeScript version resolution in our `pnpm-lock.yaml` to force the `@nuxt/typescript-build` module we use for TS on Nuxt 2 to use an up-to-date version of TypeScript.
Managed renovate does not allow running pnpm scripts to reduce the attack surface: https://github.com/renovatebot/renovate/discussions/11250
For that reason, we can't actually use managed renovate. Instead, we can try to use the github action which runs the Renovate CLI on a cron schedule (in this configuration, every 15 minutes). This will be less responsive with things like checking the rebase box on PRs, but that should be okay for us. We can be patient :) 
Not sure. I guess we have to merge, wait for a 15 minute interval to come around and see if it works :grin: Presumably we …
=> Add renovate cron workflow

src/components/VHeader/VHeader.vue, src/components/VHeader/VSearchBar/VSearchBar.vue, src/locales/en.json, src/locales/po-files/openverse.pot, src/pages/sources.vue, test/playwright/e2e/search.spec.ts
Fixes #1455 by @stacimc / @panchovm 
As indicated it adds the expected scroll, and also fix a console warning in the sources page about duplicated keys.
See the linked issue.
<details>
```
Version 1.1
Suite D4700 …
```
=> Scroll to top after submit a new search

.github/renovate.json, .github/workflows/renovate.yml
I realized that I hadn't followed up on this since I originally merged the workflow. It appeared to be failing due to bad configuration, so I re-read the documentation and tried again. Hopefully it works this time.
Merge and see how it goes.
<details>
```
Version 1.1
Suite D4700 …
```
=> Fix the self-hosted config and secret for renovate cron

src/components/VAudioTrack/layouts/VGlobalLayout.vue
Fixes #1469 by @zackkrida 
Adding a new tailwind class text-dark-charcoal to change the color of the global audio player
- [ x I added or updated tests for the changes I made (if applicable).
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in …
```
=> Add tailwind black text color

.github/workflows/frontend_deploy.yml
Fixes the failure when I tried to run the action described here: https://github.com/WordPress/openverse-frontend/runs/6791104169?check_suite_focus=true
Merge and :crossed_fingers: 
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part by me and …
```
=> Checkout before trying deploy

src/components/VAudioTrack/layouts/VFullLayout.vue, src/pages/audio/_id.vue
Fixes #1478 by @obulat 
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, to the best
of …
```
=> prevent padding to drop to 0 on large screen on audio detail view

.github/actions/frontend-deploy/action.yml, .github/workflows/frontend_deploy.yml
I'm modifying the composite action here and then will backport the fixes to the template in the infrastructure repository where it is generated once it's fixed.
See if it works on this branch, remove the testing code, then merge and hope it also works on main.
Update: it worked! https://github.com/WordPress/openverse-frontend/runs/6828684979?check_suite_focus=true
Confirmed in AWS that the service did indeed redeploy with the new task definition and reached a steady state :tada: 
<details>
```
Developer …
```
=> Remove secrets and fix shell step in task definition redeploy

src/components/VContentSwitcher/VMobileMenuModal.vue, src/components/VContentSwitcher/VSearchTypeItem.vue, src/components/VContentSwitcher/VSearchTypeRadio.vue, src/components/VContentSwitcher/VSearchTypes.vue, src/components/VHeader/VHeaderMenu.vue, src/components/VHeader/VPageMenu/VDesktopPageMenu.vue, src/components/VHeader/VPageMenu/VMobilePageMenu.vue, src/components/VHeader/VPageMenu/VPageList.vue, src/components/VHeader/VPageMenu/VPageMenuButton.vue, src/components/VHeader/VSearchBar/VSearchButton.vue
Related to Typescriptification milestone
This PR is extracted from #1405 to make it easier to review. 
It adds `defineComponent`, sets the language to `ts`, documents `emits`, and replaces JSDoc comments with TS annotations for the ContentSwitcher and the Header components.
Passing CI should be enough. Can also check that the ContentSwitcher and Header work as usual, without warnings.
<details>
```
Version 1.1
Suite D4700 …
```
=> Use TS and defineComponent in the ContentSwitcher and Header

.github/actions/setup-node-env/action.yml, .github/workflows-disabled/sentry-release.yml, .github/workflows/bundle_size.yml, .github/workflows/ci.yml, .github/workflows/gh-pages.yaml, .github/workflows/ghcr.yml, .github/workflows/push_production.yaml, .github/workflows/push_staging.yaml
This PR updates the `actions/checkout` and `actions/cache` to version 3. This matches the `WordPress/openverse` repository versions.
There's been several failed CI runs that _might_ be fixed with new versions of actions.
Here's the error message from a [failed run](https://github.com/WordPress/openverse-frontend/runs/6704753273?check_suite_focus=true):
```
0s
Prepare all required actions
Getting action download info
Download action repository 'pnpm/action-setup@v2.2.1' (SHA:35ab4267a1a21c8e8cb1c087cf1642e891ff57bd)
Download action repository 'actions/cache@v2' (SHA:937d24475381cd9c75ae6db12cb4e79714b926ed)
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_3970bc0e-5855-4c61-8d0c-c000a0cabf66/6bfcb81c-e3a5-433f-9f76-5889389768ef.tar.gz. return code: 2.
``` …
=> Update the GH actions versions to match openverse repo

.github/workflows/ci.yml, .github/workflows/ghcr.yml
We observed that certain jobs fail on PRs from forks. That's because of certain permission issues. We tried to prevent these jobs from running but the `if` condition wasn't working.
This PR updates the `if` condition to something that should work to prevent these jobs from running.
GitHub Actions are hard to test. The most we can do is a thorough code read.
<details>
```
Version 1.1
Suite D4700
license document, but …
```
=> Update conditions to not run certain jobs for PRs from forks

src/components/VAudioDetails/VAudioDetails.vue, src/models/media.ts, test/unit/specs/components/VAudioDetails/v-audio-details.spec.js
Fixes #1544 by @krysal
Also changes the link to the `foreign_landing_url` as `url` goes to the cover image.
See in the linked issue.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part …
```
=> Show album title on audio details page

.github/renovate.json
Part of #1514 by @sarayourfriend 
See https://github.com/WordPress/openverse-frontend/issues/1514#issuecomment-1169516049 for rationalization of just disabling renovate for now at least.
N/A
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute …
```
=> Ignore package.json from renovate

src/components/VImageGrid/VImageGrid.vue
Noticed this minor issue while reviewing https://github.com/WordPress/openverse-frontend/pull/1540 and playing around with the extensions filters. If you toggle filters quickly or hit an uncached query you'll notice images slowly fill their way into the results instead of immediately updating as soon as the results have come back.
Intuitively this change makes sense and we probably should have been doing this all along. It does indeed fix the issue but strangely not _completely_. I still notice some images lingering behind when quickly toggling filters on then off again.
Checkout the branch and run the app locally with `pnpm dev`. Visit the app at `localhost:8443/images?q=birds&extension=png`. Quickly toggle on then off again the JPEG filter and note the difference in behavior in filling …
=> Use image id for key to prevent weird reordering when toggling filters

.github/workflows/rollback.yml
https://github.com/WordPress/openverse-frontend/runs/7304407532?check_suite_focus=true
We were checking the version names, not the container tags, which apparently are different.
Tested in this branch, you can see the successful run here with the matching code for a specific tag: https://github.com/WordPress/openverse-frontend/runs/7304652269?check_suite_focus=true
<details>
```
Version 1.1
1 Letterman …
```
=> Fix rollback tag check

src/components/VAudioTrack/VAudioTrack.vue, src/components/VAudioTrack/VPlayPause.vue, src/constants/audio.ts, test/playwright/e2e/all-results-keyboard.spec.ts, test/playwright/utils/audio.ts
Fixes #1567  by @sarayourfriend 
Refactors the audio keyboard accessibility tests to account for the loading state. I'm surprised this wasn't an issue earlier.
This appears to have fixed the flakiness of the tests :crossed_fingers: 
`pnpm test:playwright` and confirm none fail. Also confirm CI for the same passes.
<details>
```
Version 1.1
Suite D4700
license …
```
=> Fix flaky audio a11y tests

.github/workflows/rollback.yml
https://github.com/WordPress/openverse-frontend/actions/runs/2658884996
I got the path wrong :facepalm: 
Merge and see it work.
<details>
```
Version 1.1
Suite D4700
license document, but changing it is …
```
=> Fix deploy action path

src/utils/sentry-config.ts
Fixes https://sentry.io/share/issue/3b37a4a56ac34b928aee4cde2fe9ce11/
Ignore these errors because they only happen locally.
We should probably just remove the Sentry DSN from the repository so that these kinds of errors never reach Sentry unless someone is paying attention to them and ready to remove them from the triage list.
N/A
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute …
```
=> Ignore local only errors that do not matter

src/components/VAudioTrack/VAudioTrack.vue
Fixes #1622 by @obulat
This PR renames `_size` property to `layoutSize` to prevent the errors described in the linked issue.
CI should pass, and the Audio tracks should work well. The actual error caused by the `underscore` in the property name is only shown in Vue v.2.7.
<details>
```
Version 1.1
Suite D4700 …
```
=> Rename _size to layoutSize to remove underscore

.github/workflows/rollback.yml
Fixes #1623 by @sarayourfriend 
Paginates through the image versions instead of relying just on the first page of 30 results.
Merge and try to re-deploy production to v3.4.2 (which is not previously on the first page).
<details>
```
Version 1.1
Suite D4700
Everyone is …
```
=> Check paginated versions during Rollback version check

test/playwright/utils/navigation.ts
Fixes #1612 by @ramadanomar 
Fixed the branch issues with my fork. See pr #1636 for more details.
Imports ar.json from the test directory as suggested by  @sarayourfriend in pull req #1636 .
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part …
```
=> Fixes missing ar.json file.

README.md
Fixes #1662 by @ramadanomar
The handbook hyperlink under the banner leads you to a page that doesn't exist. I already created an issue on the openverse-catalog repo but it applies to all openverse repos. 
<details>
```
Version 1.1
Suite D4700 …
```
=> Updates handbook broken link

package.json
Fixes #1654 by @obulat
This PR removes the extraneous `--` present in the script. This fixes the complaint `ESLint` raises.
0. Checkout out the branch.
1. Run `pnpm lint:fix`. 
2. Observe that error is not raised.
**Before:** See the extra `"--"` before `"--fix"`.
**After:**
<details>
```
Version 1.1
Suite D4700
By making a contribution …
```
=> Remove extraneous `--` from `lint:fix` script

src/components/VAudioTrack/VPlayPause.vue
Related To #1600 by @sarayourfriend 
See pr #1639 for more details.
Fixed the console error when you pause an audio before it loads
This fix should stop a user from being able to pause a file before it loads. Am not sure if this is the right way to approach such problem. Would love to get some feedback!
<details>
```
Version 1.1
Suite D4700
Developer's Certificate of Origin …
```
=> Avoid pausing audio when is loading

src/pages/extension.vue, src/pages/sources.vue
Fixes #1617 & #1618 by @obulat
See pr #1638 for more details.
Fixed heading order while maintaing css style according to figma document
go to /sources and /extension pages
<details>
```
Version 1.1
Suite D4700
have …
```
=> Heading order & formating fixed

package.json, pnpm-lock.yaml
Fixes #1610 by @sarayourfriend
Changes sentry to the latest version
<details>
```
Version 1.1
Suite D4700
(b) The contribution is …
```
=> Sentry package update

.github/actions/production-frontend-deploy/action.yml, .github/actions/staging-frontend-deploy/action.yml
Updates the workflows to fix task definition registration going to the wrong family. Just moving these down from the infrastructure repository where they were generated.
Merge and force deploy staging and verify that the task definition is registered to the correct family.
<details>
```
Version 1.1 …
```
=> Update deployment actions to fix task definition registration

DEPLOYMENT.md
Part of my ongoing work to improve documentation for our infrastructure.
Read the new document and let me know if it needs more information or if anything doesn't make sense or is unclear.
<details>
```
Version 1.1
Suite D4700
license document, but changing it is …
```
=> Add DEPLOYMENT.md

.github/actions/production-frontend-deploy/action.yml, .github/actions/staging-frontend-deploy/action.yml
https://github.com/WordPress/openverse-frontend/actions/runs/2882954383
I was not using `sed` correctly. If you `sed` a file and stream it to the same file, you end up with an empty file:
```shell
➜  ~ echo "Here's a test file, friend-o" > test-file.txt
➜  ~ sed 's/friend-o/best friend/g' test-file.txt > test-file.txt
➜  ~ cat test-file.txt
➜  ~ echo "Here's a test file, friend-o" > test-file.txt         
➜  ~ sed -i 's/friend-o/best friend/g' test-file.txt         
➜  ~ cat test-file.txt
Here's a test file, best friend
```
There are no lines missing there, the first `cat test-file.txt` is an empty response. The `-i` flag enables `sed` to edit the file "in place". Apparently it actually streams to a temporary file and then renames it after the operation is done. In any case, it works for …
=> Fix sed usage

.github/workflows/bundle_size.yml
Fixes #1380 by @zackkrida
Does what the title says.
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon …
```
=> Add `minimum-change-threshold` to bundle size job and ignore language files

README.md
Related to #1711 by @ramadanomar and #1712 by @zackkrida 
A lot of our utility tools are buried in contributor handbook and past issues. This change looks to improve by addind a new Frontend Component Section and adding some more details to the Technology section
=> Doc improvement

pnpm-lock.yaml
Fixes #1718 by @sarayourfriend
Ran the command from the warning, 
```
WARN  Browserslist: caniuse-lite is outdated. Please run:                                                                               10:29:51
npx browserslist@latest --update-db
Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
```
and updated the libs.
This can be checked by running the command
```
pnpm dev
```
this time no warning will pop up.
<details>
```
Version 1.1
Suite D4700
San …
```
=> fixed warning for browserslist

src/components/VAudioDetails/VAudioDetails.vue
Fixes #1587 by @panchovm
Check PR #1611 for more info
Adds the correct meta-element styles.
Select Audio, Search any title and check the meta elements
<details>
```
Version 1.1
Suite D4700 …
```
=> Incorrect text styles in metadata information

src/components/VAudioTrack/layouts/VFullLayout.vue, src/locales/en.json, test/unit/specs/components/AudioTrack/v-full-layout.spec.js
Fixes #1341 by @AetherUnbound 
Replace the "Download" with "Go to audio's website", a text in line with the Image Details page. We step back in offering downloading audio directly from Openverse.
Run the project and visit any audio details page to see the updated button.
<details>
```
Version 1.1
Suite D4700 …
```
=> Update Audio and Image's action button text

src/composables/use-hide-on-click-outside.js
Fixes #1725  by @obulat 
Removed the event listener in src/composables/use-hide-on-click-outside.js
<details>
```
Version 1.1
Suite D4700
indicated in the …
```
=> Clean event listener on `use-hide-on-click-outside` composable

src/components/VAudioTrack/VPlayPause.vue, src/components/VButton.vue, src/components/VTabs/VTab.vue
Fixes #1181 by @dhruvkb
Updated the variant name to plain--avoid in VPlayPause.vue, updated :
```
/**
* Sets the button variant to `plain-dangerous` to manually handle focus states.
* Sets the connections (none-rounded corners) for the button based on the layout.
*/
const buttonProps = computed(() => {
const variant = 'plain-dangerous' as ButtonVariant
return { variant, connections: layoutConnectionsMap[props.layout] }
})
```
to
```
/**
* Sets the button variant to `plain--avoid` to manually handle focus states.
* Sets the connections (none-rounded corners) for the button based on the layout.
*/
const buttonProps = computed(() => {
const variant = 'plain--avoid' as ButtonVariant
return { variant, connections: layoutConnectionsMap[props.layout] }
})
```
No errors are given at runtime. …
=> Updated variant name from `plain-dangerous` to `plain--avoid`

.github/ISSUE_TEMPLATE/design_changes.md
Fixes #1667 by @panchovm 
Added an issue template for design-related changes at : ```.github\ISSUE_TEMPLATE\design_changes.md```
Reports no error upon executing ``` pnpm dev```
<details>
```
Version 1.1
Suite D4700 …
```
=> Add design issue template

src/components/VAudioTrack/meta/VWaveform.stories.mdx, src/utils/sentry-config.ts
Fixes #1743 by @krysal
Related to #1738 by @obulat 
- Run Storybook and see the waveform story page: http://localhost:54000/?path=/story/components-audio-track-waveform--message
- Look at the terminal when running the project normally, there should not be more warnings of the style `$sentry.captureException(), but Sentry plugin is disabled. Arguments:...`
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to …
```
=> Fix `VWaveform` story and silence mocked `$sentry` call logs

src/components/VHeader/VHeaderFilter.vue
Related to #1748 by @zackkrida 
This PR only renders the filter sidebar/modal on the clientside, to prevent a current portal SSR issue that borks the entire site.
Follow the reproduction steps for #1748 locally and observe that the problem doesn't occur.
<details>
```
Version 1.1
Suite D4700 …
```
=> Render filters sidebar clientside only (hotfix for #1748)

.husky/pre-commit
Fixes #1770 by @obulat
This PR replaces a `pnpx` command with `pnpm` in the pre-commit hook.
When committing a new change on main, you should see that you are making network requests to load `lint-staged`. On this branch, you are re-using the `lint-staged` that is already saved in node-modules.
<details>
```
Version 1.1
Suite D4700
By …
```
=> Use the local lint-staged

README.md
As part of testing out #1717, I noticed two things:
1. The provided `docker run` command didn't clean up after itself.
2. I instinctively tried to use the link that Nuxt provided, only to find that I ran into some really wacky cert issues when I did. Since I had only peaked at the docker steps and not the HTTPS setup, I added a caveat (which sort of mirrors the https notes) _not_ to use the link Nuxt provides.
If the second point is one y'all think others won't run into, we can drop that commit. It might just be my unfamiliarity with the frontend & only reading the part of the README that seemed it would get me up and running :slightly_smiling_face:
Run the altered command, stop the container, and ensure it no longer exists afterwards. …
=> Always clean up docker container on exit, add caveat to README

src/components/VAudioDetails/VAudioDetails.vue, test/unit/fixtures/audio.js, test/unit/specs/components/VAudioDetails/v-audio-details.spec.js
Fixes #878 by @AetherUnbound 
Shows the multiple file types of the audio track in the information section when available.
1. Run the project `pnpm dev`
2. Look for an audio track with multiple file types, which currently are only provided by **Freesound**, e.g. http://localhost:8443/audio/685531e7-fb32-4618-b9c1-472bdc3ff059
3. See the "Format"
<details>
```
Version 1.1
Suite D4700 …
```
=> Show all filetypes of audio in details page

src/components/VContentReport/VContentReportForm.vue
Fixes #1784 by @obulat
> Updates this line to `media.foreign_landing_url` instead of `media.url`:
> 
> https://github.com/WordPress/openverse-frontend/blob/bf0c72e5ea660354e20ffa33a4caf0abd65a5db9/src/components/VContentReport/VContentReportForm.vue#L13
<details>
```
Version 1.1
Suite D4700 …
```
=> The link to report at the source is incorrectly linking to the direct URL

.github/workflows/ghcr.yml
This PR adds caching to the Docker build step to speed up builds. Without the cache, it takes ~5m to build the images.
- [`build-push-action` cache docs](https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#cache-backend-api)
<details>
```
Version 1.1
Suite D4700 …
```
=> Add cache to speed up the Docker build step

src/composables/use-dialog-content.js, src/composables/use-focus-on-hide.ts, src/utils/reakit-utils/focus.ts
Fixes #947 by @sarayourfriend
This PR converts use-focus-on-hide to TS.
<details>
```
Version 1.1
Suite D4700
(b) The contribution …
```
=> Convert use-focus-on-hide to TS

src/components/VContentSwitcher/VSearchTypeItem.vue, src/constants/media.ts
Fixes #1315 by @zackkrida
This PR changes the status of audio to supported and replaces a hard-coded string with a constant.
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the open source …
```
=> Convert audio as a supported media type

src/components/VContentSwitcher/VMobileMenuModal.vue, src/components/VHeader/VHeaderFilter.vue, src/components/VHeader/VPageMenu/VMobilePageMenu.vue, src/components/VModal/VModal.vue, src/composables/use-focus-on-show.ts, src/composables/use-media-query.ts, src/composables/use-supported.ts, src/utils/try-on-mounted.ts, src/utils/try-on-scope-dispose.ts
Fixes #1730 by @obulat
Fixes #946 by @sarayourfriend
Fixes #1787 by @obulat
This PR refactors the Modals for Pages menu and Filter menu to use the VModal component instead of duplicating its functionality. This will help when we convert the components and composables to TypeScript.
The mobile modals should work as they currently do. When opened, they should focus on the first tabbable element, or the element that's passed to them.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted …
```
=> Simplify mobile modals

feat/feature-flags.json, src/components/VContentSwitcherOld/VMobileMenuModal.vue, src/components/VContentSwitcherOld/VSearchTypeButton.vue, src/components/VContentSwitcherOld/VSearchTypeItem.vue, src/components/VContentSwitcherOld/VSearchTypePopover.vue, src/components/VContentSwitcherOld/VSearchTypeRadio.vue, src/components/VContentSwitcherOld/VSearchTypes.vue, src/components/VContentSwitcherOld/meta/VSearchTypePopover.stories.mdx, src/components/VFourOhFour.vue, src/components/VHeaderOld/README.md, src/components/VHeaderOld/VFilterButton.vue, src/components/VHeaderOld/VHeaderFilter.vue, src/components/VHeaderOld/VHeaderMenu.vue, src/components/VHeaderOld/VHeaderOld.vue, src/components/VHeaderOld/VLogoButtonOld.vue, src/components/VHeaderOld/VPageMenu/VDesktopPageMenu.vue, src/components/VHeaderOld/VPageMenu/VMobilePageMenu.vue, src/components/VHeaderOld/VPageMenu/VPageList.vue, src/components/VHeaderOld/VPageMenu/VPageMenuButton.vue, src/components/VHeaderOld/VSearchBar/VSearchBar.vue, src/components/VHeaderOld/VSearchBar/VSearchButton.vue, src/components/VHeaderOld/VSearchBar/meta/VSearchBar.stories.mdx, src/components/VHeaderOld/meta/VFilterButton.stories.mdx, src/components/VHeaderOld/meta/VHeader.stories.mdx, src/components/VModal/VModalContent.vue, src/layouts/default.vue, src/pages/index.vue, src/pages/preferences.vue
Fixes #1803 by @obulat
This PR adds a `new_header` feature flag which will contain all the work on the new header.
I renamed the current header directory and the component from `VHeader` to `VHeaderOld`, but did not rename the other components inside the new `VHeaderOld` directory (since they are different anyways because of the path, and the new components will probably have different names. If not, we can rename them later)
Run `pnpm dev`. Everything should work as it currently does.
Go to `http://localhost:8443/preferences` and check the `new_header` flag:
Now, open a search page. You should be seeing the new header, which currently is the same as the old one, except it doesn't have the pages menu and the Openverse wordmark:
[best_practices]:https://git-scm.com/book/en/v2/Distributed-Gi …
=> Add `new_header` flag

src/data/api-service.ts, src/data/media-service.ts, src/utils/search-query-transform.ts, test/tapes/search/audio/license_type=commercial&license=cc0&searchBy=creator&creator=cat_close.json5, test/tapes/search/audio/license_type=commercial&license=cc0&searchBy=creator&creator=cat_keep-alive.json5, test/tapes/search/audio/q=birds&source=freesound_close.json5, test/tapes/search/audio/q=birds_close.json5, test/tapes/search/audio/q=birds_keep-alive.json5, test/tapes/search/audio/q=cat&license=cc0_keep-alive.json5, test/tapes/search/audio/q=cat&license_type=commercial_close.json5, test/tapes/search/audio/q=cat_close.json5, test/tapes/search/audio/q=cat_keep-alive.json5, test/tapes/search/audio/q=dog_close.json5, test/tapes/search/audio/q=galah&license_type=modification_keep-alive.json5, test/tapes/search/audio/q=galah_close.json5, test/tapes/search/audio/q=galah_keep-alive.json5, test/tapes/search/audio/q=honey_close.json5, test/tapes/search/audio/q=honey_keep-alive.json5
Fixes #1800 by @krysal 
Wow, I struggled to work with the media services. I cannot wait to refactor some of that code.
Anyway, this PR adds a special case to add `peaks=true` to all audio and related audio searches. To do so I also had to upgrade the related media method to allow for query parameters. Maybe that will be a nice addition in the future.
I'm not sure about tests here. Do we have any to verify the API endpoint paths are correct? Otherwise, this is covered by the fact that the visual regression tests would change if the peak data isn't downloaded. Still, it seems like we need better test coverage around the API endpoints in general.
Check on client-rendered searches that the `peaks=true` is present for all audio API search requests, and on related audio searches. Finally, make …
=> Add peaks=true to all audio searches

src/components/VSnackbar.vue
This PR updates the `max-w-full` class applied on the snackbar to account for the space left on both sides.
0. Trigger the snackbar on `main` using a mobile phone.
1. See that it is off towards the right side.
2. Check out this PR and trigger the snackbar again using a mobile phone.
3. See that it is aligned in the center.
| `main` | This PR |
|-|-|
| ![Screen Shot 2022-09-14 at 20 45 26](https://user-images.githubusercontent.com/16580576/190214018-574d5c7c-ee00-48ac-8594-bb23e6fd205e.png) | ![Screen Shot 2022-09-14 at 20 45 07](https://user-images.githubusercontent.com/16580576/190214002-bce2d9c9-76ff-4b89-9b18-e5d5ef3c8f88.png) |
<details> …
=> Fix width of snackbar on mobile devices

nuxt.config.ts
Fixes #1602 by @sarayourfriend
Nuxt redirect module checks all the requests trying to `decodeURI` them. If there are undecodeable characters, it shows a server error page. By adding the `onDecodeError` handler we make Nuxt handle the undecodeable route and show the client-side error page.
If you go to http://search-production.openverse.engineering/image/737e5a87-%A311b-4d78-9d05-69a7dfaald/, you should see the Nuxt server error page (because of `%A`). The same should happen if you try opening http://localhost:8443/image/737e5a87-%A311b-4d78-9d05-69a7dfaald/ on main. In this branch, you should see the yellow Openverse error page for the same URL
<details> …
=> Prevent server errors if the URL has invalid characters

src/assets/icons/source.svg, src/components/VButton.vue, src/components/VHeader/VContentSettingsButton.vue, src/components/VHeader/meta/VContentSettingsButton.stories.mdx, src/components/VIconButton/VIconButton.vue, src/locales/en.json
Fixes #1805 by @obulat
This PR adds the `VContentSettingsButton` for the mobile version of the new header.
Run the Storybook (`pnpm storybook`) and check `VHeader`/`VContentSettingsButton`. Check that the `pressed` and `areFiltersSelected` variants match the mockups: https://www.figma.com/file/KxkZmBNk218V2Fke1GeYCu/New-header-component?node-id=522%3A59429
<details>
```
Version 1.1
Suite D4700
license document, but changing …
```
=> Add VContentSettingsButton

.github/workflows/ci.yml
Fixes #1774 by @obulat
This PR makes the Nuxt build check and the Playwright CI tests run in parallel. See the linked issue for more context on the reasons.
The green CI should be enough.
<details>
```
Version 1.1
Suite D4700 …
```
=> Run Nuxt build and Playwright CI in parallel

src/components/VAudioTrack/layouts/VFullLayout.vue, src/components/VAudioTrack/layouts/VRowLayout.vue
Fixes #1856 by @obulat 
This PR hide the 'interpunct' character from the screenreaders
<details>
```
Version 1.1
Suite D4700
(b) The …
```
=> Hide the 'interpunct' character from the screenreaders

CONTRIBUTING.md
Hi,
This PR fixes #1884 by @0kyn 
This is an update of some outdated information in CONTRIBUTING.md file
<details>
```
Version 1.1
Suite D4700
indicated in …
```
=> Update outdated information in `CONTRIBUTING.md` file

src/components/VHeader/VSearchBar/VSearchBar.vue
Switching to pre-commit for our linting purposes broke our CI. This PR fixes that.
0. See that CI has passed.
1. Please approve immediately.
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the …
```
=> Fix alignment to pass Prettier check

src/components/VHeader/VSearchBar/VSearchBar.vue
Fixes #1890 by @obulat
This PR makes VRecentSearches a component that is only loaded on the client, not on the server.
On main, run the app. Go to a server-rendered search page (http://localhost:8443/search/?q=cat&ff_new_header=on) and look at the console. You should see the warnings like the ones in the linked issue.
On this branch, you should not see the warnings.
<details>
```
Version 1.1
Suite D4700
license document, …
```
=> Make VRecentSearches ClientOnly

src/components/VHeader/VHeaderInternal.vue, src/components/VHeader/VSearchBar/VSearchBar.vue
Fixes #1898 by @obulat
This PR adds a dark-charcoal background and sets the text (icon color) to white on hover for the menu button on the inner pages.
Enable the new header, open the '/about' page on mobile width and check that the menu button changes on hover, matching the Figma mockups.
<details>
```
Version 1.1
Suite D4700
By making …
```
=> Add hover styles to the mobile internal menu button ('hamburger' menu button)

src/locales/en.json
Fixes #1910
ocurred -> occurred
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, to the …
```
=> Fix typo in word 'occurred'

src/pages/image/_id.vue
Fixes #1909 by @zackkrida 
added a tailwind css class that trucates the title of an image to 2 lines.
[screenshot](https://ibb.co/C2BbvLt)
*open an image result.
*edit the title of the image (h1 tag) to a very long title. for example, paste a lorem ipsum paragraph.
*the title should be 2 lines long.
<details>
```
Version 1.1
Suite D4700 …
```
=> Fix - get this media button

.github/actions/setup-node-env/action.yml
Fixes #1922 by @obulat
Updates action-setup to update the Node version it uses (from version 12 that's deprecated on GitHub).
CI tests should pass.
<details>
```
Version 1.1
Suite D4700 …
```
=> Update action-setup to v.2.2.4

src/components/VFourOhFour.vue
Fixes #1972 by @obulat 
The prop Variant was removed in [this](https://github.com/WordPress/openverse-frontend/pull/1973/commits/00d2240f0f3e4e4d32eddb0592b3c1445f371346) Pull request. There was a redundant prop in `VFourOhFour.vue` file. So ` :language-props="{ variant: 'yellow' }" `  was removed from `VFourOhFour.vue`
<details>
```
Version 1.1
Suite D4700
Developer's …
```
=> Remove redundant language-prop 'variant' from VFourOhFour.vue

src/composables/use-pages.ts
Fixes #1988 by @obulat 
Changed the URL for Get involved link in the new header navbar from the [link to the GitHub repository](https://github.com/WordPress/openverse/) to [Openverse Make Handbook](https://make.wordpress.org/openverse/handbook/).
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, I certify …
```
=> Updated the URL for Get involved link in the navbar

src/layouts/default.vue
Related to #1979
This PR re-adds the padding to the filters sidebar that was accidentally removed in #1959. The VR tests did not catch this because the `maxDiffPixelRatio` was too high.
<details>
```
Version 1.1
Suite D4700 …
```
=> Fix filters sidebar regression after merge

.github/workflows/ci.yml, src/components/VBanner/VBanners.vue, src/components/VHeaderOld/VHeaderOld.vue, src/components/VHeaderOld/VSearchBar/VSearchBarOld.vue, test/playwright/utils/navigation.ts, test/playwright/visual-regression/pages/pages-single-result.spec.ts, test/playwright/visual-regression/pages/pages-with-old-header.spec.ts, test/playwright/visual-regression/pages/pages.spec.ts
Fixes #2041 by @obulat
This PR splits the Playwright tests in CI into two separate steps: VR and e2e. This makes the tests faster, but the drawback is that the CI now builds the Nuxt app twice.
The CI now lasts less than 13 minutes. I was surprised to learn that e2e tests take longer than the VR tests.
This PR also adds some changes to stop the flakiness that can currently be seen on main:
- it manually sets the search input height for screens wider than `md` to 3rem (48px) to make sure that the height of the input does not cause flakiness anymore. It's a hotfix that I think should be OK for now because we are not going to be use the old header soon.
- it adds the cookies that affect the layout to the context in the pages Playwright tests.
The CI should pass. …
=> Split the e2e and vr tests

.github/actions/production-frontend-deploy/action.yml, .github/actions/staging-frontend-deploy/action.yml
Follow up of #2059 by @krysal
This should fix the CI pipeline.
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and …
```
=> Fix secret turned input in action

.github/actions/setup-node-env/action.yml, .github/workflows/bundle_size.yml, .github/workflows/ci.yml, .github/workflows/generate_pot.yml, .github/workflows/gh-pages.yaml, bin/install-pre-commit.sh, package.json
Fixes #2064 by @dhruvkb
This PR updates the `curl` command to automatically use the `GITHUB_TOKEN` env var when available so that setting up pre-commit in CI doesn't fail due to a rate limiting error.
errors.
<details>
```
Version 1.1
Suite D4700 …
```
=> Authenticate with `GITHUB_TOKEN` when setting up pre-commit

README.md
Fixes #2097  by @anton202 
Reformat of:  how to create a component section in the main readme file
errors.
<details>
```
Version 1.1
Suite D4700
have the right to submit …
```
=> Reformat of how to create a component section in the main readme file

feat/feature-flags.json, test/playwright/e2e/homepage.spec.ts, test/playwright/e2e/migration-banner.spec.ts, test/playwright/e2e/mobile-menu-old.spec.ts, test/playwright/e2e/translation-banner.spec.ts, test/playwright/utils/navigation.ts, test/playwright/visual-regression/components/audio-results-old.spec.ts, test/playwright/visual-regression/components/header-old.spec.ts, test/playwright/visual-regression/pages/homepage-old.spec.ts, test/playwright/visual-regression/pages/pages-with-old-header.spec.ts, test/unit/specs/stores/ui-store.spec.js
Enable the new header flag for Openverse on staging only.
=> Enable new header in staging

feat/feature-flags.json
errors.
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon …
```
=> Set the new_header flag to enabled

.github/actions/production-deploy/action.yml, .github/workflows/ghcr.yml, .github/workflows/rollback.yml, DEPLOYMENT.md
Update production deployment actions to point to the new production.openverse.org (which is being used in the wordress.org/openverse) iFrame. 
errors.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or …
```
=> Update deployment actions for production.openverse.org

package.json, src/components/VHeader/VHeaderInternal.vue, src/components/VModal/VInputModal.vue, src/components/VModal/VModal.vue, src/components/VModal/VModalContent.vue, src/composables/use-dialog-content.ts, src/composables/use-dialog-control.ts, src/composables/use-focus-on-show.ts, src/composables/use-focus-trap.ts, test/playwright/README.md, test/playwright/e2e/header-internal.spec.ts, test/playwright/utils/navigation.ts
Fixes #1433 by @panchovm 
Fixes #2105 by @obulat
This PR adds scroll lock and focus trap cleanup on beforeUnmounting of modal in `useDialogControl`.
Run the app. Test the app with the new header on and mobile width. You should be able to navigate from the homepage to content pages. All the links should be interactive, and all content/search/single result pages should be scrollable. Contrast that with the non-interactive content pages (eg., "About") on https://staging.openverse.org: if you navigate to About page from the homepage, the page is non-scrollable, and you cannot click any link.
errors.
<details>
<summary>Developer Certificate …
=> Fix internal header menu

feat/feature-flags.json
Enable the new header feature flag in production.
=> Enable new header feature flag in production

src/locales/scripts/read-i18n.js
Fixes #2159 by @bengreeley
This PR fixes a bug in `read-i18n.js` that caused the `msgctxt` field to only have one parent in the path. It replaces the generation of ancestry during parsing with registration of parent. Then ancestry can be computed by walking up the tree when needed.
Compare the POT file generated by this PR with the old. The new one has correct ancestry for nodes deeper than two levels. Eg:
```diff
#. Do not translate words between ### ###.
- msgctxt "fuzziness.description"
+ msgctxt "search-guide.example.fuzziness.description" 
msgid "You can use ###highlight### to specify some fuzzy logic to the term according to the ###link### — the number of one character changes that need to be made to one string to make it the same as another string."
msgstr ""
```
`Update …
=> Ensure the lineage is traced correctly

nuxt.config.ts
Fixes #2164 by @obulat 
This PR correctly sets up the sitemap module with all available `locales`.
Run the app and go to https://openverse.org/sitemap.xml. Look at the source. You should see all localized URLs of the same page grouped.
errors.
<details>
```
Version 1.1
Suite D4700
By making a …
```
=> Group localized URLs of the same page in the sitemap

src/components/VFilters/VSearchGridFilter.vue
Fixes #2129 by @dhruvkb
This PR removes the ring offset from the 'Clear filters' button because that causes the ring to appear thicker. Now the thickness of the focus ring is consistent with the rest of the app.
0. Check out the PR and run the dev server.
1. Search for a term.
2. Apply a filter. You will see the Clear filters button.
3. Hover over the button, note the outline style.
4. Focus the button with the keyboard, note the outline style.
5. The style should be the same.
https://user-images.githubusercontent.com/16580576/217169268-b7875fb7-a412-43e4-9d27-ac6aa0fb6847.mov
^ The first occurrence is the move hover and the second is the keyboard focus
errors.
https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Pr …
=> Remove ring offset to reduce ring thickness

src/static/opensearch.xml
This is a quick PR to change the URL in opensearch.xml to openverse.org
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source …
```
=> Update URL in opensearch.xml

src/components/VHomepageContent.vue
Fixes #2176 by @obulat
This is a quick fix for the heading level on the homepage.
Go to the homepage and checkout the a11y outline. There should be a level 1 heading.
errors.
<details>
```
Version 1.1
Suite D4700
(a) The contribution …
```
=> Use h1 for the main heading on the homepage
